### ISSUE TITLE
MW supplement fresh look, part 5: Missed entries from the Annexure pages

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#101]
Just filtered these lines from my earlier work at this forum.

[missed entries (Annexure).txt](https://github.com/sanskrit-lexicon/MWS/files/6031469/missed.entries.Annexure.txt)

There are 60 entries in here.

These are to be properly "applied" as "rev" to existing main entries, or added as "sup" to the main entries (at resp. places, as the case may be.)

**Comment by Andhrabharati** [comment]
Just posting the WIP file.

[missed entries (Annexure)-1.txt](https://github.com/sanskrit-lexicon/MWS/files/6037562/missed.entries.Annexure.-1.txt)

**This is bringing out some interesting observations indeed.**

Pl. have a look at the comments under
A(1309,2) aṅgāraka-yantra
A(1310,2) adhi-√ji
R(1322,1) ún-nīta—śikha
R(1324,3) kāśyapī-bālākya-māṭharī-pútra
R(1332,2) vrā́.

Probably by another session, this work would be over as missing entries-2, for @funderburkjim to take over.

@------------------------------
The 7 comp. word headers listed here before [anyataḥ, anyāya, avāk, avāg, aṣṭā-daśa, Nir, bahiḥ] are taken out from the list, as it was only partially done earlier while discussing on "Annexure entries" at the forum.

As was done sometime later, while proofing the annexure text, noted that over 470 such headers were listed in annexure pages. (The list is put here.)
[Comp. word headers in Annexure pages.txt](https://github.com/sanskrit-lexicon/MWS/files/6037576/Comp.word.headers.in.Annexure.pages.txt)

They need to be compared with the main page headers, to decide which of them are to be added or revised or ignored.
As the number is quite a big one, separated the "headers" from the "missing HW entries".
Shall be posting those comp. word headers as another portion [as missed comp. word headers (Annexure)] later.

**@gasyoun , you may note how much "integration work" (of annexure) is still pending in this MW [refer your query to @funderburkjim elsewhere on this point].**

**Comment by Andhrabharati** [comment]
BTW, can someone tell me why I am being asked by Github to "verify my device" time and again?
(getting the mail almost every 3rd or 4th time that I go for logging in here)

**Comment by gasyoun** [comment]
> (getting the mail almost every 3rd or 4th time that I go for logging in here)

Never seen such before.

**Comment by Andhrabharati** [comment]
> > (getting the mail almost every 3rd or 4th time that I go for logging in here)
> 
> Never seen such before.

This happens with logging at my computer (which has "never store history & cookies" setting in the Firefox browser that I use).

With mobile (which I use during my daytime to quickliy reply with just text matter, having no attachments; for replies or original posts that need files either inserted or attached, I have to use the computer) this never occurred, as I never have to login at github; does it mean, like Google which always keeps the Android user logged in (by default), github also has such always logged setting 'secretly' stored somewhere in the Android phone?

**Comment by Andhrabharati** [comment]
Finished the basic HWs missed from the annexure pages.

[missed entries (Annexure)-final.txt](https://github.com/sanskrit-lexicon/MWS/files/6043580/missed.entries.Annexure.-final.txt)

This time the <Ls> entry is shown only at few places.

All the entries are with the remarks about the corrections or attention needed.

**The discussion at A(1326,3) -pâcala or -pâdri may be looked at.
This shows how one can (sometimes) go wrong in interpreting the matters.**

**Comment by Andhrabharati** [comment]
**Now started with the comp. word headers, from the annexure.**

Out of the 470+ entries there, just 8 are to be seen in the present mw data. 
[a-divā, ana-ḍuḍ, a-nirdaya, a-patita, a-parāvṛtta, a-parāvṛtti, a-rāga-dveṣa, kamaṇḍalu]

And in those 8, two are wrongly rendered!
```
;; BEGIN
A(1311,1) <s>ana-ḍuḍ</s> (in comp. for <s>°ḍuh</s>)
<L>4840.1<pc>1311,1<k1>anaḍud<k2>anaḍ-úd<e>2	<s>anaḍ-úd</s> 	¦ (in comp. for <s>°ḍuh</s>) <info n="sup"/>	<LEND>
;; HW accent wrongly marked; and the hyphen place is wrong.
;; END

```

```
;; BEGIN
A(1324,1) <s>kamaṇḍalu</s> (in comp.)
<L>43904.1<pc>1324,1<k1>kamaṇḍalucaryā<k2>kamaṇḍalu-caryā<e>3	<s>kamaṇḍalu-caryā</s> 	¦ (in <ab>comp.</ab>) <s>-caryā</s>, <lex>f.</lex> the practice of carrying a water-jar, <ls>Baudh.</ls><info n="sup"/><info lex="f"/>	<LEND>
;; The full text at annexure pages is thus-
;; A(1324,1) kamaṇḍalu (in comp.); -caryā. f. the practice of carrying a water-jar, Baudh.
;; The ; character demarcating the comp. word header and the actual comp. word is missed and the full text is placed as a single entry as L-43904.1 data.
;; This needs to be split as two entries, one the comp. word header, and then the comp. word
;; END

```
Probably few others might also be present (without the "sup" or "rev" marking); but that would be a very rare case, looking at the state of this mw data having been handled.

So, all ~470 entries are to be checked for proper positioning and "integration" with the main pages' data.

**Comment by Andhrabharati** [comment]
Just pushed the "missed entries (Annexure)-final.txt" file to mwtranscode folder, the place allotted by @funderburkjim for my work-files.

**Comment by funderburkjim** [comment]
@Andhrabharati    I'll be able to start looking at these soon.  
* Is your work finished?
* Which file (or files)  should I work from?

**Comment by Andhrabharati** [comment]
> Just pushed the **missed entries (Annexure)-final.txt** file to mwtranscode folder, the place allotted by @funderburkjim for my work-files.

**Comment by funderburkjim** [comment]
OK - Thanks.

**Comment by Andhrabharati** [comment]
"missed comp. word headers" may take 2 more days- would you wait for it to commit?

or do we do those alongwith the "sup"s, in another session?

**Comment by funderburkjim** [comment]
Based only on a cursory look at 'missed comp. word headers'  list.  it seems that these will be
"sup" items that are relatively easy to do, with the hardest part will be deciding what L-number to give them.

The missed 'or/and' of 	`missed entries (Annexure)-final.txt`  at the moment seem difficult to do.

First impression is that the 'missed comp. word headers'  can be considered separately
from the 'missed entries (Annexure)-final.txt' -- they seem independent.

**Comment by Andhrabharati** [comment]
let or/and cases be postponed. there are plenty more grouping cases to be done in main data as well.

**Comment by Andhrabharati** [comment]
ok, shall hold the missed comp. word headers work for timebeing.

**Comment by funderburkjim** [comment]
Re:
```
R(1323,3) kakā́tika (AV.)

<L>41412<pc>241,1<k1>kakāṭikā<k2>kakāṭikā<e>1
<s>kakāṭikā</s> ¦ <lex>f.</lex> a particular part of the frontal bone, <ls>AV. x, 2, 8</ls><info lex="f"/>
<LEND>
also the ending long vowel ā to be changed to a short letter a.
```

Am NOT changing ending vowel to short 'a'.  This is a feminine.  Confirmed AP90.
Did add the accent.

**Comment by Andhrabharati** [comment]
no issues, keep going!

**Comment by Andhrabharati** [comment]
btw, is the missed entry portion being covered in this session?

**Comment by funderburkjim** [comment]
I'm working with 'missed entries (Annexure)-final.txt', but have not yet tackled the
many alternate headword suggestions at the beginning of that file.

**Comment by funderburkjim** [comment]
> R(1324,2) 1. kavya (erase 1)

I'm NOT erasing the homonym.  
There is a homonym 2  (a denominative verb) on p. 265.  So I think we need to retain the homonym 1.

**Comment by funderburkjim** [comment]
I think I am handling gopādri and gopācala as I originally thought,  and this is different from AB's 
suggestion.  When the change is committed to server, AB can review  and discuss further.

**Comment by funderburkjim** [comment]
Here is the way gopācala and gopādri look after proposed change:
```
<L>67903<pc>368,2<k1>gopācala<k2>gopācala<e>3
<s>gopā<srs/>cala</s> ¦ <lex>m.</lex> ‘cowherd-mountain’ = <s>gopāla-giri</s>, <ls>Uttamac. 2 602.</ls><info lex="m"/>
<LEND>
<L>67903.1<pc>1326,3<k1>gopācala<k2>gopācala<e>3A
¦ <lex>m.</lex> <ab>N.</ab> of Gwalior, <ls>Inscr.</ls><info or="67903.1,gopAcala;67906.1,gopAdri"/><info n="sup"/><info lex="m"/>
<LEND>

<L>67906<pc>368,2<k1>gopādri<k2>gopādri<e>3
<s>gopā<srs/>dri</s> ¦ <lex>m.</lex> = <s>°pā<srs/>cala</s>, <ls>343.</ls><info lex="m"/>
<LEND>
<L>67906.1<pc>1326,3<k1>gopādri<k2>go—pādri<e>3A
¦ <lex>m.</lex> <ab>N.</ab> of Gwalior, <ls>Inscr.</ls><info or="67903.1,gopAcala;67906.1,gopAdri"/><info n="sup"/><info lex="m"/>
<LEND>
```
Please indicate revision if you think necessary.

**Comment by funderburkjim** [comment]
```
A(1330,1) pari-nir-mita (p. 596, col. 2, read ‘-vaśa-vartin’ and ‘cf. para-nirmita-v°-v°’)
<L>117823<pc>596,2<k1>parivaśavartin<k2>pari-vaśa-vartin<e>3

Changed headword to pari-nir-mita-vaśa-vartin
```

**Comment by Andhrabharati** [comment]
> ```
> 
> Please indicate revision if you think necessary.

I've no comments about this revision which clubs the entries of "go-" comp. words with "gopa-" comp. words.

I think I don't have any more to say than what I already mentioned in my **missed entries (Annexure)** file.

However just putting Jim's version as above, and my version (as indicated in my file referred) below [as a summary]-

**Jim's version**
All under gopa- (indicating entries in p. 368)
```
<L>67903<pc>368,2<k1>gopācala<k2>gopācala<e>3	<s>gopā<srs/>cala</s> ¦ <lex>m.</lex> ‘cowherd-mountain’ = <s>gopāla-giri</s>, <ls>Uttamac. 2 602.</ls><info lex="m"/>	<LEND>
<L>67903.1<pc>1326,3<k1>gopācala<k2>gopācala<e>3A	¦ <lex>m.</lex> <ab>N.</ab> of Gwalior, <ls>Inscr.</ls><info or="67903.1,gopAcala;67906.1,gopAdri"/><info n="sup"/><info lex="m"/>	<LEND>

<L>67906<pc>368,2<k1>gopādri<k2>gopādri<e>3	<s>gopā<srs/>dri</s> ¦ <lex>m.</lex> = <s>°pā<srs/>cala</s>, <ls>343.</ls><info lex="m"/>	<LEND>
<L>67906.1<pc>1326,3<k1>gopādri<k2>go—pādri<e>3A	¦ <lex>m.</lex> <ab>N.</ab> of Gwalior, <ls>Inscr.</ls><info or="67903.1,gopAcala;67906.1,gopAdri"/><info n="sup"/><info lex="m"/>	<LEND>
```


**AB's version**
Under go- (indicating entries in p. 343)
```
<L>67229.1<pc>1326,3<k1>gopācala<k2>go—pâcala<h>a<e>3	<s>go—pā<srs/>cala</s> <hom>a</hom> 	¦ <lex>m.</lex> <ab>N.</ab> of Gwalior, <ls>Inscr.</ls><info or="67229.1,gopAcala;67229.2,gopAdri"/><info n="sup"/><info lex="m"/>	<LEND>
<L>67229.2<pc>1326,3<k1>gopādri<k2>go—pādri<h>a<e>3	<s>go—pā<srs/>dri</s> <hom>a</hom> 	¦ <lex>m.</lex> <ab>N.</ab> of Gwalior, <ls>Inscr.</ls><<info or="67229.1,gopAcala;67229.2,gopAdri"/><info n="sup"/><info lex="m"/>	<LEND>
```

Under gopa- (indicating entries in p. 368)
```
<L>67903<pc>368,2<k1>gopAcala<k2>gopAcala<e>3	<s>gopA<srs/>cala</s> ¦  <lex>m.</lex> ‘cowherd-mountain’ = <s>gopAla-giri</s>, <ls>Uttamac. 2 602.</ls><info lex="m"/>
<L>67906<pc>368,2<k1>gopAdri<k2>gopAdri<h>b<e>3	<s>gopA<srs/>dri</s> <hom>b</hom> ¦ <lex>m.</lex> = <s>°pA<srs/>cala</s>, <ls>343.</ls><info lex="m"/>
```

Let's not spend more time on just this; we have **many many more to be addressed yet**.

**Comment by Andhrabharati** [comment]
> 
> 
> ```
> A(1330,1) pari-nir-mita (p. 596, col. 2, read ‘-vaśa-vartin’ and ‘cf. para-nirmita-v°-v°’)
> <L>117823<pc>596,2<k1>parivaśavartin<k2>pari-vaśa-vartin<e>3
> 
> Changed headword to pari-nir-mita-vaśa-vartin
> ```

**I have identified more such **wrongly composed** comp. words (while digitising) in the file**, which would come out in due course (if we continue the exercise).
[As such, I had just limited to the annexure revision at the mentioned entry]

**Comment by Andhrabharati** [comment]
Incidentally the 343 in L-67906 is referring to its own page tagged here as  `<ls>`.

There are 3 types of such internal referencing- citing both page & column, only page, and only column. Probably all the three types could have the ` <pcol>` tagging.

**Comment by funderburkjim** [comment]
Next [commit of mw_iast.txt](https://github.com/sanskrit-lexicon/MWS/commit/dd526889bb399690822bf440be52216bbb345e53) finished. Approximately 450 lines changed.

See [revdoc/changes_2.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/changes_2.txt) for the changes applied to prior commit of mw_iast.txt.

These changes based on 3 files from AB, as mentioned above:
* [missed entries (Annexure)-final.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/missed%20entries%20(Annexure)-final.txt)
* [comments_edit (3.1-3.7)-AB remarks.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/comments_edit%20(3.1-3.7)-AB%20remarks.txt)
* [readme_added_comments-AB remarks.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/readme_added_comments-AB%20remarks.txt)

**Comment by gasyoun** [comment]
> Approximately 450 lines changed.

So these are more technical, not to be checked after by a human once again.

**Comment by funderburkjim** [comment]
They are what they are -- Most of these changes are technical  -- involving accents and reinterpretation of supplement records.   No fun for most humans -- If you look at the
commit links,  you can see at a glance what the changes entail.

**Comment by funderburkjim** [comment]
## a todo list

[revdoc/todo.md](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/todo.md) is derived from various of AB's files,
with a few of my comments thrown in.

@Andhrabharati  please feel free to edit this file, and to add sections to it.

I suggest that we further add 'status updates' to the sections as they occur.

**Comment by Andhrabharati** [comment]
Sorry to say that I am FORCED **to check the updated work all over again**, as I happened to notice the following not being fully attended to-

```
<L>16679<pc>94,3<k1>alāta<k2>alāta<e>1	<s>alāta</s> ¦ <lex>n.</lex> a fire-brand, coal, <ls>MBh.</ls> &c. <info n="rev" pc="1316,3"/><info lex="n"/>	<LEND>
;; My earlier remark here was ";; this marking is incomprehensible. there is no page-break nor a correction in here."
;; This has nothing to do with the "rev" and the markings are to be deleted.
;; Thus the entry would become as under-
;; <Ls>16679<pc>94,3<k1>alāta<k2>alāta<e>1	<s>alāta</s> ¦ <lex>n.</lex> a fire-brand, coal, <ls>MBh.</ls> &c.<info lex="n"/>	<LEND>
;; The Annexure mentions another headword which should be added as a "sup" here. 
;; A(1316, 3) alātacakra, n. a fire-brand carried around (-vat, ind.), MBh.; R. &c.
;; Thus the new entry would be as under-
;; <Ls>16679.1?<pc>1316,3<k1>alātacakra<k2>alāta-cakra<e>?	<s>alāta-cakra</s> ¦ <lex>n.</lex> a fire-brand carried around), <ls>MBh.</ls>; <ls>R.</ls> &c.
;; the markings here (esp. ?) should be corrected as appropriate.
<L>16679.2<pc>1316,3<k1>alātacakravat<k2>alāta-cakra—vat<e>3	<s>alāta-cakra—vat</s> ¦ (<lex>ind.</lex>) <info n="sup"/><info lex="ind"/>	<LEND>
```

**Though the two "sup" entries (16679.1 and 16679.2) are "done" as mentioned, the "rev" (for 16679) is not "done".**

**Comment by funderburkjim** [comment]
Yep, looks like I missed removing the 'rev' marking in 16679.
Will change locally, and add to corrections to mw_iast.txt for other mistakes that you discover in work so far.

**Comment by gasyoun** [comment]
> Glad you are doing all the checking.

This MW addenda seems tougher, than initially planned.

**Comment by Andhrabharati** [comment]
Much against my mind saying to re-look at the corrections done (as I mentioned earlier), I could not spend even a minute for the same (for unknown reasons) so far.

Hence decided to move on to the next phase of (i) adding the missed comp. word headers and then (ii) to review the "sup" marked entries (**leaving/deferring this re-looking for now**).

**Comment by Andhrabharati** [comment]
We can close this issue now, with a note that "the points identified to be considered yet" are put in a TODO list.
