### ISSUE TITLE
Typos under √ saMtuS

### ISSUE THREAD

**Issue by Jazirae** [sanskrit-lexicon/MWS#102]
Dict. listings under this root are misspelled, z is used where S should be.  Printed book pg. 1142.

**Comment by Andhrabharati** [comment]
@Jazirae 
can you paste a screenshot like this, showing the input and output encodings you've selected, to "see" the error you mentioned?
![image](https://user-images.githubusercontent.com/75209130/109391565-bca79f80-793d-11eb-92bc-badee60486d3.png)

**Comment by Jazirae** [comment]
I didn't notice what the input/outputs where set at, somehow they got changed from my preferences.  So to reproduce the problem I had to try various combinations.

![Screenshot_2021-02-27-21-08-56-38](https://user-images.githubusercontent.com/79756156/109392160-ac44f400-7940-11eb-9414-f81c6510521b.jpg)

![Screenshot_2021-02-27-21-09-13-12](https://user-images.githubusercontent.com/79756156/109392171-ba931000-7940-11eb-8937-eb4a545d6f79.jpg)

![Screenshot_2021-02-27-21-09-29-07](https://user-images.githubusercontent.com/79756156/109392184-c8489580-7940-11eb-8e2c-1f93fbf4ffb4.jpg)

**Comment by Andhrabharati** [comment]
@gasyoun, @funderburkjim 

is it not better to keep the input & output schemes the same, by default?

if the user is knowledgeable and keen enough, he would definitely be selecting the schemes differently (if that's what he wants).

**Comment by Andhrabharati** [comment]
@Jazirae 

The problem you faced occurs, when the default settings are there as- input: KH & output: slp1.

That's why I suggested to @funderburkjim to make both the schemes the same by default.

Even if one changes the input scheme first, I would suggest that the output also be automatically changed to it; the user would anyway be seeing it, as he is selecting the options & change the output option next, if he wants a different one.

**Comment by Jazirae** [comment]
I thought I had defaults set, as I said I don't know how they were changed.  Guess I'm not a keen user.  But shouldn't search results be correct regardless of the preferences selected?

I apologize if this is due to my ignorance.  But if I didn't have the hard copy of the book with me, I would be thinking "My gosh, I was wrong all these years on the spelling of this!" and I almost edited the book I'm writing to "correct" those words into the wrong spellings based on the online search results!

**Comment by Andhrabharati** [comment]
Luckily, you don't need to have a print copy most of the times, to cross-check.

Just click at the link shown on every search result page at the HWs, you will be shown he book page scan, may be in another window/tab on the browser.

![image](https://user-images.githubusercontent.com/75209130/109392718-b6b4bd00-7943-11eb-8f02-972bb975eb50.png)

**Comment by Jazirae** [comment]
Yes, this I know (thanks!) but have never had this problem before.  I don't
have time to crosscheck every search.

I changed my preferences back to what I want.  Does that set the default?
I'm using the mobile friendly database.

**Comment by Andhrabharati** [comment]
> 
> I apologize if this is due to my ignorance. 

No apologies required.

In fact, your observation gave a point for the Site maintaining team to "correct".

**Comment by Jazirae** [comment]
Great, thank you kindly.  And my profuse thanks for providing this
wonderful resource‼️  Must have been a HUGE labor of love!

💞🤗🙏🏼
Jazirae  (Jazzaray)

PS:  अपि  त्वम्  संस्कृतभाषया  वदसि ?  लिखसि  वा ?

**Comment by gasyoun** [comment]
> is it not better to keep the input & output schemes the same, by default?
If by default, input should be `simple`, output `IAST`, if you ask me.

> if the user is knowledgeable and keen enough, he would definitely be selecting the schemes differently (if that's what he wants).
Right.

> Even if one changes the input scheme first, I would suggest that the output also be automatically changed to it (but not the reverse way!!); the user would anyway be seeing it, as he is selecting the options & change the output option next, if he wants a different one.
I'm for simple to be the default input, @funderburkjim against.

> I'm using the mobile friendly database.
The site is not mobile friendly at all.

**Comment by funderburkjim** [comment]
@Jazirae   The 'simple' search mentioned above is available as shown below:

![image](https://user-images.githubusercontent.com/6393033/109401101-b653fc00-791a-11eb-9ef5-127aff136206.png)

This display smooths out many of the variations in spelling of
Sanskrit words.     For example, you can get
your entry with various approximate spellings, such as:

![image](https://user-images.githubusercontent.com/6393033/109401219-60cc1f00-791b-11eb-8598-91f3510122c1.png)

You might find it helpful.

**Comment by drdhaval2785** [comment]
Just to share my experience as user, 
I type in SLP1 and prefer output in Devanagari. 

There may be some people like me. So, please do not make input and output the same, as suggested somewhere.

**Comment by Andhrabharati** [comment]
@drdhaval2785 
it is not a "fixed" config that I suggested, but just a default config; and the option to have different input/output schemes should always be there for users like you and me.

**Comment by Andhrabharati** [comment]
I am refering to the main 'advanced' search page not to the 'simple' search page which "tries" to "help" the user (many times with too much extra suggestions).

**Comment by gasyoun** [comment]
> (many times with too much extra suggestions).

Make a new issue and list samples of `too much extra suggestions`, please.

**Comment by Jazirae** [comment]
Thank you!

I've never seen this screen before.  You mean I can make it show accents?!!

**Comment by Andhrabharati** [comment]
Probably this issue could be closed, as the it is identified as "not to worry about".

**Comment by drdhaval2785** [comment]
The user's concern is addressed. He needs to choose proper output transliteration scheme. 

The suggestion of Andhrabharati to suggest output transliteration to be the same as input transliteration by default needs to be deliberated upon.

**Comment by Andhrabharati** [comment]
It was suggested just for the sake of "giving no scope" for issues such as the above, not a fixed/permanent setting though- if one looks at my suggestion above clearly.

> Even if one changes the input scheme first, I would suggest that the output also be automatically changed to it (but not the reverse way!!); the user would anyway be seeing it, as he is selecting the options & change the output option next, if he wants a different one.

As per the further discussions that went on, I think it needs NO MORE deliberations.

**Comment by drdhaval2785** [comment]
Fine. Closeable.

**Comment by Jazirae** [comment]
Yes
