### ISSUE TITLE
MW supplement fresh look, part 7: missed 'or'/'and' entries

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#105]
This issue devoted to the problem as mentioned in [revdoc/todo](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/todo.md).

We start with the observation of the todo file:
* 296 such entries "¦ (or \<s>", which need to be split as sep. entries and marked as OR group.
* 596 entries "¦ or \<s>", which need to be split as sep. entries and marked as OR group.
* 18 entries "¦ (and \<s>", which need to be split as sep. entries and marked as AND group.
* 140 entries "¦ and \<s>", which need to be split as sep. entries and marked as AND group.

Some of these involve annex entries, most do not.

The problem was noticed in the context of:
```
<s>aṅgāraka-yantra</s>¦ (or <s>bhauma</s>-<s>y</s>°), 
<lex>n.</lex> a kind of auspicious diagram, <ls>Inscr.</ls><info n="sup"/>
<info lex="n"/>
```
In this example, there is an indication of an alternate word 'aṅgāraka-bhauma', but
* There is currently no mw entry for aṅgāraka-bhauma, 
   * so such an entry needs to be created
* Entries for both  aṅgāraka-yantra and aṅgāraka-bhauma need to have an `<info or="..."/>` clause.

**Comment by Andhrabharati** [comment]
would you be taking this up independently  @funderburkjim?

I missed listing another type, comma separated ones (which can be taken as part of OR type); there are quite many of them too.

**Comment by funderburkjim** [comment]
Yes, I've gotten started on it.
Do you have a regex selector for 'comma separated ones' ?

**Comment by Andhrabharati** [comment]
no, but guess it can be done.

will see the data once (to frame the regex) after I am done with comp. word headers.

hope I would be able to give it to you by the time you finish the above groupings (iff you don't make the regex yourself).

**Comment by Andhrabharati** [comment]
just a lighter vein remark-

why did you choose to have "supplement" in the title (of the issue), when you are saying that not many of these are from annexure pages?

**Comment by gasyoun** [comment]
> why did you choose to have "supplement" in the title (of the issue), when you are saying that not many of these are from annexure pages?

Love the level of accuracy.

**Comment by funderburkjim** [comment]
## First refinement of the problem set

In some cases included in the enumeration above, no correction is required.

For example,
```
<s>adhi-māṃsa</s> ¦ (or <s>adhi-māṃsaka</s>) <lex>m.</lex> 
proud flesh or cancer (especially in the eyes or the back part of the gums). 
<info or="4316,aDimAMsa;4317,aDimAMsaka"/><info lex="m"/>
```

In the process of further refining the cases where action IS required,  several miscellaneous
problems were corrected.  For example,
* spelling or other errors in an `<info or="..."/>` item, such as spelling error 'avanIsvara' in
  ```<s>avanī<srs/>śvara</s> ¦ <lex>m.</lex> ‘lord of the earth’, a king, 
     <ls>VarBṛS.</ls>
     <info or="17582,avanISa;17583,avanIsvara"/><info lex="m"/>
   ```
* mis-labeling of 'or' or 'and', For example: 'or=' should be 'and=' in:
   ```<s>ghagh</s> <hom>a</hom> ¦ (and <s>ghaggh</s>) <ab>cl.</ab> 1. <ab>P.</ab> 
      <s>°gghati</s> (and <s>°ghati</s>), to laugh, <ls>v, 53</ls> 
      (<ab>cf.</ab> √ <s>kakh</s>.)
      <info or="69217,GagG;69217.1,GaG"/><info verb="root" cp="1P"/>
   ```

After such consistency corrections (about 100) were made,  a more precise count can be
made of the cases that remain

|category|regex|count|TODO|OK|
|----|----|----|----|----|
|por |¦ (or \<s> | 296 | 150 | 146|
|or |¦ (or \<s> | 596 | 133 | 463|
|pand |¦ (and \<s> | 18 | 11 | 7|
|and |¦ and \<s> | 140 | 61 | 79|

In this table, 'OK' means, for example that there is an `<info or="..."/>` in an entry along with
 `¦ (or <s>`.

Thus, according to this approach, there are 355 ( = (+ 150 133 11 61)) cases where an entry
* appears to be in an 'or-list' or 'and-list' based on the regex, 
* but for which there is no corresponding `<info or="..."/> or `<info and="..."/>` metadata

The next step is to examine these 355 cases more closely.

**Comment by gasyoun** [comment]
> The next step is to examine these 355 cases more closely.

Wish this task does not grow any bigger anytime soon.

**Comment by Andhrabharati** [comment]
> In this example, there is an indication of an alternate word 'aṅgāraka-bhauma', but
> 
>     * There is currently no mw entry for aṅgāraka-bhauma,
>       
>       * so such an entry needs to be created
> 
>     * Entries for both  aṅgāraka-yantra and aṅgāraka-bhauma need to have an `<info or="..."/>` clause.

There is nothing like **aṅgāraka-bhauma**!!
```
> <s>aṅgāraka-yantra</s>¦ (or <s>bhauma</s>-<s>y</s>°), 
> <lex>n.</lex> a kind of auspicious diagram, <ls>Inscr.</ls><info n="sup"/>
> <info lex="n"/>
```

It is `<s>bhauma-y°</s>` that is to be added here. [**aṅgāraka** & **bhauma** are synonymous, indicating Kuja's (Mars's).]

**Comment by Andhrabharati** [comment]
> In some cases included in the enumeration above, no correction is required.
> 
> For example,
> 
> ```
> <s>adhi-māṃsa</s> ¦ (or <s>adhi-māṃsaka</s>) <lex>m.</lex> 
> proud flesh or cancer (especially in the eyes or the back part of the gums). 
> <info or="4316,aDimAMsa;4317,aDimAMsaka"/><info lex="m"/>
> ```

I would've opted to make all the entries uniformly constructed; either all of them to be just as ind. listed items, or all of them to be with the grouped items kept in the "body"- like **(or `<s>adhi-māṃsaka</s>`)**.

```
> <L>4316<pc>21,3<k1>adhimāṃsa<k2>adhi-māṃsa<e>1	<s>adhi-māṃsa</s> ¦ (or <s>adhi-māṃsaka</s>) <lex>m.</lex> proud flesh or cancer (especially in the eyes or the back part of the gums). <info or="4316,aDimAMsa;4317,aDimAMsaka"/><info lex="m"/>	<LEND>
> <L>4317<pc>21,3<k1>adhimāṃsaka<k2>adhi-māṃsaka<e>2	<s>adhi-māṃsaka</s> ¦ (or <s>adhi-māṃsa</s>) <lex>m.</lex> proud flesh or cancer (especially in the eyes or the back part of the gums). <info or="4316,aDimAMsa;4317,aDimAMsaka"/><info lex="m"/>	<LEND>
> 
```

It is not just having the group tagging added but to have the body portion also to be **"identical"** for these Group element entries, as Jim himself has mentioned earlier.


Of course, **I do understand that individual's thinking and approach would be different.**

**So leave it to Jim's discretion.**

**Comment by Andhrabharati** [comment]
>     * spelling or other errors in an `<info or="..."/>` item, such as spelling error 'avanIsvara' in
>       ```
>          <ls>VarBṛS.</ls>
>          <info or="17582,avanISa;17583,avanIsvara"/><info lex="m"/>
>       ```

I would've suggested removing all those slp1 words in the group tagging, just the L-numbers would be sufficient here (as it is mainly intended for "machine identification"); I recall "the principle of necessary and sufficient conditions" learnt in school-days in all such occasions.

**Sorry for poking my nose into every nook and corner!**

Again as I mentioned above, it is just another case of individual's thinking and approach.

**Comment by funderburkjim** [comment]
> bhaumayantra

I've made such an entry in current work. 

> body portion identical

Where new records were required, I have used this principle. For example:
```
<L>1672.1<pc>1309,2<k1>aṅgārakayantra<k2>aṅgāraka-yantra<e>3
<s>aṅgāraka-yantra</s> ¦ (or <s>bhauma-y°</s>), <lex>n.</lex> a kind of auspicious diagram, <ls>Inscr.</ls><info n="sup"/><info lex="n"/><info or="1672.1,aNgArakayantra;1672.2,BOmayantra"/>
<LEND>
<L>1672.2<pc>1309,2<k1>bhaumayantra<k2>bhauma-yantra<e>3
<s>aṅgāraka-yantra</s> ¦ (or <s>bhauma-y°</s>), <lex>n.</lex> a kind of auspicious diagram, <ls>Inscr.</ls><info n="sup"/><info lex="n"/><info or="1672.1,aNgArakayantra;1672.2,BOmayantra"/>
<LEND>
```
However, for existing 'or/and' groups, I have not retro-changed.

> removing all those slp1 words in the group tagging

Agree that this could be done -- the L-numbers are sufficient.
However, I've kept the slp1 words at this revision.

My analysis of this problem has addressed all the '355' cases.  
Plan to submit results soon.

**Comment by funderburkjim** [comment]
Changes now in new [commit of mw_iast.txt](https://github.com/sanskrit-lexicon/MWS/commit/e2d695b3ea92455331661244d008b59dac6751c3).

The changes made to prior commit are in two files:
* [changes_3.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/changes_3.txt)
* [changes_4.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/changes_4.txt)

**Comment by funderburkjim** [comment]
## 'singleton' cases

There are numerous instances similar to `<s>X</s> or <s>Y</s>`  where X and Y
differ only by accents or similar.

[orand_singletons.txt](https://github.com/sanskrit-lexicon/MWS/files/6126899/orand_singletons.txt)

For example:
```
<s>an-avadānī́ya</s> ¦ (or <s>°nīyá</s>), <lex>mfn.</lex> not fit for distribution, <ls>MaitrS.</ls>; <ls>TBr.</ls><info n="sup"/><info lex="m:f:n"/><info or="5295.1,avadAnIya"/>
```

In either form, the underlying 'key1' ('k1') is the same, namely `anavadānīya`.

I've chosen to mark these with a single 'or' group:  `<info or="5295.1,avadAnIya"/>`.
(or a single 'and' group).

With this markup, it would be possible to filter for these.

There are a few in the file mentioned as 'odd'.  For example
```
<s>bhadrā<srs/>śrama</s> <hom>a</hom> ¦ (or <s>°drā<srs/>śr°</s>?) <lex>m.</lex> <ab>N.</ab> of a hermitage, <ls>SkandaP.</ls><info lex="m"/><info or="148500,BadrASrama"/>
```
Here the distinction is more subtle than our current markup can indicate.

![image](https://user-images.githubusercontent.com/6393033/110878410-22364d00-82a9-11eb-94d7-d7d56c5c95b2.png)

Notice the minor typographical difference in the two circumflex diacritic marks.

In this particular case,  the distinction is explained by PWG entry:
`bhadra + āśrama or bhadrā + āśrama`

**Comment by gasyoun** [comment]
> There is nothing like aṅgāraka-bhauma

Wonder how many more such cases are out there

**Comment by Andhrabharati** [comment]
comes out when I post the "Entry words" point!

(we already talked on this in the beginning itself-- about having more entries and correct comp. words or samAsa words with AB!!)

**Comment by gasyoun** [comment]
> I recall "the principle of necessary and sufficient conditions" learnt in school-days in all such occasions.

And Occam's razor.

> having more entries and correct comp. words or samAsa words with AB

Yes, we want all the hidden data to come out.

**Comment by funderburkjim** [comment]
Before I proceed with the 'or/and' suggestion of [your comment above](https://github.com/sanskrit-lexicon/MWS/issues/105#issuecomment-793426577),
consider this first instance:

current 
```
<L>21<pc>1,1<k1>aMSakalpanA<k2>a/MSa—kalpanA<e>3
<s>a/MSa—kalpanA</s> ¦ <lex>f.</lex> allotment of a portion.<info or="21,aMSakalpanA;22,aMSaprakalpanA;23,aMSapradAna"/><info lex="f"/>
<LEND>
<L>22<pc>1,1<k1>aMSaprakalpanA<k2>a/MSa—prakalpanA<e>3
<s>a/MSa—prakalpanA</s> ¦ <lex>f.</lex> allotment of a portion.<info or="21,aMSakalpanA;22,aMSaprakalpanA;23,aMSapradAna"/><info lex="f"/>
<LEND>
<L>23<pc>1,1<k1>aMSapradAna<k2>a/MSa—pradAna<e>3
<s>a/MSa—pradAna</s> ¦ <lex>n.</lex> allotment of a portion.<info or="21,aMSakalpanA;22,aMSaprakalpanA;23,aMSapradAna"/><info lex="n"/>
<LEND>
```

suggested revision
```

<L>21<pc>1,1<k1>aMSakalpanA<k2>a/MSa—kalpanA<e>3
<s>a/MSa—kalpanA</s>, <lex>f.</lex> or <s>a/MSa—prakalpanA</s>, <lex>f.</lex> or <s>a/MSa—pradAna</s>, <lex>n.</lex> allotment of a portion.<info or="21,aMSakalpanA;22,aMSaprakalpanA;23,aMSapradAna"/><info lex="f"/>
<LEND>
<L>22<pc>1,1<k1>aMSaprakalpanA<k2>a/MSa—prakalpanA<e>3
<s>a/MSa—kalpanA</s>, <lex>f.</lex> or <s>a/MSa—prakalpanA</s>, <lex>f.</lex> or <s>a/MSa—pradAna</s>, <lex>n.</lex> allotment of a portion.<info or="21,aMSakalpanA;22,aMSaprakalpanA;23,aMSapradAna"/><info lex="f"/>
<LEND>
<L>23<pc>1,1<k1>aMSapradAna<k2>a/MSa—pradAna<e>3
<s>a/MSa—kalpanA</s>, <lex>f.</lex> or <s>a/MSa—prakalpanA</s>, <lex>f.</lex> or <s>a/MSa—pradAna</s>, <lex>n.</lex> allotment of a portion.<info or="21,aMSakalpanA;22,aMSaprakalpanA;23,aMSapradAna"/><info lex="n"/>
<LEND>
```

@Andhrabharati  Is this the kind of change you are suggesting?

**Comment by funderburkjim** [comment]
Such a change would have the virtue that whenever a user looked up any one of the
alternates,  he would see all the words that MW considered as alternates.

**Comment by funderburkjim** [comment]
In my suggested revision, I removed the broken bar ¦.  
¦ plays no role in the display. 

I also put the full word spellings.

**Comment by Andhrabharati** [comment]
Yes, that's one variety that I had in mind in saying-
>> all of them to be with the grouped items kept in the "body"

Another variety is just deleting the 'or' or 'and' portions after the  ¦, which is a simpler way, which I meant by saying-
>> all of them to be just as ind. listed items

**Comment by funderburkjim** [comment]
Have begun the 'normalization' as suggested above [comment](https://github.com/sanskrit-lexicon/MWS/issues/105#issuecomment-804263975).

Work so far in [latest commit of mw_iast.txt](https://github.com/sanskrit-lexicon/MWS/commit/890fbc28e56e6b6df15fa03770103cca2dd94d25).

@Andhrabharati :  please take a look and comment on sufficiency of this approach.

There are about 3000 `<info or/and="..."/>` groups that remain to be examined.
I'd like to have your observations before proceeding further.

**Comment by Andhrabharati** [comment]
Excellent work, this is.

Now it is just what the book has in print.

This should've been done in the initial stage itself, avoiding much of the rework now.

But as the saying goes, "better late than never".

I really appreciate you, in taking my comments in true spirit. (More often than not, my comments are rude, as a critic.)

**Comment by Andhrabharati** [comment]
For entries like L-306 akusIda, where the alt. forms just differ in accent, probably making "with accents" as the default option is suggestible.

**Comment by gasyoun** [comment]
> For entries like L-306 akusIda, where the alt. forms just differ in accent, probably making "with accents" as the default display option is suggestible.

You speak about the UI or the order of elements?

**Comment by Andhrabharati** [comment]
making "with accents" as the default display option -- where does this apply?

**Comment by gasyoun** [comment]
> This should've been done in the initial stage itself, avoiding much of the rework now.

After 1997 and pre-MW-2021 it was `<s>agny-ādheya</s>` and `<s>agny-ādhāna</s>`, so not exactly what was in the book, but what was meant. Now, again, it's `<s>agny-ādhāna</s>` and `<s>-ādhéya</s>` - true to the print. But true to print is only one aspect and one I really do not care that much, as long as the search becomes hard. In `<L>1176<pc>6,1<k1>agnyādheya<k2>agny-ādheya<e>3` I do not see how the full form of the `<s>agny-ādhāna</s>` is still to be found and where they are equalled in the meta markup of alternate headwords.

```
<s>agny-ādhāna—havis</s> ¦ <lex>n.</lex> an oblation at the <ab n="Agnyādheya" slp1="agnyADeya">A°</ab>, <ls>ŚBr.</ls><info lex="n"/>
<LEND>
<L>1176<pc>6,1<k1>agnyādheya<k2>agny-ādheya<e>3
<s>agny-ādheya</s> ¦ (or <s>agny-ādhāna</s>) <lex>n.</lex> ([<ls>AV.</ls>; <ls>Mn.</ls> &c.]) placing the fire on the sacrificial fire-place<info or="1175,agnyADAna;1176,agnyADeya"/><info lex="n"/>
<s>agny-ādhāna</s> ¦ [<ls>KauṣBr.</ls>] or <s>-ādhéya</s> [<ls>AV.</ls>; <ls>Mn.</ls> &c.], <lex>n.</lex> placing the fire on the sacrificial fire-place<info or="1175,agnyADAna;1176,agnyADeya"/><info lex="n"/>
<LEND>
<L>1176.1<pc>6,1<k1>agnyādheya<k2>agny-ādheya<e>3A
¦ the ceremony of preparing the three sacred fires <s1 slp1="AhavanIya">Āhavanīya</s1> &c.<info lex="inh"/>
```

**Comment by funderburkjim** [comment]
> how the full form of the <s>agny-ādhāna</s> is still to be found 

If you look at L=1175 and L=1176 in mw_iast, the text is the same:

```
<L>1175<pc>6,1<k1>agnyādhāna<k2>agny-ādhāna<e>3
<s>agny-ādhāna</s> ¦ [<ls>KauṣBr.</ls>] or <s>-ādhéya</s> [<ls>AV.</ls>; <ls>Mn.</ls> &c.], <lex>n.</lex> placing the fire on the sacrificial fire-place<info or="1175,agnyADAna;1176,agnyADeya"/><info lex="n"/>

and the same for L=1176
<L>1176<pc>6,1<k1>agnyādheya<k2>agny-ādheya<e>3
<s>agny-ādhāna</s> ¦ [<ls>KauṣBr.</ls>] or <s>-ādhéya</s> [<ls>AV.</ls>; <ls>Mn.</ls> &c.], <lex>n.</lex> placing the fire on the sacrificial fire-place<info or="1175,agnyADAna;1176,agnyADeya"/><info lex="n"/>
<LEND>
```

Maybe your point is that in this text, we see `<s>agny-ādhāna</s>`  but only `<s>-ādhéya</s>` .

Let's call this option A.

Another way that these could be written is to replace `<s>-ādhéya</s>`  with
`<s>agny-ādhéya</s>`.  Let's call this 'option B'.

```
<s>agny-ādhāna</s> ¦ [<ls>KauṣBr.</ls>] or <s>agny-ādhéya</s> [<ls>AV.</ls>; <ls>Mn.</ls> &c.], <lex>n.</lex> placing the fire on the sacrificial fire-place<info or="1175,agnyADAna;1176,agnyADeya"/><info lex="n"/>
```

option A has the full form only for the First alternate (e.g. `<s>agny-ādhāna</s>`); the
  subsequent alternates are abbreviated.

option B has the full form for all the alternates.

I also have not been certain on whether to use option A or option B.  In the changes
shown in the mw_iast commit you just examined, I tended to use option A.

But in the small amount of work I've done on the remaining 3000, I've tended to 
use option B (since it requires slightly less work to paste the full form of the alternates).

My tendency is to go with option B (full form for all alternates).

Your opinions?


1) Do you think it matters whether option A or option B is used?
2) If so

**Comment by gasyoun** [comment]
> Do you think it matters whether option A or option B is used?

I'm fully for B. It matters, because it's a headword issue. How can we find a word, if the `subsequent alternates are abbreviated`?

**Comment by funderburkjim** [comment]
Will use option B.

Note that the current search methods for headwords use the 'metaline' k1 field.
So both options A and B are equally headword searchable.

**Comment by gasyoun** [comment]
> So both options A and B are equally headword searchable.

Oh, ok. And both are presented in the `sanhw` kind of files?

**Comment by funderburkjim** [comment]
> And both are presented in the sanhw kind of files?

Yes.

The sanhw files are based only on headwords (key1,key2).  They are not affected by
the current reformatting of the text for the or/and headwords.

**Comment by funderburkjim** [comment]
The work to further *normalize* the text of  or/and records has run its course.
Here is the sequence of events, just for the record.

## Start with csl-orig/v02/mw/mw.txt at commit 7ee66c1b8
This version of mw.txt is retrieveable from git cli; assume current directory in
local installation is csl-orig/v02/mw/.
`git show 7ee66c1b8:./mw.txt > tempshow_mw_7ee66c1b8.txt`

## apply changes_1.txt
[changes_1.txt](https://github.com/sanskrit-lexicon/MWS/files/6253283/changes_1.txt) contains about 850 changes that
normalize text primarily in verbs that mention multiple forms, such as
```
;10656 old <s>ati-√ gam</s> ¦ or <s>ati-√ gA</s>, to pass by or over <pb n="13,3"/>;
;10656 new <s>ati-√ gam</s> ¦ or <s>ati-√ gA</s>, to pass by or over <pb n="13,3"/>;
;
10663 old <s>ati-√ gA</s> ¦ or <s>ati-√ gam</s>, to pass by or over <pb n="13,3"/>;
10663 new <s>ati-√ gam</s> ¦ or <s>ati-√ gA</s>, to pass by or over <pb n="13,3"/>;
```
After the change, the entries for 'atigam' and 'atigA' start the same.

A few intermediate corrections were made in relation to preparing the 
next set of changes described next.

## Apply changes_2a.txt

[changes_2a.txt](https://github.com/sanskrit-lexicon/MWS/files/6253289/changes_2a.txt) changes all the entries previously marked with `<info or="..."/>` or `<info and="..."/>`.

These are changed along the lines of *option B* mentioned in a previous comment above.
About 6800 lines of mw.txt are changed.

**Comment by funderburkjim** [comment]
## Installation
After the 2 series of changes were applied, we have a new slp1 version mw02.txt.
This is converted to iast, and moved to [mw_iast.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/mw_iast.txt).  
Unfortunately, the [commit diff](https://github.com/sanskrit-lexicon/MWS/commit/91bd8ac3f9289a5e37efd6b3538e1124cb68e8f8) is too large to see in the Github UI.

**Comment by funderburkjim** [comment]
The changes are also installed in the production version of mw, in csl-orig/v02/mw/mw.txt.

These changes are visible in the displays for or/and entries.  For a brief example,
headword JIrikA (slp1):

Scan:
![image](https://user-images.githubusercontent.com/6393033/113490252-e0a75500-9496-11eb-8d36-d73badcc54b0.png)

Display *before* change:
![image](https://user-images.githubusercontent.com/6393033/113490269-f87ed900-9496-11eb-8093-e532618704a3.png)

Display *after* change:
![image](https://user-images.githubusercontent.com/6393033/113490285-12202080-9497-11eb-904d-0be307700bca.png)

Thus, the digitization text after the change is quite close to the printed text.

**Comment by funderburkjim** [comment]
This is as far as I was planning to go in this 'fresh look' revision at this time.

**Comment by gasyoun** [comment]
> 'fresh look' revision at this time.

Good to hear it is over, it was a huge one indeed.

**Comment by Andhrabharati** [comment]
> The changes are also installed in the production version of mw, in csl-orig/v02/mw/mw.txt.
> 
> These changes are visible in the displays for or/and entries. For a brief example,
> headword JIrikA (slp1):
> 
> Scan:
> ![image](https://user-images.githubusercontent.com/6393033/113490252-e0a75500-9496-11eb-8d36-d73badcc54b0.png)
> 
> Display _before_ change:
> ![image](https://user-images.githubusercontent.com/6393033/113490269-f87ed900-9496-11eb-8093-e532618704a3.png)
> 
> Display _after_ change:
> ![image](https://user-images.githubusercontent.com/6393033/113490285-12202080-9497-11eb-904d-0be307700bca.png)
> 
> Thus, the digitization text after the change is quite close to the printed text.

I was waiting to see this "for ages".

**Comment by Andhrabharati** [comment]
Similar work could take place for other  dictionaries as well.

**Comment by Andhrabharati** [comment]
Now I can start posting the comp. words (with headers) from the annexure pages.

I was waiting for the grouping task by @funderburkjim to be over, as some of the entries are of that type, to make use of the "revised" latest text.

**Comment by gasyoun** [comment]
> Similar work could take place for other dictionaries as well.

No, not now. Such work is not of priority, as every other work stops after it.

> Now I can start posting the comp. words (with headers) from the annexure pages.

Right.
