### ISSUE TITLE
Missed gender endings 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#106]
@Andhrabharati has been interested in the missed gender endings in the text of
current digitization mw.txt.  Comments pertaining to this question have appeared
in several issues, such as
https://github.com/sanskrit-lexicon/MWS/issues/104#issuecomment-804021776
and my comments also in #104.

Let's devote this issue to further comments on this topic.

**Comment by Andhrabharati** [comment]
It is not a fascination, but just an intent to see the MW99 as a "complete" (& close to) digitization of the print version.

All such gender endings are in place in the later cologne digitisations that took place, including MW72.

**Comment by Andhrabharati** [comment]
I will be "handling" this in my current full review, and so this issue does not need any more discussion.
