### ISSUE TITLE
IAST in literary sources (was Divyâv. xxxv, 231.)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#107]
`(H1)  [Printed book page 406,2]  chiṭi   only ifc. with kāñcika- = kāñcika, Divyâv. xxxv, 231.   [ID=75904]`

Should not `â` be dead by now if it is for now sandhi in MW? Or left in abbreviations, @funderburkjim ?

![dsfdsfffsdfsd](https://user-images.githubusercontent.com/80761/114286138-d2dc6b80-9a64-11eb-93b2-ab27a6906742.png)

**Comment by funderburkjim** [comment]
It is left only in literary source abbreviations.

Do we need to change?

**Comment by gasyoun** [comment]
> It is left only in literary source abbreviations.

Oh, ok.

> Do we need to change?
I see no reason in leaving. Or add the IAST searchable one to tags?

**Comment by drdhaval2785** [comment]
I also request to convert literary sources to IAST.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Besides this â to ā change, I suggest replacing the ṉ with ṃ in the all places (incl. the ls entries), as done elsewhere in the text.

There are 812 ṉ[śsṣh] cases, but also 426 ṃ[śsṣh]; **interestingly in few cases, the same word has ṉ at some places and ṃ at some other places!!**

I also see some words with ṡ (esp. the Zend, or Old Persian), which should better be with ś, just as in Sanskrit; these two are considered "twin languages" by the linguists.

**Comment by Andhrabharati** [comment]
In fact, there were both types of Divyâv. &  Divyāv. in the text till very recent times, till @funderburkjim had changed them all to Divyâv. in October.

https://github.com/sanskrit-lexicon/MWS/issues/113#issuecomment-933031050

**Comment by Andhrabharati** [comment]
Posting the below point for reconsideration (I had posted this already earlier elsewhere)-

> There are ~350 ł occurences; these could be changed to ḷ as per the IAST notation for ळ्.
> The same ḷ is used in Telugu, Kannada and Marathi transliterations, which use the ळ letter predominantly than any other Indian languages. 
> And the same has been employed by MW in all his works, incl. this dictionary!!
> (I do not see any strong reason for selecting this ł character.)

**Comment by Andhrabharati** [comment]
> It is left only in literary source abbreviations.
> 
> Do we need to change?

The caret marking is seen under s1 tag & slp1 tag as well, not just under the ls tagging.

@funderburkjim is again requested to change all those to macron marking, and also probably remove the <srs1/> tag as well under the <s> entries (both in HW portion and in the body portion) which do not serve any 'real' purpose now.

In fact, I see many (savrṇa-dīrgha-)sandhi places without this <srs1/> marking; so, either all places should be with the tag or all without the tag, in the name of ūniformity and consistency.

**Comment by funderburkjim** [comment]
@gasyoun - Maybe you can close this issue now, since https://github.com/sanskrit-lexicon/MWS/issues/137#issuecomment-1236177210 probably provides solution.
