### ISSUE TITLE
Too Much White-space

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#109]
I understand that we insert single whitespace in digital dictionary, because if we look at it with devanagari, it would pile up. But what need to have 2 at once in one place, @funderburkjim ?

`to be a rival or a match for, Kāvyâd. ii, 61  : `

![fdfdfdfdfds](https://user-images.githubusercontent.com/80761/115104053-c1acc680-9f5e-11eb-84fa-d3d7fed9e863.png)

`dveṣṭā, Siddh. ; Pāṇ. 7-2, 10; `

No space after `10`, but space after `Siddh.` - inconsistent.

**Comment by gasyoun** [comment]
Even more in PWG

![idd](https://user-images.githubusercontent.com/80761/115136662-df932d80-a029-11eb-8c4d-692b512e05bd.png)

**Comment by Andhrabharati** [comment]
@gasyoun 

**This spacing before the colon in MW indicates a 'section-break' (a spl. type of punctuation)**, as such it should be retained.

In my current full review, I have "corrected" all other places in the file which were otherwise; and I guess this issue is closable now.
