### ISSUE TITLE
List of 190 Abbreviations in Dictionary

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#11]
http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/mwaux/mwab/mwab_input.txt is not linked from documentation page, nor included in .xml download, should not it be? I see http://www.sanskrit-lexicon.uni-koeln.de/monier/abbr.html has not changed since 2008, same amount. Can't we have it IAST by now or SLP1? A1 should be part of the history, I guess. Yes, it's ASCII, but otherwise it's only additional issues.

<code>A1.   <id>A1.</id> <disp>Atmane-pada</disp>
A1di-p. <id>A1di-p.</id> <disp><s>Adi-parvan</s> of the <s>mahA-BArata</s></disp>
Aeol.   <id>Aeol.</id> <disp>AEolic</disp>
Angl.Sax.   <id>Angl.Sax.</id> <disp>Anglo-Saxon</disp>
Aor.    <id>Aor.</id> <disp>Aorist</disp>
Arab.   <id>Arab.</id> <disp>Arabic</disp>
Arm.    <id>Arm.</id> <disp>Armorican or the language of Brittany</disp>
Armen.  <id>Armen.</id> <disp>Armenian</disp>
Armor.  <id>Armor.</id> <disp>Armorican</disp>
B.  <id>B.</id> <disp>Bombay edition</disp>
Boh.    <id>Boh.</id> <disp>Bohemian</disp>
Bohem.  <id>Bohem.</id> <disp>Bohemian</disp>
Bomb.   <id>Bomb.</id> <disp>Bombay edition</disp>
Br. <id>Br.</id> <disp>Breton</disp>
Bret.   <id>Bret.</id> <disp>Breton</disp>
C.  <id>C.</id> <disp>Calcutta edition</disp>
Calc.   <id>Calc.</id> <disp>Calcutta edition</disp>
Cat.    <id>Cat.</id> <disp>catalogue or catalogues</disp>
Caus.   <id>Caus.</id> <disp>Causal</disp>
Class.  <id>Class.</id> <disp>Classical</disp>
Comm.   <id>Comm.</id> <disp>commentator or commentary</disp>
Cond.   <id>Cond.</id> <disp>Conditional</disp>
Desid.  <id>Desid.</id> <disp>Desiderative</disp>
Eng.    <id>Eng.</id> <disp>English</disp>
Ep. <id>Ep.</id> <disp>Epic</disp>
Fut.    <id>Fut.</id> <disp>future</disp>
Gael.   <id>Gael.</id> <disp>Gaelic</disp>
Germ.   <id>Germ.</id> <disp>German</disp>
Gk. <id>Gk.</id> <disp>Greek</disp>
Goth.   <id>Goth.</id> <disp>Gothic</disp>
Gr. <id>Gr.</id> <disp>grammar</disp>
Hib.    <id>Hib.</id> <disp>Hibernian or Irish</disp>
Hind.   <id>Hind.</id> <disp>Hindi</disp>
Icel.   <id>Icel.</id> <disp>Icelandic</disp>
Impv.   <id>Impv.</id> <disp>imperative</disp>
Inscr.  <id>Inscr.</id> <disp>Inscriptions</disp>
Intens. <id>Intens.</id> <disp>Intensive</disp>
Introd. <id>Introd.</id> <disp>Introduction</disp>
Ion.    <id>Ion.</id> <disp>Ionic</disp>
L.  <id>L.</id> <disp>lexicographers (i.e. a word or meaning which although give in native lexicons, has not yet been met with in any published text)</disp>
Lat.    <id>Lat.</id> <disp>Latin</disp>
Lett.   <id>Lett.</id> <disp>Lettish</disp>
Lith.   <id>Lith.</id> <disp>Lithuanian</disp>
MS. <id>MS.</id> <disp>manuscript</disp>
MSS.    <id>MSS.</id> <disp>manuscripts</disp>
Mod.    <id>Mod.</id> <disp>modern</disp>
N.  <id>N.</id> <disp>Name (also title or epithet)</disp>
Nom.    <id>Nom.</id> <disp>Nominal verb</disp>
Osset.  <id>Osset.</id> <disp>Ossetic</disp>
P.  <id>P.</id> <disp><s>parasmE-pada</s></disp>
Pass.   <id>Pass.</id> <disp>Passive voice</disp>
Pers.   <id>Pers.</id> <disp>Persian</disp>
Pot.    <id>Pot.</id> <disp>Potential</disp>
Pr. <id>Pr.</id> <disp>proper</disp>
Pra1k.  <id>Pra1k.</id> <disp>Prakrit</disp>
Pra1kr. <id>Pra1kr.</id> <disp>Prakrit</disp>
Pruss.  <id>Pruss.</id> <disp>Prussian</disp>
RV. <id>RV.</id> <disp><s>fg-veda</s></disp>
Reflex. <id>Reflex.</id> <disp>Reflexive or used reflexively</disp>
Russ.   <id>Russ.</id> <disp>Russian</disp>
Sax.    <id>Sax.</id> <disp>Saxon</disp>
Sch.    <id>Sch.</id> <disp>Scholiast or Commentator</disp>
Schol.  <id>Schol.</id> <disp>Scholiast or Commentator</disp>
Scot.   <id>Scot.</id> <disp>Scotch or Highland-Scotch</disp>
Slav.   <id>Slav.</id> <disp>Slavonic or Slavonian</disp>
Subj.   <id>Subj.</id> <disp>subjunctive</disp>
Va1rt.  <id>Va1rt.</id> <disp><s>vArttika</s></disp>
Va1rtt. <id>Va1rtt.</id> <disp><s>vArttika</s></disp>
Ved.    <id>Ved.</id> <disp>Vedic or Veda</disp>
Zd. <id>Zd.</id> <disp>Zend</disp>
abl.    <id>abl.</id> <disp>ablative</disp>
above   <id>above</id> <disp>a reference to some preceeding word (not necessarily in the same page)</disp>
acc.    <id>acc.</id> <disp>accusative</disp>
accord. <id>accord.</id> <disp>according to</disp>
add.    <id>add.</id> <disp>additions</disp>
adj.    <id>adj.</id> <disp>adjective (cf. mfn.)</disp>
adv.    <id>adv.</id> <disp>adverb</disp>
alg.    <id>alg.</id> <disp>algebra</disp>
anat.   <id>anat.</id> <disp>anatomy</disp>
anom.   <id>anom.</id> <disp>anomalous</disp>
aor.    <id>aor.</id> <disp>Aorist</disp>
arithm. <id>arithm.</id> <disp>arithmetic</disp>
astrol. <id>astrol.</id> <disp>astrology</disp>
astron. <id>astron.</id> <disp>astronomy</disp>
c.  <id>c.</id> <disp>case</disp>
cf. <id>cf.</id> <disp>confer, compare</disp>
ch. <id>ch.</id> <disp>chapter</disp>
cl. <id>cl.</id> <disp>class</disp>
col.    <id>col.</id> <disp>column</disp>
cols.   <id>cols.</id> <disp>columns</disp>
comp.   <id>comp.</id> <disp>compound</disp>
compar. <id>compar.</id> <disp>Comparative degree</disp>
concl.  <id>concl.</id> <disp>conclusion</disp>
conj.   <id>conj.</id> <disp>conjectural</disp>
cons.   <id>cons.</id> <disp>consonant</disp>
dat.    <id>dat.</id> <disp>dative case</disp>
defect. <id>defect.</id> <disp>defective</disp>
dimin.  <id>dimin.</id> <disp>diminutive</disp>
dram.   <id>dram.</id> <disp>dramatic language</disp>
du. <id>du.</id> <disp>dual number</disp>
e.g.    <id>e.g.</id> <disp>exempli gratia, 'for example'</disp>
ed. <id>ed.</id> <disp>edition</disp>
ep. <id>ep.</id> <disp>Epic</disp>
esp.    <id>esp.</id> <disp>especially</disp>
etym.   <id>etym.</id> <disp>etymology</disp>
f.  <id>f.</id> <disp>feminine</disp>
fig.    <id>fig.</id> <disp>figuratively</disp>
fr. <id>fr.</id> <disp>from</disp>
fut.    <id>fut.</id> <disp>future</disp>
fut.p.p.    <id>fut.p.p.</id> <disp>future passive participle</disp>
g.  <id>g.</id> <disp><s>gaRa</s></disp>
gen.    <id>gen.</id> <disp>genitive case</disp>
gend.   <id>gend.</id> <disp>gender</disp>
geom.   <id>geom.</id> <disp>geometry</disp>
i.e.    <id>i.e.</id> <disp>id est</disp>
ib. <id>ib.</id> <disp>ibidem or 'in the same place or book or text' as the preceding</disp>
ibc.    <id>ibc.</id> <disp>in the beginning of a compound</disp>
id. <id>id.</id> <disp>idem or 'the same meaning as that of a preceding word'</disp>
ident.  <id>ident.</id> <disp>identical</disp>
ifc.    <id>ifc.</id> <disp>in fine compositi or 'at the end of a compound'</disp>
impers. <id>impers.</id> <disp>impersonal or used impersonally</disp>
impf.   <id>impf.</id> <disp>imperfect tense</disp>
ind.    <id>ind.</id> <disp>indeclinable</disp>
inf.    <id>inf.</id> <disp>infinitive mood</disp>
instr.  <id>instr.</id> <disp>instrumental case</disp>
interj. <id>interj.</id> <disp>interjection</disp>
interpol.   <id>interpol.</id> <disp>interpolation</disp>
irr.    <id>irr.</id> <disp>irregular</disp>
lat.    <id>lat.</id> <disp>latitude</disp>
lit.    <id>lit.</id> <disp>literally</disp>
loc.    <id>loc.</id> <disp>locative case</disp>
log.    <id>log.</id> <disp>logic</disp>
long.   <id>long.</id> <disp>longitude</disp>
m.  <id>m.</id> <disp>masculine gender</disp>
m.c.    <id>m.c.</id> <disp>metri causa</disp>
math.   <id>math.</id> <disp>mathematics</disp>
medic.  <id>medic.</id> <disp>medicine</disp>
metron. <id>metron.</id> <disp>metronymic</disp>
mfn.    <id>mfn.</id> <disp>masculine, feminine and neuter; or adjective</disp>
myth.   <id>myth.</id> <disp>mythology</disp>
n.  <id>n.</id> <disp>neuter gender</disp>
neg.    <id>neg.</id> <disp>negative</disp>
nom.    <id>nom.</id> <disp>nominative case</disp>
obs.    <id>obs.</id> <disp>obsolete</disp>
onomat. <id>onomat.</id> <disp>onomatopoetic (i.e. formed from imitation of sounds)</disp>
opt.    <id>opt.</id> <disp>optative</disp>
orig.   <id>orig.</id> <disp>originally</disp>
others  <id>others</id> <disp>according to others</disp>
p.  <id>p.</id> <disp>page and participle (cf. p.p.)</disp>
p.p.    <id>p.p.</id> <disp>past participle</disp>
parox.  <id>parox.</id> <disp>paroxytone</disp>
part.   <id>part.</id> <disp>participle</disp>
partic. <id>partic.</id> <disp>particular</disp>
patr.   <id>patr.</id> <disp>patronymic</disp>
perh.   <id>perh.</id> <disp>perhaps</disp>
pers.   <id>pers.</id> <disp>person</disp>
pf. <id>pf.</id> <disp>perfect tense</disp>
phil.   <id>phil.</id> <disp>philosophy</disp>
pl. <id>pl.</id> <disp>plural</disp>
poet.   <id>poet.</id> <disp>poetry or poetic</disp>
prec.   <id>prec.</id> <disp>preceding</disp>
prep.   <id>prep.</id> <disp>preposition</disp>
prepos. <id>prepos.</id> <disp>preposition</disp>
pres.   <id>pres.</id> <disp>present tense</disp>
priv.   <id>priv.</id> <disp>privative</disp>
prob.   <id>prob.</id> <disp>probably</disp>
pron.   <id>pron.</id> <disp>pronoun</disp>
pronom. <id>pronom.</id> <disp>pronominal</disp>
propar. <id>propar.</id> <disp>proparoxytone</disp>
q.v.    <id>q.v.</id> <disp>quod vide</disp>
redupl. <id>redupl.</id> <disp>reduplicated</disp>
rhet.   <id>rhet.</id> <disp>rhetoric</disp>
rt. <id>rt.</id> <disp>root</disp>
rts.    <id>rts.</id> <disp>roots</disp>
s.v.    <id>s.v.</id> <disp>sub voce, i.e. the word in the Sanskrit order</disp>
sc. <id>sc.</id> <disp>scilicet</disp>
scil.   <id>scil.</id> <disp>scilicet</disp>
seq.    <id>seq.</id> <disp>sequens</disp>
sev.    <id>sev.</id> <disp>several</disp>
sing.   <id>sing.</id> <disp>singular</disp>
subst.  <id>subst.</id> <disp>substantive</disp>
suff.   <id>suff.</id> <disp>suffix</disp>
superl. <id>superl.</id> <disp>superlative degree</disp>
surg.   <id>surg.</id> <disp>surgery</disp>
v.l.    <id>v.l.</id> <disp>varia lectio</disp>
vb. <id>vb.</id> <disp>verb</disp>
voc.    <id>voc.</id> <disp>vocative case</disp>
vow.    <id>vow.</id> <disp>vowel</disp>
w.r.    <id>w.r.</id> <disp>wrong reading</disp>
wk. <id>wk.</id> <disp>work</disp></code>

**Comment by gasyoun** [comment]
> p. page and participle (cf. p.p.)

Can we make it `or` instead of `and`, @funderburkjim ?

**Comment by funderburkjim** [comment]
This abbreviation now changed to use 'or'.

**Comment by gasyoun** [comment]
Be aware that in case like `<ab>N.</ab> of a poet. ` the `poet.` looks similar to an abbreviation and is so marked in the display.

**Comment by drdhaval2785** [comment]
```
(H1) [Printed book page 1069,3]
Whitney Roots links: शा   & Westergaard Dhatupatha links: 27.3
1. शि (accord. to some = √शो) cl. 3. P. शिशाति (Impv. शिशीहि, शाधि), to grant, bestow, RV.  (cf. Nir. v, 23 ); 
```
Therefore, now no `p=12345` exists.
Closing.
