### ISSUE TITLE
bot markup cleanup (1)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#110]
This note deals with the 'did you mean' list of botanical name possible corrections from
#51 ([comment](https://github.com/sanskrit-lexicon/MWS/issues/51#issuecomment-833837360)).

A program was developed to develop change transactions for some of the suggestions. Related files are in [this gist](https://gist.github.com/funderburkjim/d308e398a5e80da4bfa0c1b32981b3d7).
* readme.txt  :  How to run the program
* did.you.mean.txt  Tab-delimited file, from excel file `did you mean.xslx` of  #51 . Each line has 2 fields
  * An 'old' botanical name X and a 'new' botanical name Y
* change_misc.py  Python program to analyze did.you.mean.txt
  * finds all instances of `<bot>X</bot>` and `<bot>Y</bot>` in mw.txt; and produces two reports.  
* suggest_stats.txt  First report. Shows the number of instances in mw.txt of the two tags.  Sorts all the instance lines.  Lines with many more mw instances of Y than X come first.  Marks as DONE those
also appearing in the suggest_changes file (162 of these); marks the rest as TODO (186 of these).
* suggest_changes.txt Prepares change transactions for MW to make spelling corrections.  219 change transactions in all, corresponding to the 162 records marked as DONE in suggest_stats.

**Comment by funderburkjim** [comment]
## discussion of format
First line of sample_stats.txt:
```
063 1 asparagos racemosus	64 asparagus racemosus (DONE)
```
* 063 is 64 - 1;  the file is sorted from high to low on this numerical field.
*  `<bot>asparagos racemosus</bot>` occurs 1 time in mw.txt
* `<bot>asparagus racemosus</bot>` occurs 64 times in mw.txt
* DONE:  records marked as DONE when
  * number of suggested spelling instances is greater than or equal to number of questioned spelling instances AND
  * number of suggested spelling instances is not 0.
 

Sample from suggest_changes:
```
; old: <bot>asparagos racemosus</bot> occurs 1 times
; new: <bot>asparagus racemosus</bot> occurs 64 times
;
; 99034 : dvIpikA : Asparagos Racemosus : Asparagus Racemosus : typo or print change?=
; <L>99034<pc>507,1<k1>dvIpikA<k2>dvIpikA<e>2
333660 old <s>dvIpikA</s> ¦ <lex>f.</lex> <bot>Asparagos Racemosus</bot>, <ls>Car.</ls> (<ab>cf.</ab> <s>dvIpaSatru</s> and <s>dvIpya</s>). <info lex="f"/>
333660 new <s>dvIpikA</s> ¦ <lex>f.</lex> <bot>Asparagus Racemosus</bot>, <ls>Car.</ls> (<ab>cf.</ab> <s>dvIpaSatru</s> and <s>dvIpya</s>). <info lex="f"/>
```

In addition to the proposed mw change transaction, we show the metaline
and a line for later manual determination of whether the change is a typo or is
a change to the printed text (and thus to be included in mw_printchange.txt of
csl-corrections repository).

**Comment by funderburkjim** [comment]
@gasyoun   

I have not yet made the proposed changes of suggest_changes.txt.

Request that you review first.

Plan to ask @sanskritisampada to check the scanned images to determine which
corrections are typos and which are print changes.

**Comment by gasyoun** [comment]
> line for later manual determination of whether the change is a typo or is a change to the printed text
Everything thought of.

> Request that you review first.

https://gist.github.com/funderburkjim/d308e398a5e80da4bfa0c1b32981b3d7#file-suggest_changes-txt

Looked at some, Jim. I guess it's a drastical and long wanted cleanup. Next step - I will propose URLs to link to. I guess cases like 54 times vs. 1 time are bulletproof enough not to spend more time on them, other that deciding print or non-print error.

> Plan to ask @sanskritisampada to check the scanned images to determine which
corrections are typos and which are print changes.

Sounds like a plan, guess most are typos.

**Comment by funderburkjim** [comment]
suggest_changes transactions applied to mw.txt.  See commit b3dc0ce of csl-orig.

@sanskritisampada has agreed to finish the print/typo identification when current the SHS corrections (https://github.com/sanskrit-lexicon/csl-corrections/issues/64) finished.

**Comment by gasyoun** [comment]
Thanks @sanskritisampada

**Comment by funderburkjim** [comment]
Comments from @sanskritisampada  email (paraphrased):
* Both `Colosanthes Indica` and `Calosanthes Indica` seem acceptable.  The 3 `Col..` changed to `Cal` for
   consistency, and mark as print changes.
* `ameranthus oleraceus` changed to `amaranthus oleraceus` . However Perhaps 'ameranthus' is really the
   correct one.  @gasyoun   Please review and decide which is right.
* under ambupattrA, the text abbreviation 'Cyperus Hex. C.' is expanded to 'Cyperus Hexastachyus Communis'
* under durgakAraka, we have changed Bhojpatra  to Bhojpattra (and this is marked as a print change).
  However, we should probably change back to 'Bhojpatra' based on evidence:
   * `<bot>Betula Bhojpattra</bot>` occurs 4 times in MW, while
   * `<bot>Betula Bhojpatra</bot>` occurs 20 times.
   * 'bhojpatra' spelling also seen in Wilson.
   *  @gasyoun   Please review and decide if we should use 'Bhojpatra' throughout.

**Comment by funderburkjim** [comment]
The suggest_changes file after editing by Sampada:

[suggest_changes.txt](https://github.com/sanskrit-lexicon/MWS/files/6765656/suggest_changes.txt)

The print change notifications now installed in csl-corrections ([refer](https://github.com/sanskrit-lexicon/csl-corrections/commit/3bc95c14538dd8c752181786728e3610bd94bd0a)).

**Comment by gasyoun** [comment]
> we should probably change back to 'Bhojpatra' based on evidence

The amount speaks for itself, I agree.
