### ISSUE TITLE
Missing ls tags

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#112]
Some are because of typo errors, and some are **real missings**!
[Unmarked ls lines- 1st sample (MW).txt](https://github.com/sanskrit-lexicon/MWS/files/7149837/Unmarked.ls.lines-.1st.sample.MW.txt)

@funderburkjim, shall I continue posting the rest also?

**Comment by funderburkjim** [comment]
Yes, please continue the postings.  These need to be marked in mw.txt.

A couple of additional things to attend to.
1.  OGerm.   should be marked with 'ab' tag, not ls.   So make two files, one for unmarked ls and one for unmarked ab.
2.  Determine whether the unmarked abbreviation already exists *with exactly the same spelling*  within the
    tooltip files for ls or ab, respectively.
    * for example,  I see 'Up.' as abbreviation in the mwauth.txt file (the ls references), but the unmarked item in your file
       shows as 'UP.'   So a new entry in mwauth.txt is required.  In this case, it would be same as for 'Up.', except for 'UP.'
    * some of the unmarked abbreviations are malformed as by missing a period  (e.g. [TS]  should be [TS.]).   Since 'TS.' is
       already in mwauth.txt, no new entry is required.   Add a  note in unmarked_ls file, such as  `(Correct spelling to 'TS.')`.

You can download copies of the two 'tooltip' files from:
* [mwauth.txt](https://raw.githubusercontent.com/sanskrit-lexicon/csl-pywork/master/v02/distinctfiles/mw/pywork/mwauth/mwauth.txt)
* [mwab_input.txt](https://raw.githubusercontent.com/sanskrit-lexicon/csl-pywork/master/v02/distinctfiles/mw/pywork/mwab/mwab_input.txt)

3. For cases where the ls (or ab) element is new (not in one of the tooltip files)
  Suggest you make mwab_new.txt and mwauth_new.txt files, and add appropriately formatted new entries.
  The format should preserved.


When you are finished with your work,  it will be up to me to make the corrections in csl-orig/v02/mw/mw.txt and
in the two tooltip files in csl-pywork/v02.

**Comment by funderburkjim** [comment]
Note: in the 'UP.' example, you might check the scanned image -- perhaps this is a typo  (e.g. scan has 'Up.' but mw.txt has 'UP.').
In such a case, this would be handled like '[TS]'  , in particular no new line in mwauth.txt would be required.

**Comment by Andhrabharati** [comment]
More than half of these are due to typo errors!

For example, UP. is a typo for Up.

**Comment by Andhrabharati** [comment]
I cross-checked all these lines with the book (but not corrected any), before posting.

**Comment by Andhrabharati** [comment]
This is the 2nd portion words list for missed marking.
[MW extract for required abbr and ls marking (dot ending).txt](https://github.com/sanskrit-lexicon/MWS/files/7150002/MW.extract.for.required.abbr.and.ls.marking.dot.ending.txt)

**Comment by Andhrabharati** [comment]
And the last part, no-dot ending words list-
[MW extract for required abbr and ls marking (no-dot ending).txt](https://github.com/sanskrit-lexicon/MWS/files/7150043/MW.extract.for.required.abbr.and.ls.marking.no-dot.ending.txt)

**Comment by Andhrabharati** [comment]
The first action is to correct the typo errors in mw.txt for all these 3 parts, and then to do necessary `<ab>` and `<ls>` markings.

**Comment by Andhrabharati** [comment]
Seen that quite many listed in the three files above have been 'handled' so far; but still many more are remaining.

Will be posting the results in #135, that is presently being looked at by @funderburkjim

And this issue can be closed as such.
