### ISSUE TITLE
plIhan 

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/MWS#115]
Please note that `<s>स्प्लिहेन्</s>` deserves to be in etym tag i.e. `<etym>splihen</etym>`
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MW&page=715

Similarly, we can explore if there are other places where the word which is in etymology section is erroneously converted to Sanskrit tagging.
```
476531
[]
['splezena']
 [Orig. <s>स्प्लीहन्</s>; <ab>cf.</ab> <ab>Gk.</ab> <lang>σπλήν</lang>, <lang>σπλάγχνον</lang>; <ab>Lat.</ab> <lang>lien</lang> for <s>स्प्लिहेन्</s>; <ab>Slav.</ab> <lang>slezena</lang> for <s>स्प्लेशेन</s>; <ab>Eng.</ab> spleen.]
<s>प्लीहन्</s> ¦ [Orig. <s>स्प्लीहन्</s>; <ab>cf.</ab> <ab>Gk.</ab> <lang n="greek">σπλήν</lang>, <lang n="greek">σπλάγχνον</lang>; <ab>Lat.</ab> <etym>lien</etym> for <s>स्प्लिहेन्</s>; <ab>Slav.</ab> <etym>slezena</etym> for <etym>splezena</etym>; <ab>Eng.</ab> spleen.]
```

**Comment by Andhrabharati** [comment]
I have "handled" all the etym. entries in my current review, and so this issue does not need any more discussion.

**Comment by Andhrabharati** [comment]
@drdhaval2785 

I've made a complete list now for @funderburkjim, and noted the below from that file--

- 64 `<s>` tags need to be changed to other non-Skt. tags (whether Foreign or Indian languages), 

and the reverse case

- 3 `<etym>` tags need to be changed to `<s>` tags

**Comment by drdhaval2785** [comment]
Ok
