### ISSUE TITLE
Lithuanian in mAs

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/MWS#118]
I can see a slight dot above e.
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MW&page=814
```
<ab>Lith.</ab> <etym>mēnů</etym>, <etym>menesis</etym>
```

**Comment by drdhaval2785** [comment]
Similarly in 'mih'
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MW&page=818
```
<L>164576.1<pc>818,2<k1>मिह्<k2>मिह्<e>1E
<s>मिह्</s> ¦ [<ab>cf.</ab> <ab>Gk.</ab> <lang n="greek">ὀμιχεῖν</lang>, <ab>Lat.</ab> <etym>mingere</etym>, <etym>mejere</etym>; <ab>Slav.</ab> <etym>migla</etym>; <ab>Lith.</ab> <etym>mēżti</etym>, <ab>Angl.Sax.</ab> <etym>mîgan</etym>; <ab>Germ.</ab> <etym>Mist</etym>.]
```

**Comment by Andhrabharati** [comment]
Yes, guess you should better use the file posted exclusively for Lithuanian words, which got a 2nd reading from my side.

As I already mentioned (at https://github.com/sanskrit-lexicon/CORRECTIONS/issues/362#issuecomment-915451982), I had noticed few errors in my earlier file (being done just as a trial exercise) those days.

And thought of doing another reading based on your feedback-

> it will be another reading from my side for those complete lines (and I am more "matured" now in the process), and also it saves Dhaval's time considerably.
> 
> what would @drdhaval2785 say about this?

> Anyway, first let Dhaval have a look at the file sent and try to make a plan about using its data, as that was the original idea agreed upon.

**Comment by Andhrabharati** [comment]
My current review has "handled" all these, and this issue is closable now.
