### ISSUE TITLE
List of Proper Names (N.)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#12]
https://github.com/sanskrit-lexicon/MWS/issues/5 continued. In the search of names.
There are 47851 instances of "N." if counted in .xml file in Notepad++. The http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc2/index.php if searched by "N. of" shows endless variations of "m. N. of a man or tribe", but the total sum is never showed. Like vizvAmitra 201542, turvaza 86102 - names of historic heroes. That's what I actually aim for. And than there is agnitanu 944.1 - it's in the (first, <_ab>) ~880 list, but it's only "of partic. texts", so I would manually want to add some markup to differentiate people (gods, daemons etc.) from non-people and in this case exclude agnitanu 944.1 as non-people. Right now part of N. is in <_ab>, but much more is inside <c>, that means almost no code at all. So anyway - tags for N. have to go through a change, as they are they are non-uniform and with little value.
Otherwise the 880 list does not contain even the most popular names like Agni. It means that the <_ab> approach was wrong or the tag is not used wide enough. Tertium non datur.

![9-24-2014 22-12-51 n](https://cloud.githubusercontent.com/assets/80761/4393567/053a7986-4419-11e4-8a1f-050008dd88f9.gif)

**Comment by Andhrabharati** [comment]
@funderburkjim / @gasyoun,

Is this issue closable now?

**Comment by funderburkjim** [comment]
As with several of these earlier (2014) issues of @gasyoun , there are some good ideas (e.g. cross-referencing proper names in dictionaries).  But it is still unclear how to proceed with such analytical goals.

Since the issue still remains visible even if closed,, I say we close the issue now, since there is no clear path to resolution of the issue.
