### ISSUE TITLE
Capital letter words

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#121]
This issue a placeholder for following up suggestion in #120 regarding this list of
[Capital letter words](https://github.com/sanskrit-lexicon/MWS/blob/master/mws_issue_99/unique_section-wise_entries_Andhrabharati/(Capital%20letter)%20unique%20words%20extracted.txt).

This list might have several uses, one of which is to search for unmarked ls references.

**Comment by funderburkjim** [comment]
Examining the [capwords.txt](https://github.com/sanskrit-lexicon/MWS/tree/master/mws_issue_99/capword_changes/capwords.txt) list of words unearthed many errors and awkward codings in the mw.txt digitization.

About 2000 changes have been made to mw.txt as a result of this examination.

The LOG section of the readme.txt file of [capword_changes](https://github.com/sanskrit-lexicon/MWS/tree/master/mws_issue_99/capword_changes) folder,  provides a summary of the changes.
The [change_1.txt](https://github.com/sanskrit-lexicon/MWS/tree/master/mws_issue_99/capword_changes/change_1.txt) file has the detailed change transactions.

**Comment by Andhrabharati** [comment]
A quick look at the << entries in the readme file resulted in this-
[response to readme entries.txt](https://github.com/sanskrit-lexicon/MWS/files/7355827/response.to.readme.entries.txt)

**Comment by Andhrabharati** [comment]
Some more << entries checked-
[response-2 to readme entries.txt](https://github.com/sanskrit-lexicon/MWS/files/7357106/response-2.to.readme.entries.txt)

**Comment by Andhrabharati** [comment]
O. S. -> O.S. unmarked abbrev (1) <<< tooltip help wanted: <L>171842<pc>854,1<k1>yuga
It is 'o. s.', not 'O. S.'
A "remote" possibility could be "old system" as used in chronological citations.
[Just for ref.- [Handy_book_of_rules_and_tables_for_verifying_dates.pdf](https://github.com/sanskrit-lexicon/MWS/files/7357223/Handy_book_of_rules_and_tables_for_verifying_dates.pdf)]

**Comment by funderburkjim** [comment]
> Them.  Thema or base (from MW72)  What does 'Thema or base' mean?
  <ab>Goth.</ab> <etym>ais</etym>, <ab>Thema</ab> <etym>aisa</etym>

Used 'Thema or base' as suggested.

But what does it mean?

**Comment by Andhrabharati** [comment]
> 
> Not sure about `SivaP. Rev. is SkandaP(urāṇa). Rev(ākhaṇḍa)`, so have not changed.

Suggest looking for tIrTa (slp1), where Revākh. occurs 27 times; and this Revākhaṇḍa is a part of SkandaPurāṇa.

Of course. the tIrTa entry occurs in many books incl. Mahābhārata etc. also.

As ŚivaP. also ocuurs quite many times, probably it can be retained as is; but Rev. does indicate Rev(ākhaṇḍa) only!!
[May be those tIrTas are mentioned in both ŚivaP. & Rev(ākhaṇḍa), not sure; **but then, there must be a semicolon between two diff. sources which is absent in the print.**]

**Comment by Andhrabharati** [comment]
> 
> 
> > Not sure about `SivaP. Rev. is SkandaP(urāṇa). Rev(ākhaṇḍa)`, so have not changed.
> 
> Suggest looking for tIrTa (slp1), where Revākh. occurs 27 times; and this Revākhaṇḍa is a part of SkandaPurāṇa.
> 
> Of course. the tIrTa entry occurs in many books incl. Mahābhārata etc. also.
> 
> As ŚivaP. also ocuurs quite many times, probably it can be retained as is; but Rev. does indicate Rev(ākhaṇḍa) only!! [May be those tIrTas are mentioned in both ŚivaP. & Rev(ākhaṇḍa), not sure; **but then, there must be a semicolon between two diff. sources which is absent in the print.**]

**I was wrong here!**

Just looked at the PWG entry,

> आखाटीश्वरतीर्थ [Printed book page 5-1089]
> आखाटीश्वरतीर्थ n. N. pr. eines Tīrtha Verz. D. Oxf. H. 67,b,10.                   [ID=66119]
> 

and found that the Aufrecht catalogue has the clue.

It is Revāmāhātmyam of ŚivaP. that is meant here.

p.64 for the Revāmāhātmyam-
![image](https://user-images.githubusercontent.com/75209130/137641551-54e601d2-2ae7-4c6a-82b0-292d1818d59f.png)

and p.67B for आखाटीश्वरतीर्थ-
![image](https://user-images.githubusercontent.com/75209130/137641596-0ce63118-7cf3-4215-b888-f042ff85d0c8.png)

**Comment by Andhrabharati** [comment]
**I could not digest that I was wrong here, so looked closely at the Aufrecht's catalaogue again** and found that the sections 114 to 126 all belong to Skandapurana only (Revamahatmyam, Gayamahatmyam, Kasikhanda, ...)

As the page title is Sivapurana marked wrongly here, it is taken as such by MW. PWG played safe by just mentioning the page no.s for these tIrTas listed under section 114 (Revamahatmyam).

**So I take back my words above, and go with my original posts.**

**Comment by Andhrabharati** [comment]
> Do you have a link for the two scanned images shown above?

I gave the link in PWG, while I was on the `<ls> work` in it few months back.
https://github.com/sanskrit-lexicon/PWG/issues/37#issuecomment-882338955

**Comment by Andhrabharati** [comment]
I guess, in the mwauth.txt, the following does not give a "meaningful" expansion-
Wh.	Wh.	au	<expandNorm>Whitney, W. D. (1872). [Cologne Addition]</expandNorm>

It should've been "Whitney, W. D. (1872), Müller's Rig-Veda translation"; 
[Whitney's review(?)  in 1872, on (Max) Müller's Rig-Veda translation]

**Comment by funderburkjim** [comment]
> What I meant is, this  (Hpar) need not be listed under "remaining puzzles"

Agree

**Comment by drdhaval2785** [comment]
Anything pending? Or closeable?

**Comment by Andhrabharati** [comment]
1. @funderburkjim is yet to correct the Wh. and Ro., though he had appreciated the detective work done.

2. The remaining one in the list **VRJ** is in fact a print error; it should've been VAJ. (Vajasaneyi Samhita).
[We can refer the two VEI entries- `<L>1142` Tārukṣya  and `<L>1143` Tārkṣya-  that MW is dealing with here.]

If these two are considered and corrected in the mw.txt, the issue is closable, @drdhaval2785 !

**Comment by Andhrabharati** [comment]
And probably one might consider the issue #112 as a continuation of this "Capital letter words" issue, which is exactly what Jim started with--
> This list might have several uses, one of which is to search for unmarked ls references.

**Comment by funderburkjim** [comment]
The remaining two corrected:
```
<L>84423<pc>444,2<k1>tArukzAyaRi
 <ls>VRJ.</ls> -> <ls>VĀJ.</ls>
  vAjasaneyi saMhitA

<L>27372<pc>157,1<k1>ASaMs
 <ls>Wh.</ls> and <ls>Ro.</ls> -> <ls>Wh. and Ro.</ls>
  Atharva Veda Sanhita, Volume 1, by  R.Roth and W.D. Whitney, 1856
```
