### ISSUE TITLE
<ab> v. <lex> gender markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#124]
in csl-orig/v02/mw/mw.txt (as of commit ab4e97f3bbde717d489efc572096af9072cec1a2), there are 136 matches to the regex `<ab>[mfn]+\.</ab>`.  For example
```
<s>AvayAs</s> ¦ <lex>m.</lex> (<ab>f.</ab> ?) <ab>pl.</ab> water, <ls>Nigh. i, 12.</ls><info lex="m"/>
```
In most of these cases, a better markup would use `<lex>` tag, perhaps with one of its attributes.
And also, the corresponding `<info lex=.../>` element would be altered.  In this example, we might better use
```
<s>AvayAs</s> ¦ <lex>m.</lex> (<lex>f.</lex> ?) <ab>pl.</ab> water, <ls>Nigh. i, 12.</ls><info lex="m:f"/>
```

This condition was noticed in work of #123.

This seems like a fairly low-priority item.  Mentioning it in separate issue so it can be reconsidered sometime.

**Comment by Andhrabharati** [comment]
I have "handled" all such cases in my current review, and this issue is closable now.
