### ISSUE TITLE
SivaPurana refs in tIrTa entries : Should they be SkandaPurana?

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#125]
In several comments in #121, ([first comment](https://github.com/sanskrit-lexicon/MWS/issues/121#issuecomment-945172439)),  the question was raised
whether numerous MW references to SivaPurana should be replaced by Skanda Purana references.

These questions particularly relate to tIrTa entries; e.g. there are 57 entries in mw.txt matching regex `tIrTa.*<ls>ŚivaP.`, and all these perhaps need to be changed to 'SkandaP.' references.

There is also a slightly different question as to whether the 6 MW references `ŚivaP. Rev.` should also be
corrected (to refer to SkandaP.)

The suggestion is that MW propagated errors from one or more sources. 

If we decide to 'correct' these errors, then we may wish to extend the current markup system for MW to
more helpfully identify the 'old' and 'new' text involved in the correction.  Such markup extension could
also have application to other 'corrections' in MW, including both corrections mentioned in the Supplement and corrections identified in the Cologne document 'mw_printchange.txt'.

**Comment by gasyoun** [comment]
> old' and 'new' text involved in the correction

Agree.

**Comment by Andhrabharati** [comment]
As I am quite sure of the correction, incorporated this in my review now.

**Comment by Andhrabharati** [comment]
This issue is closable now.
