### ISSUE TITLE
Links to Dhātup. xix, 74

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#126]
@funderburkjim Whitney Roots links: rāj   & Westergaard Dhatupatha links are working for ages.

![dhatup](https://user-images.githubusercontent.com/80761/138681152-c65e7895-7b3f-407e-9581-c85bc1a134f8.png)

But Dhātup. xix, 74, linking to the same place, is not. Fixable?

**Comment by Andhrabharati** [comment]
This fruit is still **not low enough**, that @funderburkjim can put his hands on it.

**Comment by funderburkjim** [comment]
## begin link-addition process

Stepladder obtained :)

Preliminary examination of form of Dhātup. (or Dhāt.) references.
Work material in [issue26 directory](https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue126).

Usual form of Dhātup. reference is `<ls>Dhātup. R, n</ls>`, where R is lower-case roman numeral and n is integer.
The link to be generated is then
```
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-westergaard/disp/index.php?section=X
```
where X is Latin letter form of R.  e.g. `Dhātup. v, 26` should generate link
```
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-westergaard/disp/index.php?section=5
```
Note that 'n' (e.g. 26) is not part of the link.
Thus, links can be generated when 'n' is absent (e.g. `<ls>Dhātup. xi</ls>`).

The above changes to mw.txt in csl-orig deal with a few typos and irregular ls forms.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Here is what the parent "source" of MW [PWG] has for the two '84, 6' cases--

वेक्ष् [6-1348]
वेक्ष् , वेक्षयति (दर्शने) Dhātup. 35, 84,b. 
— Vgl. वेक्षण und व्लेक्ष् .
                 [ID=95135]

हिल्लोलय् [7-1629]
हिल्लोलय् , °यति = हिन्दोलय् Dhātup. 35,84,h.
                 [ID=117204]

**Comment by funderburkjim** [comment]
84,6 cases corrected as print changes to mw.  Thanks, @Andhrabharati

**Comment by funderburkjim** [comment]
Link target now implemented in displays for MW.  See commits above for details.

Additionally, links to Westergaard also implemented for 
* pw  (30 instances)
* pwg (2530 instances)

Two remaining related tasks:
* review the pwg Dhatup. links -- for mistakes in markup
* Add markup in Sch. (14 instances) for links.

**Comment by Andhrabharati** [comment]
> * Add markup in Sch. (14 instances) for links, and implement linking in displays

SCH has only 13 instances from Dhātup., not 14.

Speaking of this, probably you might be interested in looking at my SCH text having the ab- and ls- taggings done throughout (exactly two years back, but not posted for a reason).

**Comment by gasyoun** [comment]
> might be interested in looking at my SCH text having the ab-, lex-, lang-, hom-, bot-, zoo-, and ls- taggings done throughout (exactly two years back, but not posted for a reason).

@Andhrabharati how to look at it, if not posted? Strange indeed.

**Comment by Andhrabharati** [comment]
I was asking Jim if would be interested to see (rather, to use!!) it, if posted.

**Comment by funderburkjim** [comment]
## pwg dhatup changes

 about 394 lines changed in pwg.txt. [change_pwg_2.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue126/change_pwg_2.txt).
   Most of these were of form: `<ls>DHĀTUP. X, Y, v. l.</ls>' -> `<ls>DHĀTUP. X, Y</ls>, v. l.`.   At some later time `<ab>` markup to be added to 'v. l.', there are many other abbreviations that need markup and tooltips in pwg.
  'standard form' is ` <ls>DHĀTUP. X, Y</ls>` where X, Y are digit sequences, with X being 1 to 35. (sections of Westergaard's dhatupatha.).  There are a few other forms also unchanged.
 The change_pwg_2_unused.txt contains the 25 that are considered non-standard.

File dhatup_pwg_2.txt contains all the DHĀTUP. references identified.  The 25 'non-standard' are marked with `?`.

This work finishes my objectives for pwg in this issue.

**Comment by funderburkjim** [comment]
@Andhrabharati I intend next to add the markup for DHĀTUP. in Schmidt.
Since there are only a few, probably I don't require your latest work on Sch,
but it would be interesting to 'see' it, if you are inclined to share that work at this time.

**Comment by funderburkjim** [comment]
## sch links

These are now activated and available in the Cologne displays of Schmidt.  The commit links above show the changes.

dhatup_sch_2.txt indicate the instances

There are two instances that are questionable:
```
<L>11832<pc>162-3<k1>Kadana : Dhātup. 1, 960.
<L>13009<pc>179-2<k1>can : Dhātup. 1, 840.
```
There is no subsection 960 or 840 in section 1 of Westergaard, according to out edition ([section 1 Westergaard](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-westergaard/disp/index.php?section=1)).  Nor are the words (Kadana, can) mentioned in section 1.  Some searching in PW (and PWG) gave no resolution.
So the interpretation of these two is a mystery.

**Comment by funderburkjim** [comment]
This is all I had in mind to do regarding this issue.
Low-hanging (?) fruit now harvested.
Closing issue.

**Comment by Andhrabharati** [comment]
> There are two instances that are questionable:
> 
> ```
> <L>11832<pc>162-3<k1>Kadana : Dhātup. 1, 960.
> <L>13009<pc>179-2<k1>can : Dhātup. 1, 840.
> ```
> 
> There is no subsection 960 or 840 in section 1 of Westergaard, according to out edition ([section 1 Westergaard](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-westergaard/disp/index.php?section=1)). Nor are the words (Kadana, can) mentioned in section 1. Some searching in PW (and PWG) gave no resolution. So the interpretation of these two is a mystery.

It is no mystery, if one knows the details of the original Skt. works! **Probably, we can term this as 'confusing' naming.**

These are not referring to the Westergaard's 'organisation' of Radices, but directly pointing to the DHĀTUP. of PĀN. itself.
These roots are present in the first class (bhvAdi) at positions 960 and 840 resp.

![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/41d1a7c8-66ea-4ff1-8434-31822c482f64)

![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/1d7621dc-5a64-49c5-bbef-e9b772a47cb7)

**Comment by Andhrabharati** [comment]
> `At some later time ``markup to be added to 'v. l.', there are many other abbreviations that need markup and tooltips in pwg.`

@funderburkjim 
If you 'fix-up' a time, I am willing to post my PWG work that has dealt with this and many other 'useful' changes that I envisaged.

Probably, it won't be a big hurdle in adopting my PWG file to CDSL (in the same way that my pwk was "taken" some time back).

**Comment by Andhrabharati** [comment]
> @Andhrabharati I intend next to add the markup for DHĀTUP. in Schmidt. Since there are only a few, probably I don't require your latest work on Sch, but it would be interesting to 'see' it, if you are inclined to share that work at this time.

Where do you wish this to be posted (**this issue is not the 'proper' place, I believe**)?

**Comment by funderburkjim** [comment]
re where to post 'sch' latest work: Make an issue at https://github.com/sanskrit-lexicon/sch/issues

**Comment by funderburkjim** [comment]
>  Dhātup. 1, 840.

Wonderful that you solved the mystery!

We need to change the markup so that for these two, we indicate a reference to  the edition of Pāṇini Dhātupāṭha. that your (private) image above shows.  This edition must be from one of the German indologists.
`<b>Please provide a tooltip</b>`.

Incidentally, there appears to be variation among editions. For instance, https://archive.org/details/TheDhatupathaOfPanini_428/page/n25/mode/2up  shows a different root (not 'can') for 1-840:
<img width="281" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/31410736-ed4f-4023-a9a0-e1f49e77886b">

**Comment by Andhrabharati** [comment]
> This edition must be from one of the German indologists.

This is from none other than Boethlingk himself!!

By the time of completion of pwk  (1889), his 2nd (revised/enlarged) ed. of Panini (1887) has been published; and it seems to be still 'afresh' in B.'s mind, that he was 'prompted' to cite from it instead of Westergaard!!
[It may be noted that ( for 'can') PWG has Westergaard 19,41, while pwk has B.'s P. (appendix) 1,840.]

**Comment by Andhrabharati** [comment]
> Incidentally, there appears to be variation among editions.

We can discuss on the variations among various editions (**of nearly all the Indic texts**) elsewhere, if the 'real' need comes (at sometime).

**Comment by funderburkjim** [comment]
## Revised coding
```
OLD
<ls>Dhātup. 1, 960</ls>
NEW
<ab n="DHĀTUPĀṬHA">Dhātup.</ab> <ls n="DhātupB.">1, 960.</ls>
```
and similarly for the other.

Note; Enjoyed the background of B's DHĀTUPĀṬHA.

Goodbye again to this issue.
