### ISSUE TITLE
nikāya lost

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#128]
nikāya not showing up @funderburkjim 

![rerereerw](https://user-images.githubusercontent.com/80761/154867221-ae9466cc-a7e9-4dc6-9e8c-4fed82a2e42f.png)

Never seen such an effect before

**Comment by Andhrabharati** [comment]
It is seen that the resulting data for nikAya entry is displayed for a flash and then disappeared.
`-------------------`
Another related (?) observation-

![image](https://user-images.githubusercontent.com/75209130/154918396-c5207ce0-d7e8-4552-bf16-2e3dec20ba6f.png)

Only 2 out of 5 results displayed on the right side window. (all the subsequent ones after the 'problematic' nikAya are hidden!!)

**Comment by funderburkjim** [comment]
## nested ls

Noticed that mw.txt had an `<ls>` tag nested within another `<ls>` tag.
Changing this removes the display problem.
```
<L>107850.5<pc>544,3<k1>nikAya<k2>ni-kAya/<e>1A
OLD:
the air, wind, <ls>VS. xv, 5 (<ls>Mahīdh.</ls>) </ls><info lex="inh"/>
NEW:
¦ the air, wind, <ls>VS. xv, 5</ls> (<ls>Mahīdh.</ls>) <info lex="inh"/>
<LEND>
```

Several other similar cases also found, and changed.
`20 matches for "<ls>[^<]*<ls" in buffer: mw.txt`  

See commit dfca4c5 for details.

The two display examples of prior comments now work

**Comment by funderburkjim** [comment]
## revise one.dtd

See the pywork commit [b61e434](https://github.com/sanskrit-lexicon/csl-pywork/commit/b61e4340262c1dac7fe8877a4caa09fb6e03bd93).

The allowed children of the `<ls>` element revised to be more restrictive.  This will help identify problems such as
nested 'ls' elements.    A couple of other changes made to mw and also pwg regarding xml children of 'ls' elements,

AFAIK, these changes will have no impact on xml validity for other dictionaries  (pw validity with revised dtd was checked).

I think this issue can now be closed.

**Comment by gasyoun** [comment]
> Several other similar cases also found, and changed.

Thanks.

> AFAIK, these changes will have no impact on xml validity for other dictionaries (pw validity with revised dtd was checked).

Understood.
