### ISSUE TITLE
ifc forms of paYcasahasrI

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#13]
In MW, under paYcasahasrI (slp1), one sees:
![image](https://cloud.githubusercontent.com/assets/6393033/4516638/a13d6786-4c01-11e4-86e6-f7fa56bc7e59.png)

Does this mean that the ifc stems are

m = paYcasahasrIka, f=paYcasahasrIkA, n=paYcasahasrIka  

(i.e., append ka,kA,ka to paYcasahasrI ) ?

**Comment by gasyoun** [comment]
@drdhaval2785 agree?

**Comment by drdhaval2785** [comment]
I agree for -sahasrIkA.

**Comment by drdhaval2785** [comment]
Question is resolved. Installations done @funderburkjim ?

**Comment by Andhrabharati** [comment]
@funderburkjim 

Is this issue closable?
