### ISSUE TITLE
About 6800 missing ¦ (Broken Vertical bar) in the L-entries

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#132]
There are 287628 occurrences of `<L>` (and `<LEND>`), but only 280827 occurrences  of `¦` in the latest mw.txt (taken from csl-orig/v02 folder).

The last mw_iast file I got from Jim in April 2021 has 287634 occurrences of `<L>` (and `<LEND>`) and 280833 of `¦.`
I recall some `<L>` entries getting deleted during the exercise done those days, so the difference of 6 therein is accounted for.

But the difference of 6801 between `<L>` and `¦` seems continuing still.

However, the mw_meta2 file (dated Jun 18, 2018) gives a count of 287433, as under-
> ¦  (\u00a6) 287433 := BROKEN BAR  (Demarcates the headword part of an entry).

Request @funderburkjim to trace whence the 6801 difference started, and give-out the reason.

**Comment by Andhrabharati** [comment]
Here is the smaller chunk lot to complete the "and/or" tagging--
[L-entries to fill and-or tags.txt](https://github.com/sanskrit-lexicon/MWS/files/8943219/L-entries.to.fill.and-or.tags.txt)

**Comment by Andhrabharati** [comment]
Here is how I would've split the entries (header-block and body portion), for the tagged 'and-group' mentioned above--
[tagged 'and-group' entries split with vertical bar.txt](https://github.com/sanskrit-lexicon/MWS/files/8943616/tagged.and-group.entries.split.with.vertical.bar.txt)

**Comment by Andhrabharati** [comment]
Finished the 'or-group' splitting with vertical bar, and in the process some entries were changed to 'and-tagging', looking at the content; and 2 entries were to be untagged altogether!

Now the tagged group counts are-
> Tagged: 6625 [and: 1451 & or: 5174],

as against the earlier counts of 
> Tagged: 6627 [and: 1410 & or: 5217]

With this experience, seems another look at the already "grouped" (or: 1162 & and: 163) entries is needed.
`-------------`
Also seen that there are some entries that need to be identified and marked as group entries; I will be checking for them next.

[**Hope @funderburkjim would be willing to carry this output from my working to the CDSL file.**]

Shall be posting my results, upon his response to this issue.

**Comment by funderburkjim** [comment]
@Andhrabharati  I'm finishing up work to add link markup to Ramayana references in PWG.  This should be  done in a couple of days, and then I'll take a look at your work here on MW.   From a first glance at the two files you provide above,  I see no problem adding the broken vertical bar as you have placed it.

Will await your 'further look' revisions before proceeding to alter cdsl version of mw.txt.

**Comment by gasyoun** [comment]
> add link markup to Ramayana references in PWG

Hurray, long live Ramayana, Russian Sanskrit dictionaries and Jim! 

Working on https://samskrtam.ru/parallel-corpus/ramayana.html

**Comment by Andhrabharati** [comment]
> With this experience, seems another look at the already "grouped" (or: 1162 & and: 163) entries is needed.

The re-look at the already "grouped" entries resulted in the counts as
> or: 1069, orsl: 93 & and: 167

And few of these need some sort of correction in tagging etc.; probably this should be discussed in another (future) issue "grouped entries".

**Comment by Andhrabharati** [comment]
@funderburkjim 

Pl. see the screenshot for PWG ls-tooltip **'error(?)**'--

![image](https://user-images.githubusercontent.com/75209130/175009340-6eee601d-e5e6-489c-a4e6-549a06f03e13.png)

**Comment by funderburkjim** [comment]
## cleanup work finished

The work is further described in the [issue132 directory](https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue132). About 8800 lines of mw.txt were changed.

* currently 6319 entries with `<info or="X"/>`
* 1736 entries with `<info and="X"/>`
* All `<info or/and="X"/>` markup occurs on the *headline* (first line of entry after metaline) within the mw.txt digitization.
* All headlines contain a broken bar.  An attempt has been made to place this broken-bar character in a 'reasonable' location.
* The info-or/and markup has been checked for consistency, e.g.
   `<info or="L1,X1;L2,X2"/>`  occurs identically in the headlines of both entry L1 and L2.

## hom markup sidetrack
I got side-tracked to add homonym markup.  E.g., `1. <s>X</s>` was changed to
`<hom>1.</hom> <s>X</s>` everywhere applicable.

## not done
I did not address `some entries that need to be identified and marked as group entries` as mentioned by @Andhrabharati.

Will see what further corrections @Andhrabharati  suggests before closing this issue.

**Comment by Andhrabharati** [comment]
The primary point (the missing broken-bar) in this issue having been addressed, **I would suggest this to be closed now**.

> And few of these need some sort of correction in tagging etc.; probably this should be discussed in another (future) issue "grouped entries".

As I had mentioned above, the the rest (about the grouped-entries) could be dealt in another issue.

@funderburkjim may look at the #137 issue next, before generating the IAST file again **(for enabling me to resume further study)**.

**Comment by funderburkjim** [comment]
Yes, I'm just starting the 137 changes, and will regenerate the iast version of mw at the end of that.

**Comment by Andhrabharati** [comment]
@funderburkjim 

just did a casual checking for `<L>` and `¦` counts, and got a difference of 3 (287616 vs. 287619).

then found 3 orphan `¦` instances [just dangling isolated] at lines (255594), (274957) and (280382).

**Comment by Andhrabharati** [comment]
There are 2 ¦ instances without a preceding space, and another 2  ¦ instances without a following space.

**Comment by gasyoun** [comment]
> then found 3 orphan ¦ instances [just dangling isolated] at lines (255594), (274957) and (280382).

Who are you by education?

**Comment by Andhrabharati** [comment]
I am an (Electronics) Engineer.

**Comment by Andhrabharati** [comment]
@funderburkjim 

The `<info ...>` tags have been at the end of the line preceding a `<LEND>` line so far.

But now noticed that there are 217 instances where these tags are in the next line after the meta-lines; these need to be shifted to the line preceding the resp. `<LEND>` lines.

[I've used the regex `<info (.*?)\n<[^L]` to find these instances.]

**Comment by funderburkjim** [comment]
## orphan broken bar

These will removed in #137.

**Comment by funderburkjim** [comment]
## placement of `<info`

There is no definite rule where the various `<info .../>` markup should appear.  These empty
xml info elements contain various kinds of  'meta' information. The entry-relative location of
these is as we view them to be 'convenient'.

I think it is convenient to have the `<info or/and="X"/>`  tag on the headline, since
then it is readily compared to the placement of the broken bar.  

I'll look at the 217 instances;  and will probably move the info elements to the lastline (line before `<LEND>`) *except* for the `<info or/and="X"/>` elements.  Will do this in the #137 work.

**Comment by Andhrabharati** [comment]
My main intention is that all `<info ...>` tags could be in the same line (probably barring the **sup** and **rev** entries of the Annexure data); there are ~50 cases of `<info [oa]` tag on **headline** and the `<info [wv]` on another line, while all other (~150) cases of `<info [oa]` and the `<info [wv]` are on the same **headline**.

And then, noticed 2 instances of `<info orsl="248495,sumnAya;248495.1,sumnaya"/>` that are not in the **headline**.
