### ISSUE TITLE
<bio> tagging

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#133]
Unlike the `<bot>` tag which covered both the primary and secondary names together, the `<bio>` tag is individually applied to the primary and secondary names.

There are 163 `</bio> <bio>` places in the whole text, which can safely be replaced by a **'space'**.

**Comment by Andhrabharati** [comment]
Just for info, I've corrected these in my file and closing the issue now.

**Comment by gasyoun** [comment]
>There are 163 </bio> <bio> places in the whole text, which can safely be replaced by a 'space'.

Why? Whas it not a test?

**Comment by Andhrabharati** [comment]
Revisited the `<bio>` tag in my current review, and

1. merged the two part tagging into single entries,
2. changed few to `<bot>`, where needed, and
3. removed the tag altogether where it is wrongly marked.

The tag count now became 342 from the existing 523.

**Now this is issue is being 'really' closed; I thought I did so last June, but seems it was not  done so.**
