### ISSUE TITLE
RV references without the RV -- AND general<ls> cleanup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#134]
Under https://github.com/sanskrit-lexicon/PWG/issues/23, a comment noticed
an unmarked RV reference in MW:
```
and <ab>Prec.</ab> <s>cyozIQvam</s>, <ls>Pāṇ. viii, 3, 78</ls>; <ls>Kāś.</ls>) to move to and fro, shake about, 
<ls>RV. i, 167, 8</ls>;
<div n="to"/>to stir, move from one's place, go away, retire from (<ab>abl.</ab>), 
turn off; 
<ls>vi, 62, 7</ls>;   <<< ALSO RV. NOT MARKED
<div n="vp"/> <ls>x</ls>;   <<< NO IDEA what this 'x' is referring to!
<ls>BhP. ix, 14, 20</ls>;
```

Once noticed, we can change the markup  : `<ls n="RV.">vi, 62, 7</ls>`.

*But these are hard to find.*  I may have some software used in PW or PWG that would be applicable;
Will look for it.

**Comment by gasyoun** [comment]
>  I may have some software used in PW or PWG that would be applicable; Will look for it.

Hard, but not impossible for the regex magician Jim, thanks!

**Comment by Andhrabharati** [comment]
He has already listed them in lsextract file as two types--

> 00239	NUMBER	number (ls starts with number)

I find 240 of such in 223 lines!

> 12809	UNKNOWN	unknown (ls is unknown)

I find 9920 of `<ls>ib.</ls>`; 766 of `<ls>i[^b]`; 65 of `<ls> `; 75 of `<ls>,`; 23 of `<ls>;`; and 1119 of `<ls>[a-hj-z]`.
**A difference of 1000 (wrt Jim's count) is yet to be traced.**

1. Along with the 240 of IA numbered items above, the 27 of <ls>c, !500 of `<ls>v`, ~500 of `<ls>x` and 766 of `<ls>i` could be clubbed with the prev. Ls-entity.
2. All the 9920 `<ls>ib.</ls>` entries could be equated to the prev. Ls-entity.

**Comment by funderburkjim** [comment]
This phase of cleanup of MW ls references completed.
About 2800 lines changed.  This is the [csl-orig commit](https://github.com/sanskrit-lexicon/csl-orig/commit/3336b724834e84ef0ae1010d73a95fa090292761).

For details, see the [issue134 directory](https://github.com/sanskrit-lexicon/MWS/tree/master/mwauthorities/ls/issue134).

Changes in two parts:
* `<ls n="RV.">vi, 62, 7</ls>; ` type -- this is the 'cyu' example mentioned in the opening comment of this issue
   * about 260 lines changed . See the change_1.txt file 
   * see abnormal_noref_RV.txt for cases that remain unresolved.
* General cleanup of ls markup, inspired by @Andhrabharati comment above. Basically, tried to resolve all `<ls>X`  where X is not a literary source reference abbreviation.  2500+ lines changed.  The sequence of changes listed in the readme.txt and change_2.txt file.
   * No attempt yet to deal with all the `<ls>ib.</ls>`.  There are pitfalls to programmatic identification of the appropriate 'preceding' ls abbreviation.  
   * Some cases were handled, those which had appeared with a space after ib. The section of
      change_2.txt at 'temp_change_lspunct_9.txt' handles some of these, and the rest were handled
      in previous sections of change_2.txt.
   * A small number of records (currently 10) have the markup `<ls n="Unknown">X</ls>`.

There are still many improvements to be made.  For instance 
```
876 matches in 874 lines for "<ls[^<]* and"
Example: <ls>Mn. ix, 49 and 51.</ls>
```
Further work on such cleanup will be documented in another issue.

**Comment by Andhrabharati** [comment]
@funderburkjim 

> see abnormal_noref_RV.txt for cases that remain unresolved.

Under `<L>62946<pc>344,3<k1>gadgadita`
`<ls>PāṇŚ.</ls> (<ls>RV.</ls>), <ls>35.</ls>` is the `<ls>PāṇŚ. 35.</ls>` in its `<ls>RV.</ls>` recension; it may be noted that the PāṇinīyaŚikṣā exists in many recensions!

![image](https://user-images.githubusercontent.com/75209130/177934625-72aada6f-bb0b-4f97-9fad-f5fa3d6d7a80.png)

The same applies to `<L>65326<pc>356,1<k1>gItin`, `<L>70575<pc>381,3<k1>cakrAhva` and `<L>91127<pc>473,1<k1>dazwa` cases as well.

**Comment by gasyoun** [comment]
> No attempt yet to deal with all the <ls>ib.</ls>. There are pitfalls to programmatic identification of the appropriate 'preceding' ls abbreviation.

@Andhrabharati have you ever tried to?

**Comment by Andhrabharati** [comment]
My works are not usable (being in a diff. format altogether)!

**Comment by funderburkjim** [comment]
Possible markup change:
```
OLD
<ls>PāṇŚ.</ls> (<ls>RV.</ls>), <ls>35.</ls>
NEW
<ls>PāṇŚ. (RV.) 35.</ls>

And new literary source
PāṇŚ. (RV.)    == PāṇinīyaŚikṣā, Rg Veda recension [Cologne addition]
```

Possibly useful for a link:
https://linguindic.com/data/browse/texts/16/

Only about 7 instances.
