### ISSUE TITLE
Normalized Lexical Information

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#14]
As already mentioned in https://github.com/sanskrit-lexicon/MWS/issues/13 I hope that after 6 years there will be a new (public?) edition of mapnorm-step1a.zip with even more explanations, and <a href="https://github.com/sanskrit-lexicon/MWS/blob/master/step1a-191-unique-entries.txt">191 specific cases</a> solved. Most of all I'm interested in key2 and pure, unmixed data in the normalized column.

![step](https://cloud.githubusercontent.com/assets/80761/4516894/2bfd08a0-4c10-11e4-9af1-5eb6eabb7c3d.jpg)

**Comment by drdhaval2785** [comment]
As it is tracked in MWlexnorm repository, this can be closed.

**Comment by Andhrabharati** [comment]
@funderburkjim / @gasyoun,

Is this issue closable now?

**Comment by funderburkjim** [comment]
Will concur with Dhaval's comment, and close this.
