### ISSUE TITLE
MWS accent correction, continue phase 3

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#142]
In #141, the last comments pertained began what was called *phase 3*.  This is a page-by-page, column-by-column comparison of the scanned images with the cologne digitization of mw.txt.  This comparison focuses primarily on the accents in the metaline and headline portion (before the broken bar) of the digitization.

This issue continues that task.

**Comment by funderburkjim** [comment]
Recall from #141, that changes for page 1-59 are in [issue141/change_mw_6.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue141/change_mw_6.txt), of 10-17-2022.

The current work is done in [mwissues/issue142 directory](https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue142),.

This table is a log of progress.
|date|page range|change-file|
|---|---|---|
|10-17-2022|0001-0059|[issue141/change_mw_6.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue141/change_mw_6.txt)|
|10-20-2022|0060-0130|[change_mw_01.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue142/change_mw_01.txt)|

**Comment by Andhrabharati** [comment]
So far about 48800 changes in 499 pages, i.e. almost 100/page on average.

Guess @funderburkjim feels this exercise is worthy enough of his time, and would be alloting further time to continue the work in the remaing pages.

**Comment by funderburkjim** [comment]
Yes, currently at page 617.  Almost half-way. Probably 5-7 weeks to end (about 20 pages/day).

**Comment by Andhrabharati** [comment]
Today's correction file (06) is dated as 20th, not 12th, by error.

**Comment by gasyoun** [comment]
> Probably 5-7 weeks to end

So until end of 2022. When should we plan for our yearly call? Right after?

**Comment by Andhrabharati** [comment]
@funderburkjim 

You forgot to add the last commit (1100-1199) in the 'progress log table' above.

Also pl. see my post at https://github.com/sanskrit-lexicon/SKD/issues/16#issuecomment-1355955825 reg. the annexure pages.

Hope you would be finishing this commendable task before this Christmas; this indeed is the most worthy exercise (in my view) in the last 25 + years of MW work at CDSL.

**Comment by funderburkjim** [comment]
Updated progress log table.  Thanks for mentioning.

**Comment by funderburkjim** [comment]
Regarding annexure pages accent review, I was hoping you would cover that when I finish the body text accent review.

However, if you decide not to do that, then I will consider it later.

**Comment by Andhrabharati** [comment]
Sure, I can resume my unfinished task (referred above) once you're done with your work and give me the updated iast file.

**Comment by gasyoun** [comment]
> Sure, I can resume my unfinished task (referred above) once you're done with your work and give me the updated iast file.

Good to know.

**Comment by funderburkjim** [comment]
## two accents.

There are a relatively few cases where an entry headword is marked with two accents.
[two_accents.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue142/two_accents.txt) is the current list of 177.

These should be reviewed manually sometime.

**Comment by funderburkjim** [comment]
## a few extra 

Based on notes made during the accent review, several additional entries were reviewed.
Some entries were changed,  some were identified as open questions, and some were identified as no change required.
The commit above (b42..) can be used to review the changes.
[readme_extra.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue142/readme_extra.txt) may be consulted.

**Comment by gasyoun** [comment]
> Review ends at page 1308.

I bow to the way you deal with issues.

> [two_accents.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue142/two_accents.txt) is the current list of 177.

`agnī/-va/ruṇau` should be read as `agnī́-varuṇau` and `agnī-váruṇau` or `agnī́-váruṇau`

**Comment by Andhrabharati** [comment]
@funderburkjim hasn't made room for my stepping in, @gasyoun ; he wants to do something still (look at his prev.  post).

**Comment by funderburkjim** [comment]
A crude statistic shows that the primary difference between the  original  and final versions of MW in this exercise
is due to removal of 'inherited' accents in compounds.    

```
$ grep -E "<k2>[^<]*[\/^]" temp_mw_00.txt | wc -l
107142
(- 107142 48852) = 58290


<e>[34]  are, roughly, the compounds.
$ grep -E "<k2>[^<]*[\/^].*?<e>[34]" temp_mw_00.txt | wc -l
73303

$ grep -E "<k2>[^<]*[\/^].*?<e>[34]" temp_mw_extra.txt | wc -l
15001

(- 73303 15001) = 58302
```

**Comment by gasyoun** [comment]
> due to removal of 'inherited' accents in compounds

15001 changes?

**Comment by funderburkjim** [comment]
See revision of comment above.  Roughly 58000+ metalines changed.

**Comment by funderburkjim** [comment]
Closing this issue.  
#145 continues this review.

**Comment by Andhrabharati** [comment]
> > [two_accents.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue142/two_accents.txt) is the current list of 177.
> 
> `agnī/-va/ruṇau` should be read as `agnī́-varuṇau` and `agnī-váruṇau` or `agnī́-váruṇau`
> 
> > The commit above (b42..) can be used to review the changes.
> 
> @Andhrabharati would you be willing to look at the 200 lines?

@gasyoun 

See what pwk says on this word--

![image](https://user-images.githubusercontent.com/75209130/209045315-bc2eddb2-6729-4a36-9383-e9455f63f15a.png)


@funderburkjim 

I would again request you to make a page like https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/pwkvn/03/ (option 3 of https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/pwkvn/03/), for MW, PWG and pwk+pwkvn; this definitely would be helpful to easily track such queries, as MW is heavily depending on those two works.

**Comment by funderburkjim** [comment]
Such a display with MW  is not as easy as the pwkvn/03/ page,  because there are differences in spelling conventions between MW and Boehtlingk.   e.g. kar (pw) vs kf (mw) [slp1 spelling of root 'to do'].  Without handling these spelling differences,  the pwkvn/03 display could be adapted, but would sometimes stumble.  
Another approach is https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/sample/dalglob1.php.
This handles the spelling differences well, but is visually less useful.

So getting a perfected display is non-trivial.

My solution when working with the mw accents and consulting occasionally pw or pwg has been to
open  the simple-search list displays (input=slp1) in two tabs (one for pw, one for mw), and open servepdf (for mw) in a third tab (or these views could be opened in separate windows),  This configuration makes it fairly easy to consult PW when necessary .  This setup can be facilitated in windows-11 using a collection.

**Comment by gasyoun** [comment]
> MW, PWG and pwk+pwkvn; this definitely would be helpful to easily track such queries, as MW is heavily depending on those two works.

@funderburkjim kar (pw) vs kf (mw) - with the acceneted words it will not become an issue at all. @Andhrabharati is not asking for a universal tool for all cases. 

> Another approach is https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/sample/dalglob1.php.

Yeah, it's not even reachable from homepage. Hope it can get some love in 2023.

> two tabs (one for pw, one for mw), and open servepdf (for mw) in a third tab (or these views could be opened in separate windows)

Three open tabs is 2 tabs too much for me.

> See what pwk says on this word--

Thanks, so the last one. Is it still a single `pada`?

**Comment by Andhrabharati** [comment]
> Thanks, so the last one. Is it still a single `pada`?

yes, it is a dvandvasamAsa.

**Comment by Andhrabharati** [comment]
> > it is a dvandvasamAsa
> 
> But why only a small part of them have two accents at once? Archaic ones?

Almost every dual form that I came across is with double accent; just wait till I finish reading through the MW entries.
