### ISSUE TITLE
Should Ramayana links in MW be pointed to the Schlegel ed. for 1st & 2nd Kandas (as in PWG)?

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#151]
@funderburkjim 

Just by chance, seen the` R. i, 34, 16` link at the entry "amara" and noted that it is linked to the Gorresio ed. which does not contain the referred word "amarī" at all!
![image](https://user-images.githubusercontent.com/75209130/213978141-6f8ca99e-2ae2-4002-b305-c3cdb8359464.png)

Then checked with PWG and seen that it is linked to the Schlegel ed., which does contain the word "amarī".
![image](https://user-images.githubusercontent.com/75209130/213978303-3bd042ec-43e9-482a-b342-66bd3066470e.png)

I guess, MW links to `R. i, xx, yy` & `R. ii, xx, yy` should also be linked to the Schlegel ed. (as in PWG).

**Comment by Andhrabharati** [comment]
Reason being, MW has took the citations "as is" from the PW set (PWG and pwk), at almost all the places.

**Comment by gasyoun** [comment]
> MW has took the citations "as is" from the PW set (PWG and pwk), at almost all the places.

Yet another proof for a copycat. @funderburkjim agree!

**Comment by Andhrabharati** [comment]
@funderburkjim 

Wold you glance this once, and take action please?

**Comment by funderburkjim** [comment]
> MW links to R. i, xx, yy & R. ii, xx, yy should also be linked to the Schlegel ed. (as in PWG).

Request noted.

**Comment by funderburkjim** [comment]
## done
See the above commits for the change.

mw links to Kanda i (example amara as above)  Schlegel edition
mw links to Kanda ii (example anuraTyA)  Schlegel edition
mw links to other Kandas (example apASraya) Gorresio edition
