### ISSUE TITLE
Should the <ls>Gr.</ls> link to Monier Williams's own Grammar book, instead of Whitney's Grammar?

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#152]
Under the HW eka (`<L>39168`), noticed  this-- `<ls>Gr. 200</ls>`

The **Practical Grammar of the Sanskrit Language** (Monier Williams) has this under article 200--

![image](https://user-images.githubusercontent.com/75209130/216274114-bf6002ed-300a-47f9-b19f-ad4037b141ee.png)

And, Whitney's **Sanskrit Grammar** has the article 200 thus--

![image](https://user-images.githubusercontent.com/75209130/216273427-12187bb0-ef9f-4f2c-b7ca-e5957a269ad5.png)

**Comment by gasyoun** [comment]
Seems you are right again.

**Comment by Andhrabharati** [comment]
Only at 3 places [`<L>13538, <L>19472 and <L>37975`], Whitney's Grammar is specifically mentioned.

**Comment by funderburkjim** [comment]
There are 11 cases of `<ls>Gr.`.  See [extract_gr.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue152/extract_gr.txt).

In 9 of these, a specific article number is given.  These specific articles were examined in MW's
`Practical Grammar Of The Sanskrit Language  Ed. 4`  ([archive.org ref](https://archive.org/details/in.ernet.dli.2015.195884/page/n131/mode/2up)).

And all matched.  This further confirms that `<ls>Gr.` should ref to the Monier-Williams Grammar.

Regarding the two instances with no specific article number.  These are verb forms of 'nam' and 'Baj'.

Note there are 969 matches in 833 lines for `<ab>Gr\.</ab>`.  CDSL tooltip for abbreviation `Gr.` in mw is
`grammar, esp. Whitney’s Sanskrit Grammar`.   
I think the two `<ls>Gr.</ls>` should change to 'ab'.

Changes to make:
* change the two `<ls>Gr.</ls>`  to `<ab>Gr.</ab>` in mw.txt
* Change the ls tooltip for `<ls>Gr.` to  
   `Practical Grammar Of The Sanskrit Language  Ed. 4, Monier-Williams, 1877`

Will make these changes now.

**Comment by Andhrabharati** [comment]
I guess, the ab tooltip also has to be changed to MW's Grammar.

If it is Whitney, it would have been specifically mentioned thus, as at the 3 places mentioned above.

**Comment by Andhrabharati** [comment]
And, your extract (with the ending info tags included) reminds me of a point I had noted down to ask sometime--

how are the below entries taken as "genuine root"?
`<s>iṣhūya</s> [<L>29546]`
`<s>makamakāya</s> [<L>153911]`

**Comment by funderburkjim** [comment]
I am doubtful of changing the ab tooltip to MW's Grammar.
In the MW list of (general) Abbreviations, 'Gr.` means 'Grammar' (not very helpful)

![image](https://user-images.githubusercontent.com/6393033/217674775-445609a4-62cc-4da0-ab8f-323ab0410eef.png)

Yet I have an (unclear) memory that somewhere (probably in front matter of MW),  the author says this Gr. usually refers to Whitney's grammar.

**Comment by funderburkjim** [comment]
Currentlly, the tooltip for `<ab>Gr.</ab>` is
`grammar, esp. Whitney’s Sanskrit Grammar`

**Comment by funderburkjim** [comment]
Changing tooltip for `<ab>Gr.</ab>` to `Grammar.`.

At least this will agree with the author's Abbreviation for Gr.

**Comment by funderburkjim** [comment]
The above changes made.
I think this issue can be closed now.
