### ISSUE TITLE
Greek text review

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#153]
This is a placeholder issue.
In another issue (https://github.com/sanskrit-lexicon/BEN/issues/8), @Andhrabharati points out the need, for mw.txt, to 
* proofread the Greek text  - as some errors noticed incidentally.  There are about 1100 instances to review
* add Greek text -- some is missing in current mw.txt of cdsl.

When the time is right for review of mw.txt, further comments will be made here.

**Comment by Andhrabharati** [comment]
I already did the proofing of all greek and other languages' (cognate) strings. And filled up various missings at those places in all the languages.

Also made some better markups for these in my current review work.

**Comment by funderburkjim** [comment]
@Andhrabharati   How should we proceed in order to apply your corrections to cdsl mw.txt?

**Comment by Andhrabharati** [comment]
I shall post the existing lines vs. my corrected lines, explaining how I changed few markings at those places.

Then it should be easy for you to apply the corrections in the cdsl file, even if not going to change the markings (as per my proposal).

**Comment by Andhrabharati** [comment]
Only issue I see is that I had removed all the duplicate entries in my working, so you need to "look" for them in cdsl file to repeat the corrections.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Here is the file with details for quick browsing --
[lang string changes.pdf](https://github.com/sanskrit-lexicon/MWS/files/10677887/lang.string.changes.pdf)

And the summary is --
NO Error lines | 584
Greek related error lines | 91
Other lang. related error lines | 168
Misc. error lines | 441

I tried making a .tsv file with individual error types (at gist.github.com), as you suggested sometime back on a different context --
https://gist.github.com/Andhrabharati/e82889769929d74df0fe35050d734504

**Comment by Andhrabharati** [comment]
@funderburkjim 

Pl. have a look at https://github.com/sanskrit-lexicon/mw-dev/issues/7#issue-1576531888

**Comment by Andhrabharati** [comment]
@funderburkjim 

I just added some explanation on the topic at https://github.com/sanskrit-lexicon/mw-dev/issues/21#issue-1587358520

Hope you'd be taking up the corrections in the existing cdsl text itself (under v02), from various issues I am posting under mw-dev, as much as possible/applicable.

**Comment by funderburkjim** [comment]
Re [lang string changes.pdf](https://github.com/sanskrit-lexicon/MWS/files/10677887/lang.string.changes.pdf)

@Andhrabharati Do you have a way to prepare a text file of this pdf?
Reason:  Using Acrobat 9, the file is quite easy to read, but not to process with programs.  A text file (with UTF-8) coding for non-ASCII characters) would be useful, I think.  This would allow me to apply corrections.  I've tried 'export' to text file with Acrobat, but with no useful results.

**Comment by Andhrabharati** [comment]
@funderburkjim 

I have already posted the text file at mw-dev repo and mentioned the same above at https://github.com/sanskrit-lexicon/MWS/issues/153#issuecomment-1422992114; it might've skipped your notice!!

**Comment by funderburkjim** [comment]
@Andhrabharati  Just found what appears to be text file version i(lang.string.changes.txt) at #7.
So I think you can ignore prior request.

**Comment by Andhrabharati** [comment]
And I hope you've seen this https://github.com/sanskrit-lexicon/MWS/issues/153#issuecomment-1418239936

**Comment by funderburkjim** [comment]
Yes. We can use the fact that you are, thus far, retaining the line-number correspondence between mw_AB.txt and mw.txt.

**Comment by funderburkjim** [comment]
## question two similar characters

There are two visually similar Greek characters which appear in mw.txt digitization.
See [unicode_gk_o_out.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue153/unicode_gk_o_out.txt).

@Andhrabharati  suggest we change the 'OXIA  1f79' (3 times) to 'TONOS 03cc'  (171 times).

Agree?

**Comment by Andhrabharati** [comment]
I guess not, @funderburkjim !

See what @jmigliori was saying about the oxia and tonos two years back at https://github.com/sanskrit-lexicon/MWS/issues/89#issuecomment-753634001

**Comment by Andhrabharati** [comment]
Probably, all the TONOS occurrences may need to be changed to OXIA.

**Comment by funderburkjim** [comment]
If we (reasonably) assume that the Greek text in MW is from ancient Greek, and
that OXIA is likely in Ancient Greek,
Then always using OXIA in mw.txt seems right.

@jmigliori   Agree?

**Comment by jmigliori** [comment]
Yes, that’s my understanding

**Comment by funderburkjim** [comment]
@jmigliori   Hi! Thanks for immediate reply.  

@Andhrabharati  I'll go ahead with changing the omicron-tonos to omicron-oxia in cdsl mw.txt.

**Comment by Andhrabharati** [comment]
@funderburkjim 

The TONOS to OXIA change should cover **all the letters**, I feel.

ά > ά
έ > έ
ή > ή
ί > ί
ύ > ύ
ώ > ώ

Wherever I seem to have typed the character, the OXIA has been used (as I had made my own keystrokes using autohotkey, using the ancient greek alphabet), and the earlier typed accent seems to be TONOS only.

**Comment by Andhrabharati** [comment]
And probably this applies to all across cdsl repos, as they all are 19th century dictionaries, which are 'ancient'!!

**Comment by funderburkjim** [comment]
[tonos_oxia.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue153/tonos_oxia.txt) shows counts of greek text characters in mw with either 'tonos' or 'oxia' in the unicode name.

One additional 'tonos' character found.
`1 ΐ 0390 GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS`
This also has an 'oxia' version
ΐ 1fd3 Greek Small Letter Iota with Dialytika and Oxia

**Comment by gasyoun** [comment]
I love how @Andhrabharati is starting to cooperate and not only telling how wrong we are. I'm his fan.

**Comment by funderburkjim** [comment]
## lang.string.changes use completed.
The changes to Greek (including 'oxia') have been installed into (cdsl) mw.txt.
Numerous other non-Greek improvements also made based on lang.string.changes file.

[changes.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue153/changes.txt) has all  the lines changed in mw.txt. (711).

Note that the use of `<lang>X</lang>` has not been followed in cdsl mw.txt.

That's enough for this issue. Closing issue.

**Comment by Andhrabharati** [comment]
@funderburkjim

I wonder why the point that this issue has started with https://github.com/sanskrit-lexicon/BEN/issues/8#issuecomment-1418030666 is not 'attended to'.
Just looked for φ and found 18 of them still; I thought there are NONE such in the MW99 print.
[And I did not feel like checking any further.]

**Comment by Andhrabharati** [comment]
Need to see, if they are not listed in my file above. [My present working file has none such.]

Anyway, these corrections (at least) are good enough for now in the current CDSL file.

**Comment by funderburkjim** [comment]
There seem to be two kinds of phi character:
```
     φ 03c6 GREEK SMALL LETTER PHI
     ϕ 03d5 GREEK PHI SYMBOL
```
As I understand it, you prefer to use the '03d5 GREEK PHI SYMBOL' character everywhere.  Right?

**Comment by funderburkjim** [comment]
There is something odd going on in the display of these characters.
For example, in this browser the above comment looks like
<img width="236" alt="image" src="https://user-images.githubusercontent.com/6393033/220438296-8fb97112-f489-43d9-b3b1-de0a211bf9b0.png">

BUT, if  I edit the above comment, the display of the two characters switches:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/6393033/220438555-078d0a13-34e5-463c-9eed-cf0355356d7a.png">

**Comment by Andhrabharati** [comment]
I have no preferences; just looked at what the print has.

It is not out of context to mention that different works used different variants of letters (print style vs. script style) [(φ > ϕ) : MW99; (κ > ϰ) : BUR and (β > ϐ) :BEN].

**Comment by funderburkjim** [comment]
In print kapAla, p. 250,2 of mw
<img width="623" alt="image" src="https://user-images.githubusercontent.com/6393033/220440451-3647dc89-ab9d-4f12-8f87-5cda47e51677.png">

Do all the 'phi' characters in MW look the same?

**Comment by Andhrabharati** [comment]
Your above post made me look at my file to note that  `<s>gabhaim</s>` is not changed to `<etym>gabhaim</etym>` under `<ab>Hib.</ab>`

![image](https://user-images.githubusercontent.com/75209130/220443067-d23033d0-a97b-4405-a78c-e1321eeb890f.png)

**Comment by funderburkjim** [comment]
This Hib. change should be made of course.   But I obviously missed it in my study of the lang.string file.
If you have a way to discover others that I missed, please provide the items and I'll incorporate into cdsl m2.txt

**Comment by funderburkjim** [comment]
So there is still another font issue.  Ugh! I am having a similar 'same glyph' issue with Emacs for the two phis.

**Comment by Andhrabharati** [comment]
I have noticed more such errors in this font; but that's a different matter altogether.

**Comment by funderburkjim** [comment]
Repeat question:  Should all the mw instances of phi be rendered as `φ 03c6 GREEK SMALL LETTER PHI`  ?

**Comment by funderburkjim** [comment]
I currently count, for the two phis,
```
72 matches in 55 lines for "ϕ" in buffer: temp_mw_5.txt
15 matches in 14 lines for "φ" in buffer: temp_mw_5.txt
```

Should I change all those 72 to 03c6  ϕ" ?

**Comment by Andhrabharati** [comment]
As I mentioned above, the web users would not notice the difference (as there no way to change the font at client side); but this is not the letter in MW print, as you yourself have posted a snippet above with the actual letter there.

**Comment by funderburkjim** [comment]
I'll make that change to 03c6 ϕ

We could introduce another web-font for the displays to be used just for the Greek text.

Any suggestions for such a font?

**Comment by funderburkjim** [comment]
The remaining  'small letter phi' changed to 'phi symbol'
See [change_6.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue153/change_6.txt).

Note: In my windows 11 pc,  this change_6.txt file displays the characters wrong;  it is using the Consolas Font (Windows monospace default font).  It is possible to use developer tools to (temporarily) edit the font-family properties of the greek text not to use monospace -- then Segoe UI font is used, which displays the two phis correctly.

The 'Microsoft Sans Serif' font displays these two phi characters correctly, but it is not a monospace font.

**Comment by funderburkjim** [comment]
The 'kapAla' correction also made.

> Just note that 03c6 is not ϕ.

Right - I have been tossed around on the waves of font 'errors', and also by 
 https://www.compart.com/en/unicode/U+03C6  

<img width="723" alt="image" src="https://user-images.githubusercontent.com/6393033/220489071-94dfc1f9-f501-4a69-b08b-d9d8112b5217.png">

and https://www.compart.com/en/unicode/U+03D5

<img width="727" alt="image" src="https://user-images.githubusercontent.com/6393033/220489225-29f4525d-3e0f-490c-b1b9-3ad25afebe85.png">


The reference https://www.unicode.org/charts/PDF/U0370.pdf  (mentioned by AB above) is thought to be correct:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/6393033/220489437-1abd3fa7-7355-4939-9348-2ea8a9de34b4.png">

The fileformat website (e.g. https://www.fileformat.info/info/unicode/char/03d5/index.htm)
is also believed to be correct in this detail.

**Comment by funderburkjim** [comment]
I dare to close this issue once again!  Will it stay closed?

**Comment by funderburkjim** [comment]
Have I missed anything that needs doing with mw and drawn from the Benfey link mentioned in first comment?

**Comment by Andhrabharati** [comment]
> I dare to close this issue once again! Will it stay closed?

Though I did not want to spend more time, a 2nd thought forced me to look at the (corrected) mw.txt and the mw_AB.txt again.

Found good many changes that were 'left/missed', both in Greek portions and the rest (**esp. wrt diacs and hyphenation**) [even if ignoring the Indic language words, for whatever reason]!!

As Jim mostly seemed to be not that serious about the other languages portion, just posting the Greek portion
[AB vs. CDSL greek text differences.txt](https://github.com/sanskrit-lexicon/MWS/files/10801427/AB.vs.CDSL.greek.text.differences.txt)

**Comment by Andhrabharati** [comment]
> If you have a way to discover others that I missed

I just extracted (from CDSL file and AB file) the greek strings set & the etym strings set and did a comparison between them, to yield the differences. [It was only a few minutes' effort!!]

**Comment by Andhrabharati** [comment]
Just listing various types of corrections in non-greek portion that got 'left/missed', whatever worth it has--

- Misc. corrections (89)
- Un-tagged words (10)
- Diacritic separately marked (60)
- Hyphenations (6)
- `<etym>` to `<s>` and vice-versa (30)
- non-Skt. Indic words (?)

**Comment by Andhrabharati** [comment]
> If you have a way to discover others that I missed, please provide the items and I'll incorporate

@funderburkjim 

If you look for "Wrong Tag" in my above file, you'd get all those `<etym> to <s> and vice-versa` words; it appears that you had missed quite many in my file (for unknown reasons).

As I have made a new file (yesterday) with easier usability, I could post that file if you're still "interested" in this issue.

**Comment by funderburkjim** [comment]
## 25 more greek corrections
corrections from AB.vs.CDSL.greek.text.differences.txt.
See [change_7.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue153/change_7.txt).

At least some of these were missed in earlier work above because not mentioned as 'Greek' in lang.string.changes.txt file.
For instance δολιχός occurs in line labeled '(313553): Others [Spelling Error]'.
Glad you took the time to help correct these omissions.

@Andhrabharati I would like to address additional corrections you mention at [comment above](https://github.com/sanskrit-lexicon/MWS/issues/153#issuecomment-1440619432).

I'll start with the `<etym><s>` items.

If you have an easy way to identify these, please post.

**Comment by Andhrabharati** [comment]
Glad that you're still on this issue, @funderburkjim !

Here is the file I made for CDSL corrections, which has the entries in opp. order [CDSL > AB] (wrt the Greek corrections file)--
[CDSL_cognates corrections.txt](https://github.com/sanskrit-lexicon/MWS/files/10816946/CDSL_cognates.corrections.txt)


And, if you are willing to mark the other (mostly Indic, and few English) cognates, they can be seen in this addl. cognates file--
[AB_addl. cognates.txt](https://github.com/sanskrit-lexicon/MWS/files/10816954/AB_addl.cognates.txt)

**Comment by funderburkjim** [comment]
@Andhrabharati  Question regarding the '(60) Diacritic separately marked` in CDSL_cognates_corrections.

I am not finding the 2nd form in mw_AB.txt.  For instance, the first one
```
>atrúgas<	>atrúgas<   
The only difference is that the combining accent is used in first (CDSL) and 
second (AB) uses a pre-formed u-accent.

Only the CDSL form occurs in mw_AB.txt.
```
If you intend to use combining accent, then the 60 items of CDSL_cognates_corrections should be ignored.
Agree?

Note:
CDSL uses *etym* tag, and AB uses 'cog' tag.   This is another difference,
but I am uniformly not changing the tag in cdsl, as I think you are aware.

**Comment by Andhrabharati** [comment]
No, I intend to use the pre-formed letters in the non-Indic words (European etc.); you might notice this in the other changes that I had done and you had already incorporated.

See, for e.g. `<ab>Lith.</ab> <etym>verz-iù</etym>` in line 134478 in the prev. corrections you listed in [changes.txt](https://github.com/sanskrit-lexicon/MWS/issues/153#issuecomment-1438908745) above.

And this is what I see, wrt the word you are referring to--

CDSL-column
![image](https://user-images.githubusercontent.com/75209130/221331045-a377f33f-eec7-4682-aae5-2b7e3d3e7acb.png)

vs.

AB-column
![image](https://user-images.githubusercontent.com/75209130/221331068-5c1687be-05ef-499f-b239-a4928ec147ad.png)

showing the composition of the letter ù in CDSL column and AB columns.

[As I had mentioned somewhere else recently, I did not post the later updates of mw_AB.txt yet.
The mw_AB.txt file you are looking at is 'out-dated' now!!]

**Comment by Andhrabharati** [comment]
> Note:\nCDSL uses etym tag, and AB uses 'cog' tag. This is another difference,\nbut I am uniformly not changing the etym tag in cdsl, as I think you are aware.

Yes, I see that you did not change these tags; but the etym. [see WIL having it as 82Sper traditional sanskrit norms] and cog. [which is what MW intended (he also used the "etym." term in the lines of WIL when talking about the 'formation/derivation' of the Skt.words) are entirely different.

AND, as I mentioned before I had started the full review of mw.txt, I am trying to bring-in 'meaningful' (and better forms of the) tags into my working file.

**Comment by funderburkjim** [comment]
## Corrections based on cognate files
[change_8.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue153/change_8.txt)  has the corrections.
These are my 'handling' of correction suggestions from 
* AB.CDSL_cognates.corrections.txt
* AB_addl.cognates.txt.

change_8 is divided into sections, with titles 'temp_'

`722856 old <s>SiNGinI</s> ¦ [<ab>cf.</ab> <ab>Germ.</ab> <etym>Zinken</etym>]`
This may be a steganographic entry that @maltenth inserted.  I will ask him.

AB's use of non-cdsl markup (such as `<lang>` with no attribute, `<cog>`, and several more)  is based on his interpretation of the author's intent.  It is likely that this markup is, for some purposes, preferable to that in current cdsl for mw.
This will be one way that we hope mw_AB.txt will improve the cdsl mw.txt.

In the course of making this markup, AB is also noticing many items that should be considered errors even in the cdsl version.  
I am aiming to make corrections in cdsl.  
Hopefully I have accurately made the needed corrections from the two cognate files.

**Comment by Andhrabharati** [comment]
> Hopefully I have accurately made the needed corrections from the two cognate files.

![image](https://user-images.githubusercontent.com/75209130/221397917-01069639-c34c-498b-8f8b-53cd5efa6cc9.png)

See what I had mentioned in my file [`>nose-hole<	nose-hole ;; it's the meaning, not a cognate.`]; and observe the words in italic (cognate) and normal (meaning) in the image above.

Glad that @funderburkjim decided to do almost all the corrections I had listed.

**Comment by gasyoun** [comment]
> [>nose-hole<	nose-hole ;; it's the meaning, not a cognate.]

@Andhrabharati indeed! As for now we have he meanings and words intermixed.

**Comment by funderburkjim** [comment]
> `722856 old <s>SiNGinI</s> ¦ [<ab>cf.</ab> <ab>Germ.</ab> <etym>Zinken</etym>]`

This confirmed by @maltenth to be steganographic text.

Thomas has an interest in identifying websites that use the Cologne digitizations (especially mw) *without acknowledgment*.   One way to do this is to introduce extra text in several  obscure places. The presence of such extra text in  a website's rendition of Monier-Williams dictionary provides one proof that the website is based on Cologne digitization.  

In deference to Thomas, we should keep such steganographic errors in the digitizations.

@Andhrabharati  Please re-insert the above steganographic text in mw_AB.txt.  If other 'out of the blue' text is noticed,  we can ask Thomas if it is in his list of such, and (if so) keep it in mw_AB.txt.

**Comment by funderburkjim** [comment]
Removed `etym` tag from 'nose-hole'  per comment above.

**Comment by funderburkjim** [comment]
Closing this issue once again. Will it remain closed?

**Comment by Andhrabharati** [comment]
> This confirmed by @maltenth to be steganographic text.

> In deference to Thomas, we should keep such steganographic errors in the digitizations.

> @Andhrabharati Please re-insert the above steganographic text in mw_AB.txt.

Done!

**Comment by funderburkjim** [comment]
Thanks!  

If you find other 'out of the blue' text,  make a private note (don't post to github or elsewhere on internet) and communicate with me via email -- I'll check with @maltenth .

**Comment by gasyoun** [comment]
> In deference to Thomas, we should keep such steganographic errors in the digitizations.

Not sure it will be enough to recognize all of them, but at least we can try to.
