### ISSUE TITLE
Advanced search vs. Simple search results

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#157]
This is the first time that I tried the simple search, as @gasyoun "highly recommends" it & @funderburkjim also "supports" the same [as understood from various posts at Github] against the Adv. search.

And here is what I stumbled upon!!

Adv. search--

![image](https://user-images.githubusercontent.com/75209130/225642923-d5cbaae3-49ba-4880-8e74-10139b7a6ac2.png)

Simple search--

![image](https://user-images.githubusercontent.com/75209130/225645795-0b426fc3-68bf-4602-a419-ab323d4e1654.png)

Did I err somewhere or is something wrong at CDSL?

**Comment by funderburkjim** [comment]
Looks like something is wrong at Cologne.  
Entering 'gha' works -- maybe words with IAST diacritics are not handled properly with iast input.

**Comment by funderburkjim** [comment]
Marcis typically likes to use the `input = simple` option.
This brings up another menu 'input_simple'.  
In the first example, I choose 'iast' for the 'input_simple' choice.  
This works properly.
<img width="734" alt="image" src="https://user-images.githubusercontent.com/6393033/225711581-38d1a85b-7374-42f7-8e39-2cf1e6f3ce19.png">

Marcis typically (I think) uses the 'default' option for input_simple.  This also works,
but gives other possibilities besides the citation.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/6393033/225712036-f087e636-0bae-4c6a-ae8a-43d89dbed263.png">

One nice aspect is that the user does not need to know exact spelling. e.g.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/6393033/225712682-c72afe98-7c54-4db7-bb77-685033ae2a64.png">

**Comment by funderburkjim** [comment]
This problem *seems* to be solved now.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/6393033/225807870-ce6b48a2-f723-4b56-a422-3cd493412032.png">

Suggest to 
* 'Ctrl-F5' so latest code is being used.
* 'view page source'. search for 'version' -- it should show `<!-- simple-search version 1.1 -->`


I don't really understand why this works.  A '400 Bad request' error is hard to investigate because there is no obvious way to find the bad url.

**Comment by funderburkjim** [comment]
One oddity is that the program (before change) worked fine with local xampp installation.  And the local xampp installation also works fine after the change.

Also, Devanagari input worked fine before the change and after the change, both at Cologne and in local xampp installation.

Have you ever walked on thin ice?

**Comment by gasyoun** [comment]
> Have you ever walked on thin ice?

Has @Andhrabharati seen ice?

**Comment by Andhrabharati** [comment]
The reported problem has been 'corrected' and the issue is closable.
