### ISSUE TITLE
Whitney Roots twice? 34.37 case

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#158]
![34 37](https://github.com/sanskrit-lexicon/MWS/assets/80761/714e2fcb-437b-4186-9bfa-c459ce24c43e)

@funderburkjim is not twice too much?

**Comment by funderburkjim** [comment]
Removed duplicate Westergaard reference in mw.txt
```
OLD :  <info westergaard="BU,1.1,01.0001;BU,34.37,10.0235;BU,34.37,10.0235"/>
NEW :  <info westergaard="BU,1.1,01.0001;BU,34.37,10.0235"/>
```

<img width="355" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/2c238e8e-388e-48f1-91d9-fea4ff72d373">
