### ISSUE TITLE
śiva's bow -> Śiva's bow

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#16]
@funderburkjim not the first time, but let me raise it for the last time. If I search for `ajakAva` I will get `(H2B) ajakāva [p= 9,3] [L=2041]    mn. śiva's bow L.` in IAST mode, that is not equal to book scan. No easy way to leave the capital letters inside the text as they were in the printed book? Thanks.

![ajakava](https://cloud.githubusercontent.com/assets/80761/4637567/1c2b2340-53ee-11e4-8c74-4267f0691992.PNG)

**Comment by drdhaval2785** [comment]
Display and text both OK.

**Comment by gasyoun** [comment]
> Display and text both OK.

But no capital letters, @drdhaval2785

**Comment by drdhaval2785** [comment]
![image](https://user-images.githubusercontent.com/5755132/102019205-1c0efe00-3d98-11eb-82d8-becfadacc7f6.png)

To me it seems OK. It has capital

**Comment by drdhaval2785** [comment]
![Uploading Screenshot_20201213-230801_Chrome.jpg…]()

To me it seems OK

**Comment by drdhaval2785** [comment]
![Screenshot_20201213-230801_Chrome](https://user-images.githubusercontent.com/5755132/102019277-b53e1480-3d98-11eb-8ae8-adbba1c0c008.jpg)

To me it looks OK. It has capital. I checked.

**Comment by gasyoun** [comment]
> It has capital.

Capital is one of the meanings, but not the headwords itself.

**Comment by funderburkjim** [comment]
@gasyoun   Please show image with the problem identified. I also don't 
understand the problem you are noticing.
