### ISSUE TITLE
A strange error in display-code

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#160]
Just landed at this, by chance--

![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/a446283b-9048-4fa4-beb5-006c1a2beb73)

**What could be the fault, resulting in displaying the "hidden text"?**

**Comment by Andhrabharati** [comment]
Another error--

![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/dc8bd360-b419-4750-ad04-6e05e3ed558f)

Is this by any chance, a "by-product" (side-effect) of the recently introduced highlighting code?

**Comment by funderburkjim** [comment]
Yes, It does look related to the highlighting code.

**Comment by funderburkjim** [comment]
## Problem Solved

<img width="1025" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/c5ac2f18-98d8-449a-b8b4-3819b4497c75">

**Comment by funderburkjim** [comment]
Note I changed the highlight color to the one used by @neeleshb in  https://sanskritkosha.com/.

The solution is courtesy of Edge copilot.  Next comments provides the interaction with copilot.  I don't really understand all of that regex/

**Comment by funderburkjim** [comment]
This is a transcript of the copilot dialog.

[copilot_dialog_highlight.txt](https://gist.github.com/funderburkjim/d6d131dabd97935d19bfbbd9c2e47772)
