### ISSUE TITLE
सुषुप्स question

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#161]
User @aumsanskrit reported (by email) a probable error in mw under सुषुप्स.
I think this should be marked somehow as an error, but I'm not sure how to so mark it.

Using slp1 spelling.
There are 3 related headwords in MW:
* suzupsa --  this is the questionable one. It occurs as headword only in MW
  suṣupsa mfn. desirous of sleeping, sleepy, Suśr. ; Śiś. ; BhP.  [ID=250321]
* suzupsA -- appears in Apte 57 and several European dictionaries
  * in some dictionaries (but not MW), suzupsu is mentioned as the related adjective form
  * e.g. in MD: -su, des. a. sleepy.
* suzupsu -- appears in several European dictionaries
  * in MW, the suzupsu entry points to suzupsa (or maybe suzupsA)
  * in PWG: suṣupsu (wie eben) adj. zu schlafen verlangend, schläfrig Suśr. 1, 323, 9.  Śiś. 12, 52.  Bhāg. P. 3, 13, 30.  Bhaṭṭ. 8, 101.
    * cf. the references in MW under susupsa (above) -- Same as first 3 of PWG!
 
I found the Śiś. 12, 52. (SiSupAlavaDa) reference: https://archive.org/details/dli.bengal.10689.654/page/n439/mode/2up

<img width="1058" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/84fee46b-704d-40a4-87b2-d5c4948e7a26">

The usage is suzupsunA, (instrumental singular of suzupsu).

**Comment by funderburkjim** [comment]
The conclusion I draw is that MW fabricated 'suzupsa'.
Since there are no applicabe cdsl conventions, 
I propose:
* retain the  'suzupsa' entry 
* add some comment to the cdsl entry to indicate that this is likely wrong.

e.g.
```
old:
<s>suzupsa</s> ¦ <lex>mfn.</lex> desirous of sleeping, sleepy, 
<ls>Suśr.</ls>; <ls>Śiś.</ls>; <ls>BhP.</ls><info lex="m:f:n"/>
new:
<s>suzupsa</s> ¦ [SIC  <s>suzupsu</s>] <lex>mfn.</lex> desirous of sleeping, sleepy, 
<ls>Suśr.</ls>; <ls>Śiś.</ls>; <ls>BhP.</ls><info lex="m:f:n"/>
```

HELP WANTED!

**Comment by Andhrabharati** [comment]
> HELP WANTED!

This does not need so much of "extra thinking". It is just a **plain print error** in MW.

It is well known (mentioned by MW himself) that ~2/3rds of MW content is from MW72 [mostly as is, or slightly revised at times] (which is almost taken from PWG), and most of the remaining content is from **pwk**.

Here is what MW72 has (1162,1)--
![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/90671e3a-a37d-4a3f-813a-416551429f1e)

and compare with what MW has--

(1280,2)
![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/ff7cb283-7c0c-472b-9a6c-443f4c87b9d1)

and (1238,1)
![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/614de1af-8680-42d8-8e1e-0d9d2e0ce45b)

Though I can give all the "actual" citations from PWG (as I have all the sources), one given by Jim (even though its not the 'source' used by PWG) is sufficient enough for now.

**Comment by gasyoun** [comment]
> ~2/3rds of MW content is from MW72 [mostly as is, or slightly revised at times] (which is almost taken from PWG), and most of the remaining content is from pwk.

@Andhrabharati sharp analysis, as usual

**Comment by funderburkjim** [comment]
corrected to:
```
<L>250321<pc>1238,1<k1>suzupsu<k2>suzupsu<e>2
<s>suzupsu</s> ¦ <lex>mfn.</lex> desirous of sleeping, sleepy, 
<ls>Suśr.</ls>; <ls>Śiś.</ls>; <ls>BhP.</ls><info lex="m:f:n"/>
```
