### ISSUE TITLE
recoding shortlong

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#164]
Refer mentions of 'shortlong' at https://github.com/sanskrit-lexicon/csl-orig/issues/1639.

**Comment by funderburkjim** [comment]
All shortlong references 'expanded'.
[For details](https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue164).

the change_1, change_2 and change_3 files show the changes made to MW digitization.

**Comment by Andhrabharati** [comment]
Just gone through the shortest file change_3 and found 5 corrections!!--
[change_3 (AB remarks).txt](https://github.com/user-attachments/files/15860910/change_3.AB.remarks.txt)

It may be kept in mind that more often than not, the mw print has the long-short form, though it has been coded as <shortlong/> throughout the text (for ease). But, while expanding these as separate elements, we should try to follow the sequence/order of the print as much as possible.

**Comment by Andhrabharati** [comment]
Just recalled that this was mentioned in one of my [posts](https://github.com/sanskrit-lexicon/mw-dev/issues/4#issue-1549401986), while the revision was going on (last year).

**Comment by funderburkjim** [comment]
AB remarks processed.  change_4b.

[posts](https://github.com/sanskrit-lexicon/mw-dev/issues/4) suggestions also implemented.  change_5

More brief note re 4b and 5 in [readme](https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue164)

**Comment by funderburkjim** [comment]
I think this can be closed.
