### ISSUE TITLE
k1-k2 discrepancies

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#165]
At https://github.com/sanskrit-lexicon/csl-orig/issues/1638#issuecomment-2155866315, @Andhrabharati compiled a list of about 120 metalines of mw.txt where the k1 and k2 fields are inconsistent. 

This issue devoted to resolving those inconsistencies.

**Comment by funderburkjim** [comment]
Changes have now been made to resolve k1-k2 inconsistencies.
These changes can be seen in the csl-orig commits above.
Also consult the [issue165 directory](https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue165).

Closing this issue.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Found two corrections in this commit that need to be reverted--

- L-120206 change is not called for; it is to be "palāśá" only as mfn.

- L-247201 has to be "su-nu" only; see the nom. terminations at the prev. entry [<lex>m. f.</lex> |aus|, <lex>n.</lex> |u|], and also see its cross-referencing at L-247215.

**Comment by funderburkjim** [comment]
@Andhrabharati   Glad you're checking my work.  Two corrections implemented.
