### ISSUE TITLE
dot corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#166]
Develop corrections to mw at problematic points based on a list from @Andhrabharati  [see AB's comment](https://github.com/sanskrit-lexicon/csl-orig/issues/1645#issuecomment-2198054242).

**Comment by funderburkjim** [comment]
@Andhrabharati   These dot corrections now processed.

Details in https://github.com/sanskrit-lexicon/MWS/issues/166
Work directory: https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue166

the change_1.txt file has the changes made to prior version.

Note added several global abbreviations to mwab_input.
Also introduced several local abbreviations.

Found a duplicate entry to delete (203569) -- will delete this in a separate
csl-orig commit.

**Comment by Andhrabharati** [comment]
This issue may be closed now.
