### ISSUE TITLE
The accent saga continues

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#169]
Like the fabled phoenix rising from the ashes,  representation of accents in Sanskrit seems never complete in this cdsl dictionary project.

A previous extended discussion occurred in 2021, [here](https://github.com/sanskrit-lexicon/pwg/issues/5#issuecomment-895404247).

The latest resurrection appears [here](https://github.com/sanskrit-lexicon/MWS/issues/167#issuecomment-2202013048).

My attempts to put out the latest fires appear below.

**Comment by funderburkjim** [comment]
## Devanagari

In the 2021 work [specifically here](https://github.com/sanskrit-lexicon/pwg/issues/5#issuecomment-895404247),  a transcoding file [slp1_deva1.xml](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/utilities/transcoder/slp1_deva1.xml) was developed for devanagari displays to mimic the Boeghtlink system of accent representation.

The [getwordClass.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/webtc/getwordClass.php)  applies this transcoding froms slp1 to Devanagari (at about line 45 ff.):

```
   if (in_array($dict,array('PWG','PW','PWKVN')) && ($filter == 'deva') && ($getParms->accent == 'yes')) {
    // Causes display of udatta accent to be superscript Devanagari 'u'
    // As occurs in the print of these dictionaries. So slp1_deva1.xml is
    // used as the transcoder file.
    $filter = 'deva1';
   }
```

The simplest way to have the MW displays to mimic pw dictionaries is to add 'MW' to this list of dictionaries.

Thus, I am now so modifying this program.  

A similar change made in csl-apidev repository.

New example of svarita accent display in devanagari in mw:

<img width="574" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/b156acd4-55ff-4a68-ba50-0633aa064bad">

--------------------------------

New example of udAtta accent display in devanagari in mw:

<img width="563" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/653f7fc6-e1ae-4451-a5cd-4d05ad346bf1">

**Comment by funderburkjim** [comment]
@Andhrabharati   Happy so far?  @gasyoun  what about you?  @drdhaval2785 Any comment from you, or are you still in hibernation?

**Comment by Andhrabharati** [comment]
> The simplest way to have the MW displays to mimic pw dictionaries is to add 'MW' to this list of dictionaries.

Your adaptation of the simplest solution made MW also to render the udAtta accent with superscript 'u' as the PW family; probably this is a bit too much!!

![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/3714f16d-5d05-4b3e-9908-02161e2d91ae)

I would suggest leaving udAtta 'unrendered' in devanagari in MW, which is the "standard" practice.

But, I see something different at my end now--
![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/2d6ef2cd-af09-409e-87ac-435913885c20)

Very strange, this is!!

**Comment by funderburkjim** [comment]
> Very Strange ..

I see something different:

<img width="1054" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/d9ce3be7-f28d-4f2f-bec1-1266e1be9726">

**Comment by Andhrabharati** [comment]
You looked with a default setting of "Ignore accents".

Just try to see what the "Show accents" option displays!!

**Comment by Andhrabharati** [comment]
Seen that the "simple search" which is what you and Marcis use, is showing what you posted above; but the List and Advanced search displays behave in the strange manner that I mentioned now!!

**Comment by drdhaval2785** [comment]
I am in hibernation still, but it is coming to an end. Intend to forage again.

**Comment by funderburkjim** [comment]
## bugs fixed
in advanced search and list display.

## accent display customized for mw
udAtta  not displayed
svarita displayed with u0951 

@Andhrabharati   Unless I've made an error, this seems to match your suggestion regarding 'standard practice'.
Note that the 'unrendering' of udAtta hinders Devanagari accent comparisons between mw and pw.

When we get to agreement with regarding to Devanagari accents, I'll take up the above suggestions for IAST suggestions above.

**Comment by Andhrabharati** [comment]
Yes @funderburkjim, this piece of work now appears good enough (to move forward with other points).

BTW, my eyes never fell on this earlier, but noticed these just now--
![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/4439391c-c00b-4798-a39c-2d1e5a2095ef)

What do these "3 buttons" indicate (stand for)?
I see no action, when they were pressed of hovered upon.

**Comment by Andhrabharati** [comment]
> representation of accents in Sanskrit seems never complete in this cdsl dictionary project.

Now, I would venture saying that this has reached its "proper" goal-post (so far as the major dictionaries that used accents are concerned; there could be some minor works that may have to be looked at, but that is not a TOO SERIOUS issue to worry about).

**Comment by funderburkjim** [comment]
> What do these "3 buttons" indicate (stand for)?

They are relevant when highlighting is on in Advanced Search display.
They navigate the selected text instances ('>' next,  '<' previous).  I think the '=' gets the nearest).

**Comment by funderburkjim** [comment]
## IAST ḻ

Changed slp1_roman.xml and roman_slp1.xml for displays.
Now using `ḻ` (LATIN SMALL LETTER L WITH LINE BELOW ) in place of former
Latin small letter L with stroke.

Change for either roman input or output.

**Comment by funderburkjim** [comment]
## concern about combining iast accents

I don't foresee it being too difficult to change 'slp1_roman.xml' to display IAST output accents for Sanskrit text using the unicode combining accents.

However, if that is done, then will it be necessary to review ALL the dictionaries (mw.txt, pw.txt, etc.) and replace all sanskrit text with preformed accents into text with combining accents?   This seems like a big task, and a complicated one. (accents occur in many non-Sanskrit text fragments (think of the 'etymology' sections of MW, or the French dictionaries) - for many of these non-sanskrit texts the conversion to combining accents is probably inappropriate.

Perhaps such modifications with the xxx.txt files are NOT required.  If so, let's go ahead with the changes to the transcoding files.

**Comment by Andhrabharati** [comment]
My [initial post](https://github.com/sanskrit-lexicon/MWS/issues/167#issuecomment-2202013048) whaich is the start-off point for this issue had what I wanted to say (quite clearly)

> ### Now, about Roman accent
> 
> It appears that two versions of transcoders are "floating around" in the CDSL "domain", namely one with IAST accents (having combined-circumflex mark for svarita), and another with ISO15959 accents (having combined-grave mark for svarita).
> **This would definitely be a matter of great confusion among the users.**
> 
> Jim MUST attempt to take a corrective action for this, and adopt what he has https://github.com/sanskrit-lexicon/MWS/issues/140#issuecomment-1250381878.

but the subsequent posts might've raised a confusion that I was talking about 'preformed accented letters' vs. 'letters with combined accents'.

**Let me try be more clear and resolve the matter now.**

The slp1_roman.xml (transcoder) files COLOGNE and csl-websanlexicon repos that are the gateways to the end user have the Roman accents "proper", as

> `* udAtta  / 0301  COMBINING ACUTE ACCENT`
> `* svarita ^ 0300  COMBINING GRAVE ACCENT`
> `* anudAtta \ 0331 Combining Macron Below`
> `--> `
> `<e n='116'> <s>SKT</s> <in>/</in> <out>\u0301</out> </e>`
> `<e n='117'> <s>SKT</s> <in>^</in> <out>\u0300</out> </e>`
> `<e n='118'> <s>SKT</s> <in>\</in> <out>\u0331</out> </e>`

These are what Jim had named as 'ISO accent extension' of IAST sometime back.

But the ones that he has offered me to use for **my local working (on mw and PW set)**, mainly the one (of current topic) at "mw transcoding versions" #90 have the 'original iast accent rules'
> `* udAtta  / as \u0301`
> `* svarita ^ as \u0302`
> `* anudAtta \ as \u0300`

(that I had posted above); **this makes my locally generated file to differ with what I see at the cdsl web-display.**

Probably, I am **THE sole person** that look at the local files, in which case there is no need to worry about the point.

I shall change the transcoder files at my end & put an end to this issue.

**Comment by funderburkjim** [comment]
> I shall change the transcoder files at my end & put an end to this issue.

That being the case, I'll consider this issue closed.

Where will the accent phoenix arise next ? :)

**Comment by Andhrabharati** [comment]
> Where will the accent phoenix arise next ? :)

If you are eager, probably I (or someone else) would've to look at the other minor works (of CDSL) also once, to put thIS "phoenix" to sleep forever.
