### ISSUE TITLE
Unhide abbr.html (Boh. or Bohem. = Bohemian)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#17]
@funderburkjim Nor http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/downloads/mwtxt.zip nor http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/downloads/monierxml.zip has a list of abreviations used (the http://www.sanskrit-lexicon.uni-koeln.de/monier/abbr.html file). It is hard to find, next to impossible.

1) http://sanskritdocuments.org/dict/MWabbreviations.html outdated
2) http://www5f.biglobe.ne.jp/~apsarasjola/lang/data.files/source.files/MW0000.xml several additional Japanese translations
3) ftp://kinodata.kiev.ua/public/programs/Lingvo_v9.0_Multilingual/Dictionaries/SanskritMW/monier-abbr.txt a copy of your file Jim, compiled by a colleague of mine from Moscow

P.S.
I was impressed to find out that https://www.google.com/search?q=%22Boh.+or+Bohem.+%3D+Bohemian%22&oq=%22Boh.+or+Bohem.+%3D+Bohemian%22&aqs=chrome..69i57.5805j0j7&sourceid=chrome&es_sm=122&ie=UTF-8 found http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw010004.pdf and although there is no inherited OCR layer in the .pdf, google still made his own OCR and found the text I was looking for.

**Comment by Andhrabharati** [comment]
@funderburkjim / @gasyoun,

Is this issue closable now?

**Comment by Andhrabharati** [comment]
@funderburkjim 

Noticed two instances of `<disp>?</disp>` in the mwab_input.txt file.

`O.S.	<id>O.S.</id> <disp>?</disp> <INFER/>`
`prop.	<id>prop.</id> <disp>?</disp>`

The first one stands for **Old Slavonic** and the second one stands for **proparoxytone, or stress on third last syllable**.

You may update the file accordingly.

**Comment by Andhrabharati** [comment]
> Some of the links are still available, and possibly useful, e.g. https://sanskritdocuments.org/dict/MWabbreviations.html.

This data here is **full of errors**!! [Some one should have updated it with the latest CDSL data.]

**Comment by Andhrabharati** [comment]
> `Rev.	<id>Rev.</id> <disp> ?? </disp> <INFER/> Def? hw=arjuneSvaratIrTa, etc.`

There was a long post by me (earlier) reg. this, if you recall, asking to change Śivapurāṇa to Skandapurāṇa.
It stands for **Revakhaṇḍa**, in Skandapurāṇa, which talks about all the Tirthas in India.

> `corr.	<id>corr.</id> <disp>corrected ?</disp>`

It stands for **correct(ly)**, cf. `<ab n="incorrect(ly)">incorr.</ab>` which is the opposite of this.

> `necess.	<id>necess.</id> <disp>necessitative ?</disp>`

**necessitative** appears to be alright.

**Comment by funderburkjim** [comment]
>  long post by me (earlier) reg. this

The 3 issues of this MWS repository containing word Śivapurāṇa are
 #17, #121, #125.

Which one is the 'long post'?

**Comment by funderburkjim** [comment]
Noticed that the (6) references to 'Rev.' in MW are as `<ls>SkandaP. Rev.</ls>`,
such as under hw arjuneSvaratIrTa.  Thus, mwab_input.txt now needs no entry for 'Rev.' !

Am installing now the above changes to mwab_input.txt
