### ISSUE TITLE
DIsplay of 'rev' and 'sup' items in mw

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#173]
[Refer](https://github.com/sanskrit-lexicon/csl-orig/issues/1637#issuecomment-2143182599)
@aumsanskrit mentions

> When a supplement entry is 'integrated' to its 'appropriate' location within the main entry, would it be possible and prudent to use a specialized symbol such as a simple dash "—" for the "indentation itself" (rather than the standard "period"). This way, at a glance the reader will know that such an entry is supplemental to the main entries.

Within mw.txt there are two 'info' elements:
* `<info n="sup"/>`  for 'supplements' (additions of sense or headword)  (6395 of these)
* `<info n="rev" pc="1308,1"/>`  (revisions)  (248 of these)

These could be used to generate some indicator in the displays, perhaps at the [ID...] point. e.g. (display under aMSu)
* Under aMSu
  * mw.txt: `¦ a ray, sunbeam <info n="rev" pc="1308,1"/>`
 * display:
   * old: `a ray, sunbeam [ID=52]`   
   * new: `a ray, sunbeam [ID=52,rev,link to p. 1308,1]`
* similar for a 'sup'

I think the implementation of this is independent of the 'hierarch placement' issue of #171 and likely can be accomplished by changes to the csl-websanlexicon repo (basicadjust.php and basicdisplay.php).

Scott and AB may want to comment on this proposed enhancement
* whether it should be done at all
* whether the suggested solution above (for aMSu) is good.

**Comment by aumsanskrit** [comment]
Ultimately, I would like to see an indicator in the list display itself. However, in regard to the Headword display, I like your proposed enhancement.

But in regard to the word "aṃśu", I may be missing something; it seems to me that this word is entirely a main entry without any supplemental reference.

**Comment by funderburkjim** [comment]
## mwtestls1

url: https://sanskrit-lexicon.uni-koeln.de/work/mwtestls1/web/

This adds markup that
* identifies a record as 'sup' or 'rev'   (supplemental or revised). 
* In list display, adds a mark to identify and sup or rev.

<img width="957" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/544c6717-aaf6-4507-a5f8-47541fa2655b">

For the much rarer 'rev':

<img width="973" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/1f501e86-e009-4abd-afda-50cd1099d171">

**Comment by funderburkjim** [comment]
I think this is acceptable.   

My inclination is to go ahead and 
* sync this display code into Github 
* and install to Cologne
* Make comparable changes to the displays used in simple-search.
  * I noticed that simple search already does something similar in list pane.
  * But I think mwtestls1  is preferable.

Simple-search example:   green/red words in list pane.  No indication in main pane.

<img width="619" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/130bae17-5177-4cf2-a9df-66248f1b085b">

**Comment by Andhrabharati** [comment]
Yes, adding Ⓢ (for suppl. addition) and ® (for suppl. revision) [and Ⓓ (for suppl. deletion) or Ⓔ (for suppl. erase) entries is very appealing.

I would also suggest showing the corresp. ®/Ⓓ/Ⓔ entry along with the "modified" main entry as done in case of GRA; this would clearly show the exact correction "string" in the text.

BTW, I have seen that quite a few "sup" entries are actually supposed to be "rev" entries.
Also some entries are altogether "left" unmarked with either tag.

**Comment by aumsanskrit** [comment]
I am very Pleased!

I also laughed because "S" and "R" are the first and last initials to my legal name:  "Scott Rhodes".

**Comment by Andhrabharati** [comment]
Recollecting from our GRA suppl. "integration" work, it is seen to be containing

- 700 "add" records (entries) [for insertion of addl. strings in body matter or addl. HWs] from the suppl.
- 273 "chg" records [for modifications in the body/HW matter]
- 93 "del" records [for deletions of complete body/HW matter]

Do/should we employ similar naming in the MW suppl. "integration" as well?
[MW data has 'sup' marking for "add" elements and 'rev' marking for "chg" elements; the "del" elements are deleted from the text altogether, so their marking doesn't exist!!]

**Comment by funderburkjim** [comment]
The mwtestls1 code now installed at Cologne for mw (for Basic, List, etc.)
The comparable code base also installed for 'simple-search'.

Here we see simple-search revision (compare view above before the change)

<img width="752" alt="image" src="https://github.com/user-attachments/assets/57f69278-ee95-470b-b777-bcce99b0d301">

**Comment by funderburkjim** [comment]
I think this issue (being of narrow scope), can be closed.

There are two additional points that are forked into different github issues
1.  Errors in placement of supplemental entries in MW.  #171 is already started
2.  Similar display enhancement for Grassman. See https://github.com/sanskrit-lexicon/GRA/issues/33
