### ISSUE TITLE
Jumbled up order of P. Ā. (at the qualifier portion of the dhātu entries), as Ā. P.

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#174]
@funderburkjim 

While the proper order `<ab>P.</ab> <ab>Ā.</ab>` occurs 647 times,  the jumbled up order `<ab>Ā.</ab> <ab>P.</ab>` occurs 224 times in the mw.txt, though the rest of the entry matter is alright!

It is noted that the orig_utf8 digitisation file (2004) of  MW has `•A1. •P.` [i.e. `<ab>Ā.</ab> <ab>P.</ab>`] order just twice (L-130326 and L-132942), and tallying with the printed matter.

So it turns out that the rest of 222 cases are **wrongly changed** at sometime in the next 20 years of MW (at CDSL)!!

Marcis & Scott, have either of you ever noticed this (as you both seem to be closely referring to MW roots and verbs)?

**Comment by funderburkjim** [comment]
@Andhrabharati 
I need to make this orig_utf8 file available in this mws repository, so that others may explore your observation.
I probably found the version you have, but I don't recall exactly which one it was.
The oldest one I find now from my local files is  'mw_orig_utf8.txt' 
The first few lines of this file are:
```
%%%%%%%%%%all r /a:d*\}:d*¦ •m*f*n*.\| \(%\{A:d*\}\) •f. / 
%%%%%%%%%%c r /a:d*\}{:d*}¦ •m*f*n*.\| \(%\{{A:d*}\}\) •f. /&2}&1¦ •f. / * 
%%%%%%%%%%%%%%c r /a\}{[123]}\{/A}&1{/ all 
%***This File is E:\SANSKRIT\MONIER\MONIER.ALL, Last update 30.11.04 
 
 
<H1>000{a}1{a}1¦ ‹the…first…letter…of…the…alphabet› {;} ‹the…first…short…vowel…inherent…in…consonants.› ƒPage1,1ƒ MW000001 
<H3>100{akAra}3{a--kAra}¦ •m. ‹the…letter…or…sound› #{a}. MW000002 
```

Does this look like the one you are referring to?

**Comment by Andhrabharati** [comment]
YES, it is the one.

**Comment by funderburkjim** [comment]
The zipped file is now available at [mw_orig_utf8_2014.zip](https://github.com/sanskrit-lexicon/MWS/blob/master/history/mw_orig_utf8_2014.zip).

That 2004 date in line 5 (`Last update 30.11.04`)  is referring to the date of the  MONIER.ALL file from Thomas).

**Comment by Andhrabharati** [comment]
@funderburkjim 

I feel you should correct this error as mentioned above (all those places are clearly indicated).

No need waiting for others to react/respond.

**Comment by funderburkjim** [comment]
By the way, that orig_utf8.txt file is not from 2004, but from 2014.  The internal '30.11.04 ' date is for MONIER.ALL.  (I may have already mentioned this recently)

**Comment by Andhrabharati** [comment]
Necessary action taken by Jim.

Can be closed now.
