### ISSUE TITLE
Standardize group entries

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#175]
Group entries = alt headwords.
Work will focus on mw entries currently marked with
* `<info or="` (6462 such entries)
* `<info and="` (1764 such entries) 

The initial goal is to standardize such entries to be sequential with identical body text. As an abstract example, consider
```
<L>N1<k1>X1...
BODY1 with <info or="N1,X1;N2,X2"/>
<LEND
<L>N2<k1>X2...
BODY2 with <info or="N1,X1;N2,X2"/>
<LEND>
```
We want to impose two requirements:
* BODY1 = BODY2
* N2 = the next after N1 in mw.txt  (the two entries should be sequential, no entries in between L=N1 and L=N2).

Many of the or/and entries already satisfy these requirements.

## Why standardize?
* remove duplication  (only one BODY)
* Remove awkward `<info or-and ...`` markup
* Text more closely resembles MW print.

## Post-standardization plan
If we assume such a standardization, then the plan is to 
* systematically replace in mw.txt the two (or more in some cases) entries with
 only one entry (L=N1),  whose \<k2> metaline field is replaced by a comma-separated list of the k2 from L=N1 and L=N2.  The '\<h>' field of metaline will also be part of the k2 subfields
* remove the L=N2 entry.
* remove the \<info or="N1,X1;N2,X2"/> item from L=N1
* write some python code to generate mw_hwextra.txt (in csl-orig)
  * Such code has been written for GRA dictionary; similar code should work for mw.
* With mw_hwextra.txt,  current with the csl-pywork/v02 dictionary generation will add back L=N2 entry into mw.xml, and thus back into the displays.

As mentioned, this process has been carried out for the GRA dictionary.

This issue limited to the standardization. The post-standardization work outlined above will be handled under a separate issue.

That's the plan!

**Comment by gasyoun** [comment]
Sounds simple, yet great.

**Comment by funderburkjim** [comment]
## standardization complete
Work is [here](https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue175).

In addition to the 'two requirements' mentioned above:
* removed 'artificial hom'  ('a, b, ...')
* change `<e>X'` to be same for all entries in a group
* Some 'merging' of entries.  (see image in next comment)
* Some L-number changes 

The [groups_3f.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue175/groups_3f.txt) file shows all the and/or groups as of now.

I plan to take up the 'post-standardization' task next.

**Comment by funderburkjim** [comment]
The body of many and/or groups was constructed by merging formerly separate entries.  In the image, we see the old karvara on left, new on right.
Note the fewer `[ID=...]` on the new version.
Some headwords were 'lost' -- e.g. in the following, the 'karvarI' is now not a (searchable) headword.  

<img width="962" alt="image" src="https://github.com/user-attachments/assets/47891a1b-3587-4dc2-b4fd-c818a7e374cd">

**Comment by funderburkjim** [comment]
I think this issue can be closed.

**Comment by Andhrabharati** [comment]
@funderburkjim 

> * removed 'artificial hom'  ('a, b, ...')

I was quite glad seeing this! But then noticed that this is limited just to the "grouped entries"--
`327 cases altered by change_3b` out of `10584 matches for "<h>[^0-9<]+<" in buffer`

I hope, this removal would be extended to other places as well sometime sooner, and apply whatever correction logic to '**handle**' these missing `alphabetic homonym lables` as at the grouped entries.

> * change `<e>X'` to be same for all entries in a group

The `<L>37448.1` metaline has the `<e>` within `<k2>` as, `<k2>`**ulapya^`<e>`,ulapya/`<e>`2B**

> The body of many and/or groups was constructed by merging formerly separate entries.
> Some headwords were 'lost' -- e.g. in the following, the 'karvarI' is now not a (searchable) headword.

This is a flaw in a sense, and we have to bring back all such 'lost' headwords by adopting some 'logic'.
