### ISSUE TITLE
Difference of Hyphens (- vs. -- vs. --- vs. ----)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#18]
As in https://github.com/sanskrit-lexicon/CORRECTIONS/issues/22 I hardly understand what the different hyphens mean. Do you have it documented in a readme, @funderburkjim?
In `pAri--BAzika---tva` we have `---tva` - suffix.
In `pArita-vat` we have `-vat` - suffix. Why one has `---` another `-`? Should I reread MW preface?
In `pAri--mitya` we have `pAri--` - praefix.
In `vy--a/Sva---sAraTy-AyuDa` we have `---` - no idea.
In `pA/rTiva--pUjana----viDi` we have `----` - no idea.

![paro](https://cloud.githubusercontent.com/assets/80761/4682423/cc0f25e2-561c-11e4-9d8e-f6d9cb4fbd53.PNG)

**Comment by drdhaval2785** [comment]
This has been done away with. We now have only one hyphen '—'.

**Comment by gasyoun** [comment]
> We now have only one hyphen '—'.

Hope no data is lost.
