### ISSUE TITLE
Standardizing ls markup in MW (BhP)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#182]
This continues link standardization for bhagavatapurana begun for pwg [here](https://github.com/sanskrit-lexicon/PWG/issues/81#issuecomment-2522012469)
.

**Comment by funderburkjim** [comment]
The above change made to facilitate use of software made for pwg, etc. 

@Andhrabharati -- I imagine this  brings a smile to your face, since your version of MW has already made such a change.

**Comment by Andhrabharati** [comment]
No Jim, I never did such a thing in MW.

The British (English) style is quite different than the rest of Europe, esp. the German style.

I had removed such space in PWG & pwk only, as ot has been the 'intended' style therein.

You should revert this change in MW text, to render it corresponding to the print.

**Comment by funderburkjim** [comment]
standardization work is in [issue182 directory](https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue182).

* change_2.txt has the changes. 
  * only a few of these.  5 were print changes added to csl-corrections for mw
  * readme_change_2.txt has some discussion
  * [the csl-orig commit](https://github.com/sanskrit-lexicon/csl-orig/commit/682dad1a2b46e0dde48d4e2bacb0902459812e2c)
* bhagp_standard_2.txt has the 'standard' BhP literary source references
   * 6977 have no parameters,  1446 have 3 parameters and generate links.
   * The parameter lists (for skandhas 1-9) are compatible with
      burnouf index.
* There are 381 BhP. incomplete references bhagp_nonstandard_2.txt 
* bhagp_verse_2.txt shows the distinct standard references, with frequency.

The files just mentioned use the `iii,1,2` conversion.
As a final step, the parameter form was reverted to `iii, 1, 2`,  as requested by @Andhrabharati .

H

**Comment by funderburkjim** [comment]
Closing this issue.

**Comment by Andhrabharati** [comment]
[readme_change_2.txt]

>`----`
> delete this one. put as empty lines for the moment
>` <L>27712.2<pc>1320,2<k1>ASrAva<k2>A-SrAva<e>2  `
> `<s>A-SrAva</s> ¦ <ab>w.r.</ab> for <s>A-srAva</s>.<info n="sup"/>`
> `<LEND>`

L-27712.2 data should not be "deleted", but is to be "relocated" as L-27713.2 (it being a different HW "ā-śrāva", from "2. ā-śrava")!

**Comment by funderburkjim** [comment]
## restored ASrAva
See  comment in readme.txt 'version 4'
