### ISSUE TITLE
"ṛi" > "ṛ" 

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/MWS#2]
Namaste
http://www.sanskrit-lexicon.uni-koeln.de/scans/MW72Scan/2014/web/webtc1/index.php
In MW, the letter ऋ (both individual and in consonant combination) is made as "ṛi" in Roman, which is wrong. Such a combination of two vowels can never exist in Sanskrit. Eg. pushpī-vṛiksha. Kṛitya-vid, tad-vṛitti 
By mistake I submitted them as corrections in the form provided. Then I see that the words having ऋ are all in same manner. Please replace them with "ṛ" alone.
Thankyou

**Comment by gasyoun** [comment]
Time to close, @funderburkjim ?

**Comment by funderburkjim** [comment]
Yes, this looks closeable now.

I'm working towards a goal of replacing the AS coding in MW72, in response to @drdhaval2785 's [plea]
(https://github.com/sanskrit-lexicon/CORRECTIONS/issues/313#issuecomment-253685783)

**Comment by gasyoun** [comment]
(H1) kiṇa [p= 282] : m. a corn, callosity MBh.  Mṛicch.  Ṡak.  &c [L=50259]

 `Mṛicch.`

but

277 `mṛcchakaṭikā` Title[Mṛicch.]

a mess :)

**Comment by funderburkjim** [comment]
The difference is due to an inconsistency in AS to IAST transcoding.   
I've altered the transcoding table used in the Basic display to be consistent with the table used in the
mwauthorities.  


(H1) kiṇa [p= 282,2] [L=50259] | m. a corn, callosity MBh.  ; Mṛcch.  ; Ṡak.  &c

**Comment by gasyoun** [comment]
> I've altered the transcoding table used in the Basic display to be consistent with the table used in the
mwauthorities.

Understood.
