### ISSUE TITLE
samakzam, samakze inaccessible in displays.

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#20]
A user raised this issue regarding the displays of MW (S).
It came to his attention with headword samakza.
Currently, if a user looks up samakza, he typically doesn't see the related words samakzam, samakze,
etc.   And if the user looks up samakze, he typically doesn't see samakza.

The subheadwords (samakzam, samakze, etc.) are currently separate records (coded as H1C in case of samakza).  

I'm not sure how to handle this problem.  It is currently a problem just with MW.

**Comment by drdhaval2785** [comment]
Currently working. I checked with samakza and got samakzam. I tried with samakzam and got samakza. Closing.
