### ISSUE TITLE
Italics in etymologies missing

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#21]
@funderburkjim  Let's search `bandh` for http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/indexcaller.php

Words it etymologies should be in italics, as in the book.

[cf. Zd. band ; Gk. πενθερός, πεῖσμα ; Lat. foedus, fides ; Lit. be4ndras ; Goth. Angl.Sax. bindan ; Germ. binden ; Eng. bind.]

P.S. Lithuanian words (they are close to my mother tongue) are still pre-Unicode, I could clean up, if we had a list.
`be4ndras` -> `bèndras`

**Comment by drdhaval2785** [comment]
Except Greek, every other language is shown in italics.
Any idea why Greek is not shown in italics @gasyoun or @funderburkjim ?

**Comment by gasyoun** [comment]
> Except Greek, every other language is shown in italics.

a CSS missing, right, @funderburkjim ?

**Comment by funderburkjim** [comment]
## Devtools 
By 'right-click Inspect' in browser, we see the final html as it currently is (banD for MW):
![image](https://user-images.githubusercontent.com/6393033/102024118-fc5ae400-3d5d-11eb-8e8c-f0f758a86804.png)

So, the others are italic because contained in `<i>xxx</i>`  and the `<i>` tag generates italics.

But Greek doesn't have `<i>`. 

## scan 
The scanned image probably does show the Greek in italics:
![image](https://user-images.githubusercontent.com/6393033/102024167-4e9c0500-3d5e-11eb-9903-b17ea64b5f8e.png)


**How to change?**

**Comment by funderburkjim** [comment]
## How coded in mw.txt 
csl-prog/v02/mw/mw.txt:
```
<L>142512.1<pc>720,1<k1>banD<k2>banD<e>1E
<s>banD</s> ¦ [<ab>cf.</ab> <ab>Zd.</ab> <etym>band</etym>; 
<ab>Gk.</ab> <lang n="greek">πενθερός</lang>, <lang n="greek">πεῖσμα</lang>; <ab>Lat.</ab> 
<etym>foedus</etym>, <etym>fides</etym>; Lit. <etym>béndras</etym>; <ab>Goth.</ab> 
<ab>Angl.Sax.</ab> <etym>bindan</etym>; <ab>Germ.</ab> <etym>binden</etym>; <ab>Eng.</ab> <etym>bind</etym>.]
<LEND>
```
So, somewhere the `<etym>` tag is being converted to `<i>` tag,

But `<lang n="greek">πενθερός</lang>` is apparently being converted to just the Greek text.

Where are these conversions happening?

## maybe in xml?
Look at mw.xml  first: (search for `<L>142512.1`):
```
<H1E><h><key1>banD</key1><key2>banD</key2></h><body><s>banD</s>   [<ab>cf.</ab> <ab>Zd.</ab> 
<etym>band</etym>; <ab>Gk.</ab> <lang n="greek">πενθερός</lang>, <lang n="greek">πεῖσμα</lang>; 
<ab>Lat.</ab> <etym>foedus</etym>, <etym>fides</etym>; Lit. <etym>béndras</etym>; <ab>Goth.</ab> 
<ab>Angl.Sax.</ab> <etym>bindan</etym>; <ab>Germ.</ab> <etym>binden</etym>; <ab>Eng.</ab> 
<etym>bind</etym>.]</body><tail><L>142512.1</L><pc>720,1</pc></tail></H1E>
```

Still have `<lang n="greek">πενθερός</lang>` in mw.xml.

So the conversion is happening later.

That must mean we need to look in csl-websanlexicon where xml is converted to html.

**Comment by funderburkjim** [comment]
## where in csl-websanlexicon ?

https://github.com/sanskrit-lexicon/csl-websanlexicon/tree/master/v02/makotemplates/web/webtc

Almost surely in either basicadjust.php or basicdisplay.php:
![image](https://user-images.githubusercontent.com/6393033/102024455-28776480-3d60-11eb-95af-3b0c6931a8b7.png)

**Comment by funderburkjim** [comment]
## Not in basicadjust.

Search for 'lang' in [basicadjust.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/webtc/basicadjust.php).

Only in two lines:
```
   $line = preg_replace('|<g></g>|','<lang n="greek"></lang>',$line);    <<< this changes old <g> to <lang>
OR
   #$line = preg_replace('|></lang>|'," empty='yes'></lang>",$line);   <<< This is a php comment
```

These aren't what is removing the `<lang>` tag around Greek.

**Comment by funderburkjim** [comment]
##  basicdisplay.php is where a change is needed:

Here "lang" might occur in three places:
* the  function **sthndl** where the xml parser is entering the '<lang>' tag
* the function **chrhndl** where the xml parser encounters a text node
* the function **endhndl**, where the xml parser is leaving the `<lang>` tag

In the current implementation, the `<lang>` element is mentioned in **sthndl** and **chrhndl**,
 but is not mentioned in **endhndl**.

## Current `<lang>` in sthndl

   ```
     } else if ($el == "lang") {
    // nothing special here  Greek remains to be filled in
    // Depends on whether the text is filled in
    $n = $attribs['n'];
    if (in_array($this->dict,array('pwg','mw','pw','wil','md','yat','mw72','snp','stc','gra'))) {
     # nothing to do.  Greek (and other) unicode has been provided. 
     }else {
     # put a placeholder where the greek, arabic, etc. needs to be provided.
     $this->row .= " ($n) ";
    }
  }
  ```

##  Current `<lang>` in **chrhndl**
```
  } else if ($this->parentEl == "lang") {
   // Greek typically uncoded
   //$data = $data . ' (greek)';
   $this->row .= $data;
```
##  How to introduce `<i>` tag?

We have at least two options:
* introduce the opening `<i>` tag in the *sthndl* clause 
  * add a closing `</i>` tag in a new "lang" clause of *endhndl*
* OR, put both  `<i>` and `</i>` into *chrhndl*, e.g.:
   `$this->row .= "<i>$data</i>";`

I'l try out the second choice in local installation.
...

**Comment by funderburkjim** [comment]
## local installation test step 1:
in local csl-websanlexicon repository,
change /c/xampp/htdocs/cologne/csl-websanlexicon/v02/makotemplates/web/webtc/basicdisplay.php
as in 2nd option above.

BUT one refinement,  do this ONLY for MW dictionary
So the change will be
```
   if ($this->dict == "mw") {
    $this->row .= "<i>$data</i>"; # Greek italic for MW
   } else {
    $this->row .= $data;
   }
```

## local installation test step 2:
regenerate local displays for mw:
in csl-websanlexicon/v02,  in gitbash:
```
grep mw redo_xampp_all.sh  # get the command to redo mw
# run the command
sh generate_web.sh mw  ../../mw
```

## See if our local output now shows italics for Greek
![image](https://user-images.githubusercontent.com/6393033/102025398-b7d34680-3d65-11eb-97dd-e6de03de3638.png)

Greek looks italic to me!

Inspect:
![image](https://user-images.githubusercontent.com/6393033/102025461-0a146780-3d66-11eb-90de-83306466fb23.png)

The Greek text is in the `<i>` tag, as expected.

Conclusion:  local change is good.

**Comment by funderburkjim** [comment]
## commit and push to github
We want to get the change to the Cologne displays.


First, commit the change and push to github.
Do this in local gitbash terminal.  Here's the terminal session
```
Jim@Jim-Dell MINGW64 /c/xampp/htdocs/cologne/csl-websanlexicon/v02 (master)
$ git status
Refresh index: 100% (3349/3349), done.
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   makotemplates/web/webtc/basicdisplay.php

no changes added to commit (use "git add" and/or "git commit -a")

Jim@Jim-Dell MINGW64 /c/xampp/htdocs/cologne/csl-websanlexicon/v02 (master)
$ git add .
warning: LF will be replaced by CRLF in v02/makotemplates/web/webtc/basicdisplay.php.
The file will have its original line endings in your working directory

Jim@Jim-Dell MINGW64 /c/xampp/htdocs/cologne/csl-websanlexicon/v02 (master)
$ git commit -m "MW: add italics around Greek text.
> Ref #21"
[master ba6b95c] MW: add italics around Greek text. Ref #21
 1 file changed, 5 insertions(+), 1 deletion(-)

Jim@Jim-Dell MINGW64 /c/xampp/htdocs/cologne/csl-websanlexicon/v02 (master)
$ git push
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 604 bytes | 201.00 KiB/s, done.
Total 7 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To github.com:sanskrit-lexicon/csl-websanlexicon.git
   e61847d..ba6b95c  master -> master

Jim@Jim-Dell MINGW64 /c/xampp/htdocs/cologne/csl-websanlexicon/v02 (master)
```

**Comment by funderburkjim** [comment]
## pull change to cologne server:

Connect to Cologne server via ssh terminal.
Here is session
```
# Navigate to scans/csl-websanlexicon/
> git pull
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Entpacke Objekte: 100% (7/7), Fertig.
Von github.com:sanskrit-lexicon/csl-websanlexicon
   e61847d..ba6b95c  master     -> origin/master
Aktualisiere e61847d..ba6b95c
Fast-forward
 v02/makotemplates/web/webtc/basicdisplay.php | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)
```

## install the changes for mw
> cd v02
/nfs/projekt/sanskrit-lexicon/http/docs/scans/csl-websanlexicon/v02
> grep mw redo_cologne_all.sh
sh generate_web.sh mwe  ../../MWEScan/2020/
sh generate_web.sh mw72  ../../MW72Scan/2020/
sh generate_web.sh mw  ../../MWScan/2020/
> sh generate_web.sh mw  ../../MWScan/2020/
updating for websanlexicon for dictionary mw to ../../MWScan/2020/
```

Change should now be visibile in displays

**Comment by funderburkjim** [comment]
Check  Greek is in italics in mw:

![image](https://user-images.githubusercontent.com/6393033/102025717-e4885d80-3d67-11eb-9b15-e05f7b094ade.png)

looks good!

**Comment by funderburkjim** [comment]
I thought showing all the steps of this change might be a useful review for Dhaval.

**Comment by drdhaval2785** [comment]
This was a wonderful refresher course Jim. Will try to replicate for some problem soon.

**Comment by gasyoun** [comment]
> Greek looks italic to me!

It sure is. And sooo damn well documented as well.
