### ISSUE TITLE
अयुर्वेद vs. āyurveda print error (in colontitle)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#23]
@funderburkjim Right from page number 148 at http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/servepdf.php?page=148 we can see अयुर्वेद instead of. Do we note this print error somewhere, or as it is not used in our system, not even for naming scan pages, so we continue to ignore it?

**Comment by funderburkjim** [comment]
This column title print error must be what you notice:
![image](https://cloud.githubusercontent.com/assets/6393033/7687978/fa8e1564-fd6e-11e4-9710-6e9911206774.png)

This column title doesn't play any role in the digitization, so there is nothing overt we can correct.

A note could be place in the corrections_factual file, I guess ?

**Comment by gasyoun** [comment]
I guess yes, because I do hope this list of factual errors will be added to one of the next reprints to come. We must ber ready for it.

**Comment by funderburkjim** [comment]
[corrections_factual](https://github.com/sanskrit-lexicon/MWS/blob/master/corrections-factual.txt) now reflects this print error.

**Comment by gasyoun** [comment]
> corrections_factual now reflects this print error.

Thanks.
