### ISSUE TITLE
Problem in Deprecated Displays at 'hima'

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#25]
A user discovered a problem in the [2008 Advanced Search](http://www.sanskrit-lexicon.uni-koeln.de/mwquery/index.html) display.  You can see it by doing an exact search for Sanskrit word 'hima'.

A Perl parser subroutine bombs:
```
Software error:

not well-formed (invalid token) at line 1, column 483, byte 484:
<H2B><h><key1>hima</key1><key2>him/a</key2></h><body>  <lex>mf<p><s>A</s></p>n.</lex> 
<c>cold , cool</c> <ls>{a href='javascript:winls("mwauth_SktDevaUnicode.html","record_Ja1takam_")'} 
Ja1takam. {/a}</ls> <b><c><ab>cf.</ab> <ab>Zd.</ab></c> <etym>zima</etym>  ;  <c><ab>Gk.</ab>
</c> <p><gk>1</gk></p> <gk>2</gk>  ;  <gk>3</gk>  ,  <gk>4</gk> ; <ab>Lat.</ab> 
<etym>bi1mus</etym> <c>for</c> <etym>bihimus</etym> ; <etym>hiems</etym> <c>; <ab>Slav.</ab>

</c> <etym>zima</etym> <c>Lit. ż�m� </c></b>  </body><tail> <mat/>   <L>262971.1</L></tail></H2B>

 at /usr/lib64/perl5/XML/Parser.pm line 187
```

The deprecated [basic display](http://www.sanskrit-lexicon.uni-koeln.de/monier/indexcaller.php) doesn't bomb, but does improperly display this record.

The problems are somehow involved with the extended Ascii characters in this record.

I don't currently plan to solve this problem for the deprecated displays.

The problem does not show up in the current (2014) displays.

**Comment by gasyoun** [comment]
I could fix the Lithuanian etymology, but 2008 is dead, so why should we? Let it die.

**Comment by funderburkjim** [comment]
That's my view, too.

**Comment by gasyoun** [comment]
The only thing I would do is add a link bellow `For help, please send mail to the webmaster (funderburk1@verizon.net), giving this error message and the time and date of the error.` to https://github.com/sanskrit-lexicon/ or some other fine place as well.

**Comment by funderburkjim** [comment]
I'm not sure how to do that, but I thought a 'Deprecated' notice should be put on those old displays.

**Comment by gasyoun** [comment]
Anything is better than nothing. The notice should be in font 20-30.

**Comment by funderburkjim** [comment]
Added 'deprecated' notices to deprecated displays which are referenced in [Cologne Home page](http://www.sanskrit-lexicon.uni-koeln.de/).  

The only exception is the Boeghtlink-Schmidt display, which is not elsewhere duplicated.

**Comment by gasyoun** [comment]
But the Boeghtlink-Schmidt display is not unupdated, contains older typoes, right?

**Comment by funderburkjim** [comment]
@gasyoun  Right.  The B-S display uses old data.  It should be possible to use the 'apidev' approach to
generate a 'new' version of the B-S display if there is demand for it.

**Comment by gasyoun** [comment]
Demand depends on how much hours should be spent to do the apidev magic. 1 day?
