### ISSUE TITLE
MW display variant:  (H2B/H2C cases)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#26]
A user of MW posted the following to the Correction form, regarding headword 'BAvanA':

```
Repeat the first part of the definition of bhAvanA, that is given under bAvana after the value as a masculine, before the present definition of bhAvanA, in order to have the complete meaning of the lemma bhAvanA under one's eyes when one searches for it (in the present situation when bhAvanA is searched for as such, one gets only the meanings exclusively femminine, which are in fact less important than the ones occurring in the neuter gender also.)
In fact the actual dictionary page has before the meanings of bhAvanA/am and immediately following, the meanings of bhAvanA
N.B. The dictionary distinguishes the first set of meanings of bhAvanA from the second set of meanings, and so doing produces two apparently different entries, because with the first set of meanings the stem is found also as a neuter, as bhAvanam; but with the second set of meanings  the stem is only feminine bhAvanA.
Another possibility would be to remove all together the entry bhAvanA and place the definition of bhAvanA only feminine under the entry bhAvana, after bhAvanA/am is given (and this is exactly what the dictionary does, so it might be the best thing to do in fact: but the beginner might be penalized by the fact that typing bhAvanA in the search box he would be replied that the entry doesn't exist, something which is obviously false)
```

I think this is an example of a long-standing issue with displays of certain headwords in MW.  Using the apidev display has provided a possible solution.  I'd like to describe this solution and solicit comments.

**Comment by funderburkjim** [comment]
A  [test display](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/testmw-0.1.html)
 has been prepared to compare the proposed solution with the current display.

When you search for a word, the new display shows in the left panel, and the old display shows in the right panel.

The differences show up in such headwords as (in SLP1 spelling):
```
BAvana, BAvanA
agra, agrA, agre, agreRa
guru, gurvI
rAma, rAmA
 etc.
```

It's complicated to describe the situation in words, but briefly,
the old display shows ONLY the records whose 'key1' matches the given citation.
While, the new display also shows other 'related' headwords. And the new display distinguishes
the 'related headwords' visually by presenting them with a light gray background color.

At the moment, the new display looks to me like an enhancement that should replace the old display.  I hope others will comment.

**Comment by gasyoun** [comment]
In Devanagari mode the word gets converted to भावनाथ. I wonder if we can leave the input field unchanged. Because if I want to change the query a bit (only by let's say 1 letter), I have to rewrite it all now. I agree that the context will not hurt. I'm no fan of grey (make it lighter, paler?), but as I have no better idea for now, I keep silent.

**Comment by funderburkjim** [comment]
User Zaaf2 made a similar comment:

Regarding L=48545, hw=कारणा

I think this should appear under कारण 1 n. ― This kind of problem results from the fact that in this new version of the dictionary (contrary to the printed edition and to former digital versions) the feminine and other forms of the same word are shown as separate entries, as if it were unconnected with the headword. I think this unjustifiable and misleading, first because it does not render the original structure of the article as in the printed edition (and surely the author had good reasons for that); secondly because it does not enhance the accessibility, since in reading and in research it is useful to have at a glance the full range of forms and meanings a word has acquired throughout its history, without having to do another search in the sidebar to see if there are other forms of the same word. Of course it is only my personal opinion. I only think the former synoptic display method better, and less prone to this kind of inconsistency or error, as here.  Thank you.

**Comment by funderburkjim** [comment]
The 'sample' [APIDEV displays](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/) are currently invisible to the general user, like Zaaf2.  

The easiest solution to make them accessible is to add a link to these from the Cologne Sanskrit Lexicon [home page](http://www.sanskrit-lexicon.uni-koeln.de/).

A harder solution (for me) is to incorporate the ideas of these sample displays into the 'normal' displays.  This is harder because of substantial technical differences between the sample displays and the 'normal' displays.

**Comment by gasyoun** [comment]
Adding more links would need explaining them. Even `B   L   A   M   D   S1   S2   Deprecated  ` can take some time to understand.
If http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/ `autosuggest`  and `autocomplete` is the same, I would leave 1.
I would not go for the harder in 2015. I would concentrate on the content, not the form.

**Comment by funderburkjim** [comment]
The changes in MW display solved the display problem for Zaaf2:
<blockquote>
Thank you for your attention. Yes, those new displays solve perfectly the problem! I think the best is list-0.2. The suggestion-as-you-type feature is a major enhancement. I would only suggest that there be an option for the user to turn the sidebar on and off (really a switch between the basic and the full display options), although I personally would let it always on, as it is very useful. In a portable device, though, it would require precious screen space. Yes, absolutely: not only there should be a link to those display options in the home page, but they should appear as the standard displays for MW, at least the basic-0.3 and the list-0.2 versions. They seem to me just perfect. The “old” display method should be deprecated.
</blockquote>

**Comment by funderburkjim** [comment]
Re homepage link additions:

I was thinking of adding a separate 'DEV' section at the bottom, which would probably have a small
comment and a link to the [apidev sample displays](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/).  There would be no addition to the B L ... list for each 
dictionary.

**Comment by gasyoun** [comment]
DEV makes me think it's Devanagari, so bad name. Even B L addition would make more sense. A = for autotype :key:

**Comment by funderburkjim** [comment]
DEV just an abbreviation.  I would use 'Development' . Sorry for confusion.

Development displays would also include multi-dictionary displays. One such might allow a user
to choose any two dictionaries, and then, for a given headword, display the results side by side - sort
of a generalization of the PW/SCH display.   E.g. MW v. PW,  SKD v. VCP, WIL v. YAT, etc.

**Comment by gasyoun** [comment]
Confusion is no problem if just mine, but I guess I would have been not the only one. Side by side would be a gem, but I ask you to deal more with contant than display in 2015. It's all I ask and in the upcomming weeks will bring new batches of corrections together with @Shalu411 - she is preparing a come back.

**Comment by Andhrabharati** [comment]
> DEV just an abbreviation. I would use 'Development' . Sorry for confusion.
> 
> Development displays would also include multi-dictionary displays. One such might allow a user to choose any two dictionaries, and then, for a given headword, display the results side by side - sort of a generalization of the PW/SCH display. E.g. MW v. PW, SKD v. VCP, WIL v. YAT, etc.

The link for testmw-0.1.html [individually](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/testmw-0.1.html) and in the [group](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/) is not accessible now.

**[It seems to be the one being talked about here.]**

@funderburkjim 

Would you mind making the link active again, or is this issue closable now?

**Comment by funderburkjim** [comment]
The dev versions were made for a specific purpose at the time in 2015.
The time of this issue having passed, I'll close the issue.

**Comment by funderburkjim** [comment]
Possibly this technique of a 'development' version could have use in other contexts.
