### ISSUE TITLE
bug: pradeSavartitvA,  prAYc, sAtmyatas, sAzwrika

### ISSUE THREAD

**Issue by mbykov** [sanskrit-lexicon/MWS#28]
key1 - pradeSavartitvA - key2 - pra-deSa---varti-tA
should be -tvA

"key1: prAYc" - "key2: prAk"
should be prAYc

  key1 - sAtmyatas key2 - sA<srs/>mya-tas
should be  sAt-

key1 - sAzwrika - key2 - sA<srs/>zrifka - 2 bugs!!!
shoild be -zwrika + w, -f

**Comment by gasyoun** [comment]
@mbykov thanks, this brings me to an idea there should be a few more.
@drdhaval2785 what do you think about batch comparison of `key1` and `key2`? Seems there are even more typoes in reach of a hand. Some fuzzy magic?!

**Comment by mbykov** [comment]
no, there is no bug of this type, I check already.

**Comment by gasyoun** [comment]
@mbykov if you deal with 280k words, how can you be sure? There is RegEx that can help compare key1 and key2 in all the dictionaries and ignore differences like `*` or `accents`, but you have not done it, have you? Wish @funderburkjim would be here.

**Comment by mbykov** [comment]
I am now converting MW dict to JSON form, and so check key1 and key2 in all rows. And yes, I have ignored accents and other special symbols, and simply strip them 
like, for example, <key1>sArisTAKA</key1><hc1>1</hc1><key2>sArisTA-KA~</key2>

**Comment by gasyoun** [comment]
MW dict - what release, what date?
So out of all the words only 4 mistakes?

**Comment by mbykov** [comment]
last xml.dict from coeln site. Yes, only 4 mistypes. But look my note about accents and special symbols.

**Comment by drdhaval2785** [comment]
@mbykov and @gasyoun 
I rechecked independently.
The code is https://github.com/sanskrit-lexicon/MWS/blob/master/k1k2/clash.py
The output is https://github.com/sanskrit-lexicon/MWS/blob/master/k1k2/k1k2clash.txt

There are at least a few more than @mbykov found.

```
ISeSvara:ISe@Svara
upasamas:upasam2as
garBadAsI:garBadAsa
dakziRApraYc:dakziRAprAYc
dASa:dAS2a
parASraya:>parASraya
pradeSavartitvA:pradeSavartitA
prAYc:prAk
sAtmyatas:sAmyatas
sArisTAKA:sArisTAKA~
sAzwrika:sAzrifka
```
Total 11 entries.

The adjustments made were
```
	repl = [('-',''),('/',''),('^',''),(' ',''),("'","")]
and
	word = re.sub('[0-9]$','',word)
```

**Comment by gasyoun** [comment]
@drdhaval2785 thanks, great. Guess not only in MW.

**Comment by drdhaval2785** [comment]
Code is resilient enough to test for all dicts, if that is what you had in
mind.

**Comment by gasyoun** [comment]
Yap, indeed, that was it.

**Comment by funderburkjim** [comment]
Here are the corrections from the list above:
```
ISeSvara:ISe@Svara  29844.5 I<sr/>Se@Svara => I<sr/>Se<srs/>Svara
upasamas:upasam2as 36145  NOT AN ERROR. key2=upa-sam-<root><hom>2</hom>as</root>
garBadAsI:garBadAsa 64013 key2 g/arBa--dAsa => g/arBa--dAsI
dakziRApraYc:dakziRAprAYc 89435.1 Already corrected key1 = dakziRApraYc
dASa:dAS2a  91865.2 key2 error. dAS2a => dASa
parASraya:>parASraya key2 error >parASraya => >parASraya
pradeSavartitvA:pradeSavartitA  134715.1 key2 err. pra-deSa---varti-tA => pra-deSa---varti-tvA
prAYc:prAk  done  See #28. key1 error prAYc => prAk
sAtmyatas:sAmyatas  See #29. key2 error
sArisTAKA:sArisTAKA~  243121  key1 error: sArisTAKA => sArisTAKA~ (loan word)
sAzwrika:sAzrifka  See #30, key2 error
```

These are in process of installation.

**Comment by funderburkjim** [comment]
There should be a check for consistency between key2 and key1 as part of the update process.
There is a program at Cologne to do this, but it is written in Perl and last run apparently in 2007!

**Comment by funderburkjim** [comment]
Here's the python routine I'm using for the converting key2 to key1 for MW:
```
def key2_to_key1(x):
 """ convert MW key2 to key1 form """
 x = re.sub(r'<hom>.*?</hom>','',x)
 x = re.sub(r'<sr1?/>','',x) # <sr/>, <sr1/>
 x = re.sub(r'<srs1?/>','',x) # <srs/>, <srs1/>
 x = re.sub(r'<shortlong/>','',x)
 x = re.sub(r'</?root/?>','',x) # <root>, </root>, <root/>
 x = re.sub(r'[/\^]','',x) # accents
 x = re.sub(r'-*','',x)  # pada separators
 x = re.sub(r"'",'',x) # avagraha
 x = re.sub(r'(.) (.)',r'\1\2',x) # multi-word space.  Error if space at ends
 return x
```

If key1 != key2_to_key1(key2), then there is considered to be an error.  The error may be in 
either key1 or in key2; to determine which, further examination required.

This generates all the errors listed above, along with two more where there is an extra 'space character' at one end or another in key2:
```
key1 (kramAgatatva) != key1a ( kramAgatatva), key2= kram/A<srs/>gata---tva, L=57824

key1 (hiraRyakeSiSAKIyabrAhmaRa) != key1a (hiraRyakeSiSAKIyabrAhmaRa ), 
        key2=hiraRya--ke<sr1/>Si--SAKIya-brAhmaRa , L=263200.05

```

**Comment by funderburkjim** [comment]
These corrections installed.

**Comment by funderburkjim** [comment]
I think this issue can be closed. 

@mbykov   Feel free to reopen if I've missed something.

**Comment by gasyoun** [comment]
2007 vs. 2016, hurray!
