### ISSUE TITLE
2 bugs: sAzwrika

### ISSUE THREAD

**Issue by mbykov** [sanskrit-lexicon/MWS#31]
key1: <key1>sAzwrika</key1> - key2: <key2>sA<srs/>zrifka</key2> 2 bugs!!!

should be - <key2>sA<srs/>zwrika</key2>

**Comment by funderburkjim** [comment]
This is L= 243549.

Agree with correction to key2.

**Comment by gasyoun** [comment]
Good to see the bug catcher back.

**Comment by funderburkjim** [comment]
Correction installed
