### ISSUE TITLE
MWAuthorities display

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#32]
This issue is prompted by the comments of a long-time user Giulio Geymonat.  

He has found to be confusing several aspects of the [MWAuthorities display](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/sqlite/mwauth_roman.html)  .

Several of his points make sense to me, and perhaps it is worth while to revamp that part of the
display.

Here are some of his comments:

```
Looking closely at the list given in the window and the list in the printed version, I have noticed few 
'awkward things such as sources missing, sources given twice for no apparent reason, sources given 
'not in any alphabetical order and sources missing completely from the list
```

```
 this is a clear (minor) mistake easily fixable: "....is based primarily on the lists presented on pages xxxiii 
'andxxxiii of the preface to the dictionary" pages xxxiii and xxxiv would be the obvious correction.
```

This comment was in response to my explanation to him of the order (alphabetical by first column) of the display.
```
I understand now that the funny order that one finds on the window depends on the fact that  such 
order is based on the first letters of the entries without taking into account the rest of the word: I still 
see a problem though here, because one cannot know about this fact and feels puzzled when reads 
the list as such: maybe a note could help, something that explains in plain words why this is so, or at 
least a  warning: "Don't expect any alphabetical order: just take it as it is, and be grateful to the 
volunteers that made possible this enterprise". 

I notice actually that in the printed edition there is a warning: "The order is that of the English 
Alphabet" (why Alphabet with a capital A?)

There is then, in the electronic version of the list of works and authors, the undeniable problem of 
repetitions (a fact easy to notice, just scrolling down the list): why three times, for example suzruta? or 
twice sUryasiddhAnta? or twice siddhAntaziromaNi? or trice sarvadarzana-saMgraha? or trice saMhitA-
upaniSad-brAhmaNa? twice sAyaNa? (I am on the s; but if you go on any letter you'll find this problem 
of repetitions; for example atharva-veda-pariziSTa is given four times! A record I think!).

Also those strange names on the left with those numbers occurring: I bet everyone using this 
dictionary asks himself: what are they? I wonder:  couldn't they be removed? 

So I still think there is something to be done about the list, I still think that as it is now it looks a bit 
funny: even if one does not look at it as a whole (so that he cannot realize that the list is not in any 
strict alphabetical order), but just clicks on an abbreviation and finds repeated two or three times (and 
even more!) the title of the same work, he's bound to think "Hey! What's this? There must be 
something wrong here! Or something which I don't know: maybe different editions of the work?" 
Which is a pity, being so accurate and useful the dictionary in general.
```

Would others think about this a bit, and make suggestions about how they think this aspect of the
MW display should be improved?

I hope we will be able to make a similar enhancement to the PW(K) and PWG displays, for which we now have digitized versions of the bibliographies.   To the extent reasonable,  it would be desirable for this 'Authorities/Literary Source Link' aspect of all three displays to be similar.

**Comment by funderburkjim** [comment]
For reference, I've uploaded the basic [xml document](https://github.com/sanskrit-lexicon/MWS/blob/master/mwauthorities/MWWorksAuthorsCurrentMarkup3.xml) for the MWauthorities.

As need dictates, I'll upload other programs and data files.

**Comment by gasyoun** [comment]
>  maybe different editions of the work?

Untrue in all cases?

> Alphabet with a capital A

Just outdated manner, I guess.

> The order is that of the English Alphabet

So why not have it as it was in printed book?

**Comment by funderburkjim** [comment]
I think the reason that there are repetitions of work names is as follows:
(a)  That mysterious first column shows the abbreviation *as it appears in the digitization*  (and even
      more confusing to the uninitiated, it is shown in the current MWAuthorities display in the Anglicized
      Sanskrit transcoding rather than Unicode version of IAST.)
(b) As with recent work with PW, there was with MW the issue of correlating the abbreviations of literary sources appearing in the body of the dictionary with the list of works and authors.  One artifact of this matching process is that sometimes there are two or more abbreviations (first column) which are matched with the same item from the list of works and authors.  
(c) Since the MWauthorities display shows a separate line for each literary source abbreviation appearing in the body of the dictionary, there thus can appear duplicates from the list of works and authors.

Here is an example, mentioned by Giulio:
```
Su1ryas.	Title	sUryasidDAnta
S3u1ryas.	Title	sUryasidDAnta
```
Note that there is a slight spelling difference in the literary source abbreviation (Su1...  in one case, and S3u1... in the other).

A search in monier.xml shows that 'S3u1ryas'  appears twice, under headwords
SaNku and SEGra  (SLP1 spelling)  That 'S3' indicates a palatal sibilant, and appears to be in
agreement with the scanned text:
![image](https://cloud.githubusercontent.com/assets/6393033/16852100/945dd30c-49d4-11e6-8518-cdd3afcf0049.png)

So, either the printed text is wrong in using a palatal sibilant, OR  there is some other work being referenced.  At the time of making this correspondence, I could not resolve this issue, so asserted that S3u1ryas must refer to sUryasidDAnta.  Since the subject under discussion under discussion under SaNku is a term of astronomy, and sUryasidDAnta is a work on astronomy, my current opinion is that
S3u1ryas under SaNku should be considered a print error, and be changed to Su1ryas.

The situation with SEGra is similar:
![image](https://cloud.githubusercontent.com/assets/6393033/16852255/51b245f0-49d5-11e6-8161-e0c8dbcd97c5.png)

And I think S3u1ryas should also be changed as a print correction  in this case.

Thus, after these changes, there will be no need for the S3u1ryas. literary source abbreviation;
it can be deleted from the part of the system  (namely, from the [linkmwauthorities]() file).
Then, after the MWauthorities displays are regenerated, there will be no duplication of sUryasidDAnta.

It would be useful for someone to do a similar investigation of the other 'duplicates' appearing in the MWauthorities display.  Probably most will be similarly resolved by corrections.

**Comment by funderburkjim** [comment]
@gasyoun   I've suggested it to Giulio.  We'll have to see if he wants to.

**Comment by funderburkjim** [comment]
The MWauthorities display has now been changed so that it displays the records in 'scan order', meaning the order that they appear in the text.

```
Actually, the order is that of the [mwuathorities_init.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwauthorities/mwauthorities_init.txt), which is a transformation of the xml file, with slight additional editing.
```

[Here](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/sqlite/mwauth_deva.html) is the Devanagari display.

**Comment by funderburkjim** [comment]
As is invariably the case with a new computation, one or more critters crawl into visibility.

In the new display, the list of abbreviations (last field)  brings two features to light:
* Sometimes, there is more than one abbreviation (I count about 150 of these)
  For instance, in the 2nd item, AcAranirRaya, there are two abbreviations [Ācāranirṇ., Ācār.].
  These associations were done by me at some distant point in the past, on the basis of formal
  similarities between the implicit abbreviations of the scanned list of works and the entry from
  the mwuathorities.   Such cases indicate places where, according to the analysis, MW was inconsistent
  in the abbreviations appearing in the text and the implied abbreviations of the list of works. It is
  quite possible that there are some errors here.
* Sometimes (55 cases) the word 'unused' appears in the abbreviation.  These are cases where we
  think there are NO instances in the text which point to the given work appearing in the list of works.
  Item # 4 is of these type: `Adi-parvan  of the  mahABArata` .  It seems odd that MW would have
  items in the list of works that are never referenced.  

In a perfect world, someone would examine these oddities and provide an independent evaulation of
the accuracy of the correspondences between textual references and the list of works.

**Comment by funderburkjim** [comment]
I hope others will take a look at the new display, and evaluate whether it seems to be an improvement over the previous MWauthorities display.  My opinion is that it IS an improvement.

**Comment by gasyoun** [comment]
> MW was inconsistent in the abbreviations appearing in the text and the implied abbreviations of the list of works. It is quite possible that there are some errors here.

Will take years to weed out.

> odd that MW would have items in the list of works that are never referenced.

Odd is not the fact, but that there are so many. I see it many times and have counted myself in the past in different dictionaries, that there are plenty of unused, serialized sometimes abbreviations.
