### ISSUE TITLE
MW display under xampp

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#34]
In developing the revised mwauthorities display, I did most of the work locally.

The first step was to download a local version, and put it under xampp:

```
C:\xampp\htdocs\cologne
```

by running the (GIT BASH) script

```
sh dictionary_init.sh mw
```

This bash script is [here](https://gist.github.com/funderburkjim/bd86c8adef3b78de489f1c4403d262fb).

However, when I went to use one of the mw displays in xampp:

```
http://localhost/cologne/mw/web/webtc1/index.php
```

and searched for a word I got this error message:

```
Caught exception: SQLSTATE[HY000] [14] unable to open database file
db = sqlite:C:\xampp\htdocs\cologne\mw\web\webtc/sqlite/mw.sqlite
```

Most disconcerting!

I believe this is a rather subtle bug; a solution has thus far eluded me.

Here are some observations that seem relevant:
-  I tried this on local versions of three other dictionaries (PWG, YAT, SKD) and encountered NO
  problem.  So, it is something to do with MW.  The mw.sqlite file is larger than any of the other three
  sqlite files 
-  I have a local version of sqlite3, and opened mw.sqlite with it:
  
  ```
  $ cd /c/xampp/htdocs/cologne/mw/web/sqlite
  
  Jim@JIM-DELL /c/xampp/htdocs/cologne/mw/web/sqlite
  $ sqlite3 mw.sqlite
  SQLite version 3.7.6.3
  Enter ".help" for instructions
  Enter SQL statements terminated with a ";"
  sqlite> select * from 'mw' where key='deva';
  deva|95518|<H1><h><hc3>110</hc3><key1>deva</key1><hc1>1</hc1><key2>deva/</key2></h><body> <lex>mf<p><s>I</s></p>n.</lex> <p><c>fr._3.</c>~<s>div</s></p> <c>heavenly_,_divine_<p>also_said_of_terrestrial_things_of_high_excellence</p></c> <ls>RV.</ls> <ls>AV.</ls> <ls>VS.</ls> <ls>S3Br.</ls> <p><ab>superl.</ab>~ ~  <phw><dL>95539.11</dL><s><sr1/>deva/-tama</s>~<lex type="phw">m.</lex></phw>  ~ <ls>RV._iv_,_22_,_3_<etc1/></ls>~;~   <phw><dL>96277.1</dL><s><sr1/>devi-tamA</s>~ <lex type="phw">f.</lex></phw>  ~,~<ls>ii_,_41_,_16</ls></p> </body><tail><pc>492,2</pc> <L>95518</L></tail></H1>
  deva|95519|<H1B><h><hc3>110</hc3><key1>deva</key1><hc1>1</hc1><key2>deva/</key2><
  etc
  .exit
  ```
  
  Thus, the mw.sqlite file seems fine.
- the code is exactly the same as the code being run by the Cologne server, which runs fine, as we know.

It would be good to find the source of this problem, so anyone so-inclined can use a local version of the MW display.

I would be interested if anyone else has tried this local MW display, or has any thoughts about
what might be going on.

My version of XAMPP is 5.6.8.

**Comment by gasyoun** [comment]
> I would be interested if anyone else has tried this local MW display, or has any thoughts about
what might be going on.

Only PWG, PWK. XAMPP version has nothing to do with it, it's up to date.

**Comment by drdhaval2785** [comment]
With 2020, installation and updation in local is a jiffy. closing.
