### ISSUE TITLE
Advanced Search Display - Remember 'text/headword' setting

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#35]
A User submitted this suggested improvement to the Advanced Search Display for MW:

```
	Dear friends - I love MMW and use it all the time - what a great service to Sanskrit studies you have
 provided.  I have one minor frustration with the version I am using:  http://www.sanskrit-lexicon.uni-
koeln.de/scans/MWScan/2014/web/webtc2/index.php LB Why does it always default to 
'Headword or Text'? Every time I open the page, I have to reset it to 'Headword only'. I am sure that I and 
other users would use 'Headword only' fare more frequently that the other option. Would you consider 
changing the default setting?  Thanks in advance - have a great Xmas and New Year.  Yours,  ...
```
It should be possible to do this with a browser Cookie.

**Comment by gasyoun** [comment]
> browser Cookie.

I guess just defaulting it to headword would be enough. No need of cookie. I agree. That mode makes more sense by default, had the same thoughts.

**Comment by funderburkjim** [comment]
Default now changed to 'headword only'.

Didn't work with cookies - it is trickier to do since I don't understand cookie javascript coding very well.

**Comment by gasyoun** [comment]
> Didn't work with cookies - it is trickier to do since I don't understand cookie javascript coding very well.

No need, @juhnowski is back and he is thinking or remaking the whole UI totally. Making it mobile friendly as well, but let him himself tell the story, he'll come.

**Comment by juhnowski** [comment]
Hello, I have some idea and best practices to use React.JS and React Native with Redux in UI. Today, may be tomorrow I will create new issue with description of my vision of ways of improvement UI.
