### ISSUE TITLE
abbr.html update

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#36]
As I see http://www.sanskrit-lexicon.uni-koeln.de/monier/abbr.html it's not equal to the printed book. How can I update it?

```
A1.	Atmane-pada
abl.	ablative
above	a reference to some preceeding word (not necessarily in the same page)
acc.	accusative
accord.	according to
add.	additions
A1di-p.	Adi-parvan of the mahA-BArata
adj.	adjective (cf. mfn.)
adv.	adverb
Aeol.	AEolic
```

![atmannn](https://cloud.githubusercontent.com/assets/80761/23132233/f966f7d4-f79d-11e6-8b58-09aa85d144c8.PNG)

**Comment by funderburkjim** [comment]
The key input file is [mwab_input.txt](http://sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/mwaux/mwab/mwab_input.txt).

When this file is modified, a script puts it into a sqlite file, which is used by the displays to generate tool tips for the abbreviations.

AFAIK, this is the only use of these abbreviations.  There is no current display of them (the link you gave is based on a prior version of the mwab_input.txt file).

So, if some of them need changing, the mwab_input.txt file is the place to change.  You could download that file, revise it, and send it back (or maybe put it in MWS repository).  Then I could install at Cologne.

Here are the notes on format of the mwab_input.txt file:
```
 File has lines, each line has 2 tab-delimited fields:
   id  The abbreviation as used in MW
   data an xml fragment: <id>X</id> <disp>Y</disp>

```
This should be enough info to get you started.

Probably, if we attend to the csldoc system, the abbreviations would be something to add.

**Comment by drdhaval2785** [comment]
@gasyoun Still game? If not, close.

**Comment by gasyoun** [comment]
> Still game?

Guess, yes, @funderburkjim ?

**Comment by funderburkjim** [comment]
The abbr.html file from monier directory at cologne has been uploaded
to this MWS repository, at [mwabbreviations/abbr.html](https://github.com/sanskrit-lexicon/MWS/blob/master/mwabbreviations/abbr.html)

This abbr.html file is not used anywhere in current displays.

The current *official* list of MW abbreviations (the basis of the tooltips in the
displays) is in the csl-pywork repository, at url
[mwab_input.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/mw/pywork/mwab/mwab_input.txt)

**Comment by gasyoun** [comment]
> This abbr.html file is not used anywhere in current displays.

So be it, let it be, thanks, closing.
