### ISSUE TITLE
MW o_vs_O Highest probability (Limited ed.)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#38]
I want to learn Radha how to treat https://drdhaval2785.github.io/o_vs_O/output2/MW.html and so it begins. @drdhaval2785 please correct me if I should use the standard format you've developed for batch submissions, could not locate it right now. If I do a copypaste from the HTML file I get

> `1	9197	apatyasac	apatyasAc	अपत्यसच्	अपत्यसाच्	MW	GRA,GST,PW,PWG,VCP`

that is not quite equal to what Dhaval has developed. Rewriting it manually each time is a bad idea, as I intent to bring the Highest probability cases with help from Harvard to an end in a year from now. I could ask @juhnowski to help recode in on the fly, so I ask for your help and advice. I hope @funderburkjim will be ok to what we develop here.

So it this `1	9197	apatyasac	apatyasAc	अपत्यसच्	अपत्यसाच्	MW	GRA,GST,PW,PWG,VCP` case `apatyasAc` is right, and `apatyasac` does not make much sense and is a print error, as it is in the printed book (and not just in the file).

> `2	9563.2	aparityajya	aparityAjya	अपरित्यज्य	अपरित्याज्य	MW	PW,SCH,STC`

Is a more interesting case, it's a false alarm. MW contains a number of "illegal" words that are known. 

`(H1) अ-परित्यज्य [p= 1314,1] [L=9563.2]	mfn. = (or v.l. for) अ-परित्याज्य.`

@drdhaval2785 is there any easy way to clean all these `v.l.` cases out or mark them in a color?

Similarly `Abhyāse, ind. near; more correctly written abhyāśe.`, but with `more correctly` it's only manual markup. So I need a method to note words that are actually ok, so they would not show up in future regenerations.

> `4	18893	avipraRaSa	avipraRASa	अविप्रणश	अविप्रणाश	MW	PW,STC`

Here comes the first error in the file itself. First I open

![mw](https://cloud.githubusercontent.com/assets/80761/26656268/0561cbdc-4667-11e7-85e5-73baeca9f4c1.PNG)

the "default" links, it's the quickest way and compare the meanings. So I see that MW's `m. (said of the actions) the not perishing, continuing through their fruits MBh.  xv, 923.` is equal to `m.  das nicht spurlos Vorübergehen.` As MW is a translation of PW, that's no wonder. As the dictionary I suspect is MW, I first open it. And there I see अ-विप्रणश [p= 109,2], that means after opening the page scan I'll look in the 2nd (out of 3) columns. But that's wrong. The number is wrong (in this case, not too often) and it should have been [p= 109,1].

![avip](https://cloud.githubusercontent.com/assets/80761/26656376/721e79dc-4667-11e7-98d9-fac6c9bcee74.PNG)

There I see that in the printed book everything fine. Printed MW is equal to printed and digital PW. But there is an error in the digital version of MW. That's it!

> 5	28674	ijyaSIla	ijyASIla	इज्यशील	इज्याशील	MW	SHS,VCP,WIL,YAT

ijyASIla is right because ijyaSIla has lost that the base is ijyA and not ijya (starting from the middle of the article:
![ijya](https://cloud.githubusercontent.com/assets/80761/26656520/1f0277e8-4668-11e7-8122-dc2eeb87b438.PNG)

Similarly in `7	29989	Ihatas	IhAtas	ईहतस्	ईहातस्	MW	BEN,SHS,WIL,YAT`

> 6	29726	ILita	Ilita	ईLइत	ईलित	MW	BOP,SHS,VCP,WIL,YAT

Same word, different orthography.
![taa](https://cloud.githubusercontent.com/assets/80761/26656745/0b4c14ba-4669-11e7-89a2-03da375a8810.PNG)

> 8	40168	elAvali	elAvalI	एलावलि	एलावली	MW	PW,PWG

It's a plant name, so harder. Where does एलावली->एलावलिhttps://github.com/drdhaval2785/SanskritSpellCheck/blob/master/o_vs_O/output2/PWG.txt Dhaval comes from? But it's f., so i->I, right, @drdhaval2785 ?

> 9	41297	OzaDAvali	OzaDAvalI	औषधावलि	औषधावली	MW	PW,PWG

Same.

> 10	44206	karasUtra	kArasUtra	करसूत्र	कारसूत्र	MW	BHS,PW

False alarm, two different articles.

**Comment by drdhaval2785** [comment]
This code was written before we standardized the correction submission
methods. I will write a script to generate standard correction format with
instructions how to use it. Give me a day.

**Comment by funderburkjim** [comment]
> 1 9197 apatyasac apatyasAc अपत्यसच् अपत्यसाच् MW GRA,GST,PW,PWG,VCP

Here is my guess of the 'fields'
* 1 == a sequence number
* 9197 == MW L-number
* अपत्यसच्  = old key1, in Devanagari
* अपत्यसाच्  = new key1, in Devanagari
* MW = the dictionary under study
* GRA,GST,PW,PWG,VCP   comma-delimted sequence of dictionary codes

All fields separated by spaces

If this interpretation is right,  then this format would be quite fine as a change-submission.

**Comment by drdhaval2785** [comment]
1 9197 apatyasac apatyasAc अपत्यसच् अपत्यसाच् MW GRA,GST,PW,PWG,VCP

Here is my guess of the 'fields'

   - 1 == a sequence number
   - 9197 == MW L-number
   - अपत्यसच् = old key1, in Devanagari

ok till here.


   - अपत्यसाच् = new key1, in Devanagari

This is the corresponding headword with only length of vowel difference in
rest of dictionaries like GRA,GST,PW.....

**Comment by gasyoun** [comment]
>  I will write a script to generate standard correction format with
instructions how to use it

Thanks, Dhaval.

**Comment by drdhaval2785** [comment]
Corrections had been made based on o_vs_O. Closing.
