### ISSUE TITLE
ā*di (accents in MW)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#39]
Exploring https://github.com/sanskrit-lexicon/Cologne/issues/156 I found out that the MW web display in `ādi` has `gṛhā*diyukta` and `khaṭvā*diḥ`. If it's only because we miss it in the font, I can add it to the font (ask a designer to do it). @funderburkjim or let's pretend we did not see it?

![adi](https://user-images.githubusercontent.com/80761/28645148-1ff4aefe-7265-11e7-9c43-26316c9eed2c.PNG)

**Comment by funderburkjim** [comment]
To understand what is going in with the asterisk after a-macron (),
we have to look at the scan and the digitization:
![image](https://user-images.githubusercontent.com/6393033/28801382-40b2cbf4-761f-11e7-861c-42c968149a8b.png)

#### Digitization:
* gṛhā*diyukta   in mw.xml is `<s>gfhA<srs/>diyukta</s>`
* khaṭvā*diḥ  in mw.xml is `<s>KawvA<srs/>diH</s>`

We can see that the digitization codes a-circumflex  **â** as 'A<srs/>'  (where the 'A' is long-A from SLP1.

The vowel-circumflex in MW print means two things:
* the vowel is a long vowel
* the vowel occurs as a vowel-sandhi 

So in gṛhâdiyukta = gṛh**a** + **ā**diyukta, for example.

The `<srs/>` in the xml digitization is an acronym 'simple-replacement-sandhi'. 

#### Rendering `<srs/>`
In the conversion of the xml to html, we have to decide how to render `<srs/>`.  The choice currently
made is to render `<srs/>` as an asterisk.  This is done in the 'disp.php' program as part of the MW display.

It would be easy to render `<srs/>` as the empty string.   That would get rid of the '*'. For example,
that would leave us with `gṛhādiyukta` in the display.

**Comment by drdhaval2785** [comment]
Display is just fine.

**Comment by Andhrabharati** [comment]
This is what the book says about these characters (symbols)-

![image](https://user-images.githubusercontent.com/75209130/103645417-f67fa980-4f7d-11eb-89bd-448fb6b71a20.png)

the left character denoting the left-side word vowel and the right character denoting the right-side word in the sandhi operation. If the character is thin, it denotes a short vowel and if it is thick, it denotes a long vowel.

Plenty of such gimmicks could be seen in olden days print books. (Each having its own "ideas").
Now we can live with the present IAST notations.
