### ISSUE TITLE
Replica of Printed Fonts for Web Display

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#4]
Jim, if you want to (I would do myself if I only could) we can make http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/indexcaller.php look like http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/servepdf.php?page=407
For headers use https://www.dropbox.com/s/ag2kfaam9mjtniu/Clarendon%20Indologique.ttf?dl=0 (it's not as bold, but still same family). If needed, will make bold one day when I'll get rich enough to order it. For main text Old Standart can be used until I found out the real one.

**Comment by drdhaval2785** [comment]
@gasyoun Still relevant?

**Comment by gasyoun** [comment]
Yes, only partly solved and easy solvable, when @funderburkjim is around.

**Comment by funderburkjim** [comment]
I am less eager to continue adding more and more web fonts.   There's a good reason 
for Siddhanta  (better ligatures for Devanagari) web font.   But reason for other web fonts 
much less compelling to me.

At least for the time being,  Marcis interest in font beautification should be developed  by others who have a real interest.

**Comment by gasyoun** [comment]
> But reason for other web fonts much less compelling to me.

All I ask is that the techniques used in one dictionary be scaled to others.

**Comment by gasyoun** [comment]
> font beautification should be developed by others who have a real interest.

Do you give a go? Can I experiment in the field and you'll approve the push if agreed?

In Advanced search italics is not working:

![ghuna](https://user-images.githubusercontent.com/80761/115136356-f46ec180-a027-11eb-938b-c34cf983e2fb.png)

I checked view-source:https://sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/webtc/font.css

As I can see in view-source:https://sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/fonts/oldstandarditalic.otf the font is there, I do not understand why it does not use the italics but only imitates it @alex-bukach .

You can see in Word how a real italics in this font looks like:

![ghunass](https://user-images.githubusercontent.com/80761/115136401-2c760480-a028-11eb-97ef-7826ec44a0e7.png)

And none of it works at https://sanskrit-lexicon.uni-koeln.de/simple/ because the only font there is `siddhanta_deva`

```
@font-face { 
 src: url(../../fonts/siddhanta.ttf);   /* location specific */
 font-family: siddhanta_deva;
}
```

**Comment by funderburkjim** [comment]
Made small change in display (for MW) to deal with this.
oldstandardcharter (computed font = Old Standard Indologique) for IAST output in MW.  
It is currently also used for general italic text.

Note 1:  I have verified this for both basic display and simple-search displays with Chrome Browser.
             Also with basic display in Edge browser.  
Note 1a: However, with Edge browser and simple-search, these
             italic texts do not display with oldstandard, but with Times New Roman.  Have tried Ctrl-F5 to refresh.
             Maybe there is some subtle error in [csl-apidev/css/basic.css](https://github.com/sanskrit-lexicon/csl-apidev/blob/master/css/basic.css)  that Chrome handles but not Edge?

Note 2:  The changes made are
* For Basic display:  [basicdisplay.php and font.css](https://github.com/sanskrit-lexicon/csl-websanlexicon/commit/c8108ffba5e0ac19675f7e74ffe527b0c259060e#diff-a4174ec386a754fc68953dd41acf268fa71bfed28e500f2974ceed84f5898cab)
* For simple-search, same basicdisplay, and [basic.css](https://github.com/sanskrit-lexicon/csl-apidev/commit/6066c12af33c5b95597a8119382c06438ee5884e#diff-97869b799fd6aa0b10e39131fcabc0c470197bcc381b1c0a6594e412af0aced5).

**Comment by gasyoun** [comment]
> Maybe there is some subtle error in csl-apidev/css/basic.css that Chrome handles but not Edge?

@alex-bukach any clue about Edge or Firefox?

It works now well in simple in Chrome.

![tara](https://user-images.githubusercontent.com/80761/115945392-47cb8e80-a4c4-11eb-9743-500ae93e3e5a.png)

Firefox

![fireff](https://user-images.githubusercontent.com/80761/115945419-692c7a80-a4c4-11eb-9205-63ab673bb7af.png)

**Comment by Andhrabharati** [comment]
@funderburkjim / @gasyoun,

Is this issue closable now?
