### ISSUE TITLE
*ंश

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#41]
(H3) नवा*ंश [p= 531] : m. = °व-भाग Var.  [L=104707]

![nava](https://user-images.githubusercontent.com/80761/30582775-98ef80ca-9d2d-11e7-9468-7995f8761265.PNG)

Because of the *ं devanagari is broken. Guess nothing we can do about it, @funderburkjim

**Comment by funderburkjim** [comment]
We could change the display logic to just ignore the `<srs/>` coding.

**Comment by gasyoun** [comment]
> just ignore

Let's try to.

**Comment by funderburkjim** [comment]
Modification to disp.php.
Remove `<srs/>` and `<srs1/>` tags when requesting Devanagari output.

Example:
![image](https://user-images.githubusercontent.com/6393033/32302254-1a3d0cfc-bf38-11e7-9a25-7f9cc1ff3c62.png)

The tags remain (displayed as asterisk) when output is not Devanagari, for instance in Roman Unicode:
![image](https://user-images.githubusercontent.com/6393033/32302287-475db088-bf38-11e7-9332-c69813e9bde4.png)

**Comment by gasyoun** [comment]
> Remove <srs/> and <srs1/> tags when requesting Devanagari output.

Good idea.
