### ISSUE TITLE
Mod. Germ. ga0hne 

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#42]
> ([cf. χαίνω, χανῶ, χώννυμι ; Old Germ. ginēm, ginōm ; Mod. Germ. ga0hne ; Angl.Sax. cina, cinan ; Lat. cuniculus, canalis.])

a0 ->ä

In `<etym>gino1m</etym>` on web is `ginōm`, but `<etym>ga0hne</etym>` remains unsolved.

and

`to foment, soften SāmavBr.  : Desid. of Caus. sisvedayiṣati, Gr.: Desid. sisvitṣati ib. : Intens. seṣvidyate, seṣvettiib. [cf. Gk. ἱδρώς ; Lat. sūdor, sUdare ;Angl.Sax. swât ; Eng. sweat ; Germ. Schweiss, schwitzen.]`

Lat. sūdor, sUdare -> Lat. sūdor, sūdare

and

Lat. suadeo, and under svAdu.

In `Lith. sesú` can't reproduce in Unicode

![u](https://user-images.githubusercontent.com/80761/32195765-5f9e7ffc-bdcf-11e7-992c-918b68684dff.PNG)

Germ. sss. -> Germ. süss.

![svadu](https://user-images.githubusercontent.com/80761/32195869-c164868c-bdcf-11e7-8c8a-26c13bb374e6.PNG)

` Lit. spe0ti`

`Germ. spe0hôn, spa0hen`

`Lith. stē4gti` -> `Lith. stē4gti` should contain a grave accent, but can't locate in Unicode https://en.wiktionary.org/wiki/%C4%92

**Comment by funderburkjim** [comment]
### `<etym>`
Probably most of these occur within the `<etym>` tag in mw.xml.

Thus tag occurs in about 900 entries; although in a given entry it typically occurs several times.

Of these, the AS (letter-number) coding appears in 315 lines.

It would be good to replace all these AS codings with Unicode.

If you are game to tackle these,  I'll start by making some lists.  Then we can also develop some UI to make the change process more efficient, if that seems warranted.

**Comment by gasyoun** [comment]
> This tag occurs in about 900 entries; although in a given entry it typically occurs several times.

Exactly.

> If you are game to tackle these, I'll start by making some lists. Then we can also develop some UI to make the change process more efficient, if that seems warranted.

If you can change what's already noted - sure, I'm in.

**Comment by drdhaval2785** [comment]
Everything is converted to IAST. Closing.

**Comment by Andhrabharati** [comment]
>In Lith. sesú can't reproduce in Unicode

Here it is (though not exactly the way printed, guess this is the intended one)-

0xE720 | LATIN SMALL LETTER U WITH RING ABOVE AND ACUTE | 0075 + 030A + 0301 | ů́

(sesů́)

**Comment by Andhrabharati** [comment]
> 
> ### `<etym>`
> 
> Probably most of these occur within the `<etym>` tag in mw.xml.
> 
> This tag occurs in about 900 entries; although in a given entry it typically occurs several times.
> 
> Of these, the AS (letter-number) coding appears in 315 lines.
> 
> It would be good to replace all these AS codings with Unicode.
> 
> If you are game to tackle these, I'll start by making some lists. Then we can also develop some UI to make the change process more efficient, if that seems warranted.

Dhaval has requested me to give the corrections done at my end for all these ety. lines, and I need to prepare some comparison and pass on my data to him to incorporate the corrections whereever needed.
