### ISSUE TITLE
Old Germ. glat

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#43]
Words in etymologies should be left in italics, as in book.

Old Germ. glat -> Old Germ. _glat_

![italics](https://user-images.githubusercontent.com/80761/32194713-35e9b918-bdcc-11e7-9f5d-3d833b126a67.PNG)

In `Old Germ.` only word `Germ.` is tagged, Old is left out. Let's check if all Old belong where they should be.

Similarly in `N.B.` in `(N.B. in the following comp. own stands for one's own) . [L=257781]`
N. is marked, but should be N.B. marked together.

**Comment by funderburkjim** [comment]
Again, these words occur within the `<etym>` tag.  A change to disp.php shows these in italics:

![image](https://user-images.githubusercontent.com/6393033/32302936-ccf7e8aa-bf3b-11e7-8a2b-6ab5c753cc82.png)

**Comment by gasyoun** [comment]
> Again, these words occur within the <etym> tag. A change to disp.php shows these in italics

Great.

> In Old Germ. only word Germ. is tagged, Old is left out. Let's check if all Old belong where they should be. Similarly in N.B. in (N.B. in the following comp. own stands for one's own) . [L=257781]
N. is marked, but should be N.B. marked together.

What about this part?

**Comment by gasyoun** [comment]
> m. a hog (= kiṭi) Uṇ.  iv, 144 [L=50514]

kiṭi should be italics as well.

![kiri2](https://user-images.githubusercontent.com/80761/32352355-f87e9b08-c031-11e7-8641-558c4c5cf1ea.PNG)

**Comment by funderburkjim** [comment]
`<s>kiwi</s>` is how `kiṭi` is coded in mw.xml.

Text within the `<s>` (Sanskrit) tag is rendered in displays according to the output display options that the user chooses.  E.g., Devanagari, IAST, etc.

For instance, if Devanagari output is chosen, then the output appears as
![image](https://user-images.githubusercontent.com/6393033/32463274-50161cc6-c30a-11e7-8b3e-d4d6f74501b2.png)

Italics would not be appropriate for Devanagari output.
It might be possible to add italic styling to `<s>` text if the user output choice differs from Devanagari, but is it worth the trouble?

**Comment by gasyoun** [comment]
> It might be possible to add italic styling to <s> text if the user output choice differs from Devanagari, but is it worth the trouble?

It sure is. We want to have 1 to 1 for comparing with the book. Right now too many things at once look too different. That is the reason I'm aware of people still using the .pdfs...

**Comment by funderburkjim** [comment]
> In Old Germ. only word Germ. is tagged, Old is left out

The tagging here is the abbreviation tag `<ab>`.  Current xml is `Old <ab>Germ.</ab>`.  When disp.php renders this into HTML,  it does the following to the content of the `<ab>`.
* adds a tooltip  (text of tooltip is based on mwab_input.txt).
* adds coloring to the text.

There are two ways we could vary this in order to have 'Old' and 'Germ' appear in the same font color.

1) retag mw.xml to have `<ab>Old Germ.</ab>` and add the corresponding 'Old Germ.' to list of abbreviations.
2) Remove the coloring from the HTML rendering of the `<ab>` tag.  This way, both 'Old' and 'Germ.' would look the same, and if the mouse hovered over 'Germ.' the 'German' tooltip would show.  
   * The coloring would be removed from ALL abbreviations, not just the 'Germ.' abbreviation.

**Comment by gasyoun** [comment]
> retag mw.xml to have <ab>Old Germ.</ab> and add the corresponding 'Old Germ.' to list of abbreviations.

The only way out.

**Comment by gasyoun** [comment]
>kapi [cf. Gk. κήπος κεῖπος κήβος; Old Germ. affo; Angl.Sax. apa; Eng. ape.] [ID=43442.1]

It is not `Germ.`, but `Old Germ.`
`Angl. Sax.` instead of `Angl.Sax.` - all around the dictionary, noy only here.

> Goth. aljis, Theme alja; Gk. ἄλλος

It's `Theme` indeed in the book as well, but can not understand, there is no such abbreviation.

>manyā f. du. and pl. the back or the nape of the neck (musculus cucullaris or trapezius), AV. ; VS. ; Suśr.  [ID=157954]
Partly markup for `musculus`.

**Comment by Andhrabharati** [comment]
My file mentioned in the Lithuanian thread has dealt with all issues in ety. parts, no tagging, wrong tagging,  wrong letters, ... ...

It should be clearing all such issues individually posted.

It should've been just a single issue "etym. related", the way I handled it.

**Comment by gasyoun** [comment]
> It should've been just a single issue "etym. related", the way I handled it.

We do language by language or all at once. Your data entry skills would not be enough to cover all the languages anyway.

**Comment by Andhrabharati** [comment]
Thanks for the comment, and I wish I could see your "all at once" work sometime soon.
[This clearly tells that my post at that thread hasn't been looked into.]

**Comment by Andhrabharati** [comment]
> 
> > Goth. aljis, Theme alja; Gk. ἄλλος
> 
> It's `Theme` indeed in the book as well, but can not understand, there is no such abbreviation.
> 

It is not Theme, but should be "Them."! 
Pl. see this from MW72 abbreviations.

![image](https://user-images.githubusercontent.com/75209130/103355898-79fc4f00-4ad5-11eb-9f43-6a09ff188575.png)

**I would just say that one does need to know the languages, but a **WILL** to get things rendered correct (and that's how old scripts were deciphered by later linguists/Archeologists/...), and like to put a stop in discussing about the topic.**

**Comment by gasyoun** [comment]
> It is not Theme, but should be "Them."!

Your eyes seem sharp.

> not listed in Abbr.s

These are the most valuable abbreviations, the not listed ones.

**Comment by Andhrabharati** [comment]
Now I think you are coming to know how we work.

**Comment by Andhrabharati** [comment]
This issue contains **NO points** that need future attention, and is closable now.
