### ISSUE TITLE
yesterdayRV.

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#44]
Are there spaces after words and before abbreviations? `yesterdayRV.` example shows us not always.

(H1) hyas [p= 1306] : ind. (g. svar-ādi) yesterdayRV.  &c &c [cf.Gk. χθές ; Lat. hesternus, heri ; Goth. gistra (-dagis) ; Germ.ge0staron, gestern ; Angl.Sax. geostra ; Eng. yester (-day).][L=264653]
--

![hyas1](https://user-images.githubusercontent.com/80761/32194940-e0ad77ea-bdcc-11e7-9b41-6f4ecf47060f.PNG)

![hyas2](https://user-images.githubusercontent.com/80761/32194944-e33c5418-bdcc-11e7-8e12-4df43519ca79.PNG)

and in `woundMuṇḍUp.`

**Comment by funderburkjim** [comment]
Modified disp.php for mw to add spaces around `<ls>X</ls>`.
Result:
![image](https://user-images.githubusercontent.com/6393033/32303136-14f2446a-bf3d-11e7-9af3-a60db8cb3aff.png)

**Comment by gasyoun** [comment]
> Modified disp.php for mw to add spaces around <ls>X</ls>.

All entries or just this one? It's an all-round issue.

**Comment by gasyoun** [comment]
> Thus, when a change is made to disp.php, it applies to the display of any and all records of mw.

Oh, sure, great.

**Comment by Andhrabharati** [comment]
> 
> 
> Modified disp.php for mw to add spaces around `<ls>X</ls>`.
> Result:
> ![image](https://user-images.githubusercontent.com/6393033/32303136-14f2446a-bf3d-11e7-9af3-a60db8cb3aff.png)

We should have a comma here- not a space, after yesterday.

**Comment by gasyoun** [comment]
> comma here- not a space,

So a comma AND space you wanted to say.

**Comment by Andhrabharati** [comment]
right. that is implied.
a comma, a full-stop, or a semi-colon would always have a space after (unless in a number).
