### ISSUE TITLE
śarīram,deham,prā*ṇān spacing lost

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#46]
(H1) hā 3 [p= 1296] :
cl.3 P. (Dhātup.  xxv, 8) jahāti (rarely cl.1. jahati 3. du. jahītaḥ Impv. jahīhi [or jahāhi Pāṇ.  6-4, 117] ; jahītāt AV.  ; Pot. jahyāt AV.  &c ; pf. jahau, jahuḥ RV.  &c ; jahe Br.  ; aor. ahāt ib. &c ; ahāsīt Gr. ; 3. sg. ahās RV.  ; ahāsi AV.  ; hāsiṣṭa ib., ; fut. hātā Gr. ; hāsyati,°te AV.  &c , jahiṣyati MBh.  &c ; inf. hātum ib. ; ind.p. hitvā. [q.v.] RV.  &c ; hitvī °tvāya RV.  ; -hītvā Gr. ; -hāya Br. , hīyam TS. ), to leave, abandon, desert, quit, forsake, relinquish (with śarīram,deham,prā*ṇān,asūn,jīvitam &c - " to die ") RV.  &c , &c  ; 

`śarīram,deham,prā*ṇān,asūn,jīvitam` spacing is gone, where?

![jivitam](https://user-images.githubusercontent.com/80761/32195378-2fe391a4-bdce-11e7-96bd-21b93074e12f.PNG)

Similarly in `Intens. sāsvaryate, sāsvartiib. [cf. Gk. σῦριγξ ;Lat. susurrus ; Germ. schwirren, Schwarm ; Eng. swarm.]`

There is `;Lat.` instead of `; Lat.` and `sāsvartiib.` instead of `sāsvarti ib.`

**Comment by funderburkjim** [comment]
modified disp.php to add a space after `>[,.;]`.  That handles this case, and should handle other similar cases, and shouldn't have unwanted side effects.
The 'hA' example now looks like:
![image](https://user-images.githubusercontent.com/6393033/32303414-de3e377e-bf3e-11e7-96a2-5ff6b59192aa.png)

**Comment by gasyoun** [comment]
> modified disp.php to add a space after >[,.;]. That handles this case, and should handle other similar cases, and shouldn't have unwanted side effects.

I hope you document it as well, so when we build the universal display, we remember why it's there in MW.

**Comment by drdhaval2785** [comment]
Spacing now in mw.txt also. Closing.
