### ISSUE TITLE
" a pile " -> ‘a pile’

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#48]
> (H2) kiri a [p= 283] : m. " a pile " » ākhu-kirí [L=50513]

Worth doing, @funderburkjim ?

**Comment by funderburkjim** [comment]
The mw.xml coding is `<quote>_a_pile_</quote>`.  As with `<etc/>`, the HTML rendering of `<quote>` and `</quote>` is determined by the display function disp.php.   
Currently:
* The '_' are changed to spaces, resulting in `<quote>a pile</quote>`
* This is changed to Html   `&quot; a pile &quot;`.

What do you suggest as alternate?

**Comment by gasyoun** [comment]
> What do you suggest as alternate?

Before:
&quot; a pile &quot;.

After:
&quot;a pile&quot;.

**Comment by funderburkjim** [comment]
White space now trimmed from quoted string before display.

![image](https://user-images.githubusercontent.com/6393033/32629753-3ada7d56-c568-11e7-9126-659afc43c027.png)

**Comment by gasyoun** [comment]
> White space now trimmed from quoted string before display.

Perfect.
