### ISSUE TITLE
whether-or-or -> whether–or–or

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#49]
> also the kim prefixed to verbs with a similar meaning (e.g. kim-adhī*te, he reads badly Pāṇ.  8-1, 44 Kāṡ. ) kim-uta, or kim-uta-vā or kim-athavā-uta, whether-or-or R.  Ṡak.  Bhartṛ.  &c (cf. utá.) [L=50294.1]

Minus sign not equal to hyphen.

![kimuta](https://user-images.githubusercontent.com/80761/32353569-f56207c0-c036-11e7-868d-da6daf32744a.PNG)

**Comment by funderburkjim** [comment]
This can be corrected by using em-dash character,  
I've submitted correction to do this.

There may be similar instances under yaTA, taTA.

**Comment by gasyoun** [comment]
> I've submitted correction to do this.

Perfect.
