### ISSUE TITLE
Monier Williams Grammar Markup

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#5]
How can I make a list in MW with words that appears only at the end of compounds. Will"ifc" help me (884 pieces)? Like -da, -pa, -ja, -ra (end of compounds).
I would want to have a list of words like ज 76157 that change meaning when at the end or beginning of a word <c>after_an</c>~ <ab>adv.</ab>~<c>or_adverbial_word</c></p> <c>_born_or_produced</c> or like अ 4 in the beginning - it's not an upasarga, still could be in my case called a prefixoid. I do not see no markup in the printed book and no markup in the digitization as well.
And <ab>ifc.</ab>~ <lex type="hwifc">f<p><s>A</s></p>.</lex> looks messy in the code and bad on the web display as well. "mf(आ)n." is not we see it in the book. In printed book we have a mix of mf(ā)n. inside the text and द as header - right now we can only have all devananagari or all IAST kind of thing. Can we have a mode to look similar to the book? pakṣa is Pakṣa (wing, pinion) in printed - original anywhere stored? Are all capital letters lost? In which mode I can get the data about accents used in MW?
I started exploring again and I see that MW has LEX (<lex>mfn.</lex>, <lex type="inh">mf<p><s>A</s></p>n.</lex>)
What's the difference between <lex>f.</lex> and <lex type="inh">f.</lex>? http://www.sanskrit-lexicon.uni-koeln.de/mwupdate/mwxmldownload/mwtags.html#lex
First "aBavya" has <lex type="inh">mfn.</lex>. But there are 2 more, so can (I would say should) we add (invisibly for the eye, but understandable for the coding end decoding purposes) <lex type="invisible">mfn.</lex> to 311530 and 311530.1?
Have you ever tried to regex and find grammar info for every word?
Right now what I miss in my manipulations with MW:
- capital letters (for those words, that have them in the book)
- accents
- words breakings (h2?)
- grammar data (mnf. kind of things for every single word)
  Any chance to get some advice? Thanks.

**Comment by Andhrabharati** [comment]
@funderburkjim / @gasyoun,

Is this issue closable now?
