### ISSUE TITLE
Review of MW abbreviations

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#52]
Due to various recent discussions on abbreviations in MW, such as #45, I've attempted a thorough review of this topic.  In the process, several hundred coding changes have been made.

The results are in the [mwabbreviations](https://github.com/sanskrit-lexicon/MWS/tree/master/mwabbreviations) directory of this repository.  The readme file there describes the files.  The [compare.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwabbreviations/work/compare.txt) file has the most comprehensive overview; some clues to reading this file are in the readme mentioned above.

**Comment by funderburkjim** [comment]
### Question on Vārttika 

There are many cases where Vārttika is marked as an abbreviation in the MW digitization.  But this 
markup is surely flawed.   Before I can undertake to improve the markup, I need to have someone (@SergeA or @drdhaval2785 ) explain how to read these references.

There are over 1000 instances in the digitization where markup such as `<ab>Va1rtt.X</ab>` appears.
X represents the *extra* information contained within the scope of the `<ab>` tag.  
Almost all of these have a nearby mention of a Panini sutra, either before (more common) or after the mention of Vārttika.   

The following appears to be the relevant meaning Vārttika:
> n. an explanatory or supplementary rule, critical gloss or annotation (added to a grammatical or 
philosophical सूत्र and defined to be " the exposition of the meaning, of that which is said, of that which 
is left unsaid, and of that which is ill or imperfectly said " ; the term वार्त्तिक is, however, especially 
applied to कात्यायन's critical annotations on the aphorisms of पाणिनि's grammar, the object of 
which is to consider whether पाणिनि's rules are correct or not, and to improve on them where this 
may be found to be necessary ; and also to similar works on various matters 
by कुमारिल, सुरेश्वर &c ; cf. तन्त्र-व्°, श्लोक-व्°)

**Comment by funderburkjim** [comment]
### Examples where Vārttika appears without any extra information


```
hw = dAruvaha
<ls>Pa1n2._6-3_,_121</ls> <ab>Va1rtt.</ab>
```
![image](https://user-images.githubusercontent.com/6393033/32526103-9efd9832-c3f5-11e7-9aa8-254b1dc952d5.png)

```
hw = drORa
<ls>Pa1n2._5-1_,_52</ls> <ab>Va1rtt.</ab> <ls>Pat.</ls>
```
![image](https://user-images.githubusercontent.com/6393033/32526155-de7ca624-c3f5-11e7-846f-be2e154bb214.png)

```
hw = kazwAya
<ls>Pa1n2._3-1_,_14_;_and</ls> <ab>Va1rtt.</ab> <ls>Vop._xxi_,_10.</ls> 
```
![image](https://user-images.githubusercontent.com/6393033/32526240-4bc0a06e-c3f6-11e7-947b-5a93c2e84d86.png)

**Comment by funderburkjim** [comment]
#### Examples where Vārttika is followed by a number
```
hw = kavarapucCa
<ls>Pa1n2._4-1_,_55</ls> <ab>Va1rtt._2.</ab>
```
![image](https://user-images.githubusercontent.com/6393033/32526412-24d74434-c3f7-11e7-9dc0-3cc235bd5e9c.png)

```
hw = parisOvIram
<ls>Pa1n2._6-2_,_33</ls> <ab>Va1rtt._1</ab> <ls>Pat.</ls>
```
![image](https://user-images.githubusercontent.com/6393033/32526505-8fa1adf4-c3f7-11e7-8ea3-b701e6356bc1.png)

```
hw = duHKajAta
<ls>Pa1n2._4-1_,_52</ls> <ab>Va1rtt._5</ab> <ls>Pat._;_vi_,_2_,_170.</ls> 
```
![image](https://user-images.githubusercontent.com/6393033/32526555-e789d488-c3f7-11e7-9906-ec970ff0c474.png)

**Comment by funderburkjim** [comment]
#### How to read the examples?
Again, the first question is simply how to read such examples as above.
For instance, does Varttika always mean the same thing in these examples? or does it depend ?
Should Varttika be treated as a literary source or an abbreviation. or does it depend ?
In cases where it should be treated as a literary source, is it always THE SAME literary source, or, is it 
sometimes one source and sometimes another source?

**Comment by drdhaval2785** [comment]
To put things in perspective,

1. Panini wrote Ashtadhyayi.
2. Katyayana wrote vArttikas on them to supplement whatever was missing in
AS.
3. Patanjali in his Mahabhashya (MB) examined the validity of vArttikas and
accepted or rejected them.

Varttikas have not come down to us as separate book. They are preserved
only as quotations in MB. So for referring to a vArttika, usually people
say - look for this vArttika in MB under the Paninian sutra A.B.C.

The same is followed by MW.

E.g. kabarapucCa
Here 'कबरमणिविषशरेभ्यो नित्यमिति वक्तव्यम्' vArttika is mentioned in MB
under 4.1.55. There are more than one vArttika mentioned in this sUtra in
MB. So they are referred to by a number. If there is only one vArttika, no
numbering is needed.

So the reference is
Pan. 4.1.55 vArttika 2.

See http://ashtadhyayi.com/sutraani/4/1/55 under Mahabhashyam.

कबरमणिविषशरेभ्यो नित्यम् - (भाष्यम्) कबरमणिविषशरेभ्यो नित्यमिति वक्तव्यम्।
कबरपुच्छी, .....

**Comment by drdhaval2785** [comment]
Pat at the end of some reference is referring to Patanjali, the author of
MB.

**Comment by gasyoun** [comment]
> There are more than one vArttika mentioned in this sUtra in MB. So they are referred to by a number.

Oh that's why there is 2...

> Pat at the end of some reference is referring to Patanjali, the author of MB.

That means a useless addition?

**Comment by SergeA** [comment]
> That means a useless addition?

You are free to call Patanjali's Mahabhashya "a useless addition", but it was not so for Monier. When he mentions Pat. this means he considers some info provided in the Pat. commentary to be useful.

> how to read such examples as above.

**Pāṇ.** is a 1st level independent source. 
Pāṇ. sūtras are very brief, few words in each. 
It is referenced by the book-chapter-sūtra number.

**Vārtt.** is a 2nd level source, dependent on Pāṇ. 
Vārtt. are short explanations or additions to the sūtras, with few sentences divided in numbered paragraphs under each sūtra. 
It is referenced by Pāṇ. sūtra number and Vārtt. paragraph number.

**Pat.** is a 3rd level source, dependent on Pāṇ. & Vārtt. 
Pat. is a verbose comm. with large passages, explaining both Pān. sūtras and Vārttikas. 
It is referenced through Pān. sūtra and Vārtt. numbers, which it comments.

There can be also 4th level source (as Pradīpa, a comm. on Pat.), 5th level source (as Pradīpa-uddyota, comm. on Pradīpa) and so on.

I read the examples above in this way:
Pāṇ. 6, 3 121, Vārtt. = see Vārtt. commentary to Pāṇ. sūtra.
Pāṇ., 5, 1, 52, Vārtt., Pat. = see Vārtt. and Pat. comm. to the Pāṇ. sūtra 
                                  OR = see Pat. comm. to Vārtt. to this sūtra.
Pāṇ. 3,1 14; and Vārtt. = see Pāṇ. sūtra AND also see Vārtt. comm. to this sūtra.
Pāṇ. 4, 1, 55, Vārtt. 2 = see the 2nd Vārtt. comm. to the Pāṇ. sūtra.
Pāṇ. 6,2,33, Vārtt. 1, Pat. = see Pat. comm. under the 1st Vārt. comm. to the Pāṇ. sūtra.
Pāṇ. 4,1,52, Vārtt. 5, Pat. ; 6,2,170 = See Pat. comm. under Vārtt. 5 to the sūtra 4.1.52 and also see the sūtra 6.2.170

**Comment by gasyoun** [comment]
> Pat. is a 3rd level source, dependent on Pāṇ. & Vārtt.

Thanks for the detailed explanation with examples.

**Comment by funderburkjim** [comment]
> e.g. Pāṇ. i, 4, 52, Kāṡ. or Pāṇ. vi, 4, 16, Siddh., where the reference actually points not to Pāṇ. but to the explanations of Kāś. and Siddh. on the Pāṇ. ṣūtras.

Just bringing this comment from #45, as it provides an additional example of how to read.

Presume `Kāś.` = Kāśikā-vṛtti 

and  Siddh. = Siddhānta-kaumudī

**Comment by funderburkjim** [comment]
Appreciate the helpful explanations above!  

Will have to think how to mark these in mw.xml in a helpful way.  Definitely open to suggestions here.
Maybe I'll attempt an anthology of variations, which could be useful in developing a scheme for better coding than current.

**Comment by funderburkjim** [comment]
Kāśikā-vṛtti, Siddhānta-kaumudī  these works in mwauthorities
pāṇini , patañjali and kātyāyana  appear as authors in mwauthorities.

Interestingly, Mahabhashya  and Varttika do not appear in mwauthorities.

varttika appears in ACC in three instances, but this seems to be the one we are interested in:
vārttika gr. by Vararuci i. e. Kātyāyana. Oppert II, 6422. C. II, 4925.

**Comment by funderburkjim** [comment]
> Add to readme :) Is Lex different than the VLEX research?

lex and vlex are two tag names used in mw.xml markup.  I'm to blame for the particular choice of tag names.  lex is used to enclose gender information for substantives.  vlex is used to identify headwords as roots, and also to mark conjugation class (1-10) and pada (Parasmaipada or Atmanepada) for verbs.

**Comment by gasyoun** [comment]
> lex is used to enclose gender information for substantives. vlex is used to identify headwords as roots, and also to mark conjugation class (1-10) and pada (Parasmaipada or Atmanepada) for verbs.

Crystal clear now. I do forget now and then some of the not so well documented tags.

**Comment by gasyoun** [comment]
> (See bhúvas, bhūr, pp. 760 and 763) [L=151554]

`pp. ` left unmarked.

**Comment by gasyoun** [comment]
`mgs` is treated as `mg` = meanings, @funderburkjim 

```
laghu [Printed book page 233-a]laghú, younger form of raghú, a.

```

![sdasddsds](https://user-images.githubusercontent.com/80761/114601324-0bb35500-9c9e-11eb-9287-8d7fba76088e.png)
--

**Comment by gasyoun** [comment]
@funderburkjim `gad [cf. Lith. gadijos, zadas, zodis, giedmi; Pol. gadaé; Hib. gadh.] [ID=62868.1]`

`Pal.` to be added to abbreviations.

![pold](https://user-images.githubusercontent.com/80761/115067991-50d3c300-9efa-11eb-8cb5-484e48082cbc.png)

**Comment by funderburkjim** [comment]
> Is this issue closable now?

Hard to say for sure.  Some of these suggestions have been acted upon, some of them are now hard to decipher.
I say yes, let's close this issue.
