### ISSUE TITLE
Tooltips for H1, etc.

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#53]
In #45, it was mentioned that the H1, etc. notation used in the MW displays (and xml) is confusing to people.

These codes classify each of the entries of the mw.xml digitization.
Here are all the codes, with frequency:
```
<H1> 31835
<H1A> 9562
<H1B> 9768
<H1C> 604
<H2> 32459
<H2A> 21755
<H2B> 17548
<H2C> 513
<H3> 112133
<H3A> 17046
<H3B> 15060
<H3C> 782
<H4> 17108
<H4A> 385
<H4B> 228
<H4C> 14
```

**Comment by funderburkjim** [comment]
The numbers (1-4) are intended to correspond to the '4 lines' of headwords as described by Monier-Williams in [Section 2 of the Introduction](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/mwpref/mwpref11.html).

* H1:  Nagari line
  * There is also a subset of several hundred roots which are printed in large Devanagari.
     We have a list of these, but membership in this list is not currently indicated in mw.xml or in the
     displays.
* H2: IAST headwords.  Generally, begin a paragraph.   
* H3: compounds formed from H2 words. 
* H4: Further level of compounds from H3 words.

**Comment by funderburkjim** [comment]
### The 'Usual' case for H3.

The way that H3 classification is determined in the digitization is generally typographic.  IAST words that
begin a paragraph (and these are invariably presented in complete form)  are classified as H2.
Words within a paragraph (also in bold type, and usually presented in partial form) are classified as H3.

The most common relation between an H3 child headword and an H1 or H2 parent headword is that the H3
is a compound (samAsa) whose first pada is the H2 word.
Both of the examples provided by MW for H3 are of this form. 
For instance under  H1 **कर** first compound appears as **-kacchapikā**. 

![image](https://user-images.githubusercontent.com/6393033/32531839-3c39fa82-c414-11e7-9cb9-ba611c8e68f8.png)


And under H2 **karaṇa** the first compound H3 is **-kutūhala**.

![image](https://user-images.githubusercontent.com/6393033/32531889-8a867788-c414-11e7-9237-0ce3ffd915ca.png)
 ---------
![image](https://user-images.githubusercontent.com/6393033/32531905-a21966e4-c414-11e7-8673-97d1507812c7.png)

**Comment by funderburkjim** [comment]
### A questionable kind of H3 case

There is another category where the mw.xml digitization uses an H3 classification, but where the H3 word is not related by samAsa to the parent H1 or H2 word.  These occur frequently with verbal derivates of a **prefixed root**.

vi-rata (H2) and vi-rati (H3) illustrate this.  
![image](https://user-images.githubusercontent.com/6393033/32532302-517e58f4-c417-11e7-8fcf-682f87e5f5a8.png)

There is a typographical clue: the character preceding 'rati' is not a hyphen, but `°`: °rati.

In this case both virata and virati are (I think) what Whitney calls 'verbal derivatives' of the root vi-ram.

There is a typographic similarity between this kind of H2-H3 and the more typical samAsa relation of H2-H3, in that the first word (H2) begins a paragraph and the H3's are within that paragraph and not completely spelled.

#### Change *these* H3's to H2 ?
However, it seems to me that it would be more informative to classify virati and other similar  H3s as H2s, and to view the paragraphs containing them as a convenience, rather than an indication of Monier's **line** relation.

What do others think?

**Comment by funderburkjim** [comment]
### A,B,C
Each of the four H1, H2, H3, H4 lines occur, in the mw.xml digitization, in one of four flavors.  This distinction is not one that MW made, but rather one that we added to the Cologne digitization.  
* (empty string) - e.g. H1.  This applies to the first entry.
* The other A,B,C are seen only in substantives or indeclinables for senses after the first.
* A  appears when the gender information (`<lex>` tag) is the same as that for the *first* sense.
  * H2A, for instance, is generally not printed in the displays, although it is present in the xml.
* B  appears when the gender information is different than that for the *first* sense.
  * H2B, for instance, is generally not printed in the displays unless the form is a feminine with a 
    different ending than the first.  For instance, it is not printed for the `m.` forms under karaRa.
    But H2B is printed for the first instance of the feminine form karaRI.  Whether to print H2B or not
    is a tricky choice made by the disp.php display program; H2B, etc. is always present in the xml.
* C appears when a sense applies for an inflected form.
   * Examples are seen under headword agra, where 'agram', agreṇa and agre are noted as H1C.

**Comment by funderburkjim** [comment]
#### Tooltips

I'm not sure how to phrase tooltips to explain these HXY categories.

If we can come up with useful short characterizations for tooltips, these could be added (at least in the Basic, et.al displays.)

#### Drop the ABC ?
Since the ABC designations are implicit in the sequence of records and their gender information, it might be an improvement to the displays to not print these at all.  That might avoid one point of confusion for users, and would entail no information loss in the displays.

**Comment by funderburkjim** [comment]
#### List display convention

In the list display, there is a list of nearby entries shown in the left pane.  Here, the H1,2,3,4 designations are
represented by 0,1,2 or 3 leading periods before each word.

**Comment by gasyoun** [comment]
> several hundred roots which are printed in large Devanagari

Is not every root in large Devanagari? Can we give 'em back the big one in displays?

> Both of the examples provided by MW for H3 are of this form.

Thanks, that's exactly what they miss - real life examples with colored screenshots.

> In this case both virata and virati are (I think) what Whitney calls 'verbal derivatives' of the root vi-ram.

Seems so. So H3 is expressed with Clarendon.

The main text is set in "old-style" of serif fonts. I will find out what Oxford University's Clarendon Press used at that time.

>  similar H3s as H2s, and to view the paragraphs containing them as a convenience, rather than an indication of Monier's line relation.
Makese sense to me.

> H2B, for instance, is generally not printed in the displays unless the form is a feminine with adifferent ending than the first. 
Did not knew! In 2018 I plan to print a translation of https://archive.org/details/SanskritGrammarWikner (which is a lot about how to use MW). What you write is of great importance. I never understood the A,B,C before. Actually we could include a surplus chapter on the Cologne digitization of MW.

> Since the ABC designations are implicit in the sequence of records and their gender information, it might be an improvement to the displays to not print these at all. 
I'm for dropping from display. It's far too complicated.

> H1,2,3,4 designations are represented by 0,1,2 or 3 leading periods before each word.
I was suspecting it. Here it's ok, the only thing is - I'll write a tutorial based on your notes. I'll have additional questions on MW UI.

**Comment by gasyoun** [comment]
```
←  (H2) [p= 420,3] :
jit a mfn. ifc. (Pāṇ. 3-2, 61 ) winning, acquiring cf. go- and svar-jit, svarga- &c. [ID=79195]
conquering cf. abhimāti-jít, śatru-, &c. [ID=79196]
(in med.) removing cf. kāsa- &c. [ID=79197]
←  (H1) [p= 421,1] :
jit b jitá, jíti See √ji. [ID=79308]
```

`med.` - no tooltip

**Comment by Andhrabharati** [comment]
> `med.` - no tooltip

It iindicates 'medicine'

**Comment by Andhrabharati** [comment]
> `med.` - no tooltip

It indicates 'medicine'.

**Comment by gasyoun** [comment]
> It indicates 'medicine'.

Yes, we know. But not indicated @funderburkjim

**Comment by funderburkjim** [comment]
@gasyoun   Solving the 'med.' problem is something you can do.
Here are instructions on one approach:

## First, update csl-orig/v02/mw.txt
1.  pull the latest version of csl-orig repository to local computer.
2.  edit csl-orig/v02/mw.txt 
3. Change all the relevant 'med.' to `<ab>med.</ab>`
   * relevant can be tricky.  I'll leave it to you to check that only the relevant 'med.' are changed.
      I think there are about 100.
4. git add, git commit, and git push csl-orig.
   * Mention this issue in the commit message.
 
## Second, update the mw abbr tooltip file
You need to add the 'med.' tooltip in the abbreviation file for mw.
This could be done by editing (in browser)
https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/mw/pywork/mwab/mwab_input.txt.

The format is fairly obvious; you need to add a line for 'med.'.  Be sure there is a 'tab' character where needed.
Then save and commit.  Have your commit message refer to this issue (e.g. `https://github.com/sanskrit-lexicon/MWS/issues/53`).

## Notify me
When done, notify me by a comment in this issue.  
Then, I'll do what is necessary to make the changes active on the Cologne server.

**Comment by gasyoun** [comment]
> csl-orig/v02/mw.txt

csl-orig/v02/mw/mw.txt

**Comment by Andhrabharati** [comment]
> @gasyoun Solving the 'med.' problem is something you can do.

@gasyoun, @drdhaval2785 

Let @funderburkjim be asked to do just the tasks he could only undertake.

Rest of the things should be done by others; this makes Jim's life easy and others would also have some feel of contributon (as the things don't lie undone for long).

I guess this point has already been discussed upon recently.

**Comment by gasyoun** [comment]
> Let @funderburkjim be asked to do just the tasks he could only undertake.

Sure, but that means we need to know, what and where to do. We need a list of where documentation is. There are so many of them, that I loose track all the time.

**Comment by Andhrabharati** [comment]
Just browsed through the mw.txt; it seems at many places the abbr. is 'medical' (or probably even 'medicinal') more appropriately.

So the ab_input could have 'medicine or medical' as the expansion.

When looked further, this applies to almost all the subjects- Anatomy, Astrology (Astrological), Astronomy, Geometry, Grammar (Grammatical), Mathematics, Medicine, Mythology, Surgery- to be either in the noun-form or as adjective (depending on context).

**Probably one has to live with a single form, as mentioned in the book!**

**Comment by gasyoun** [comment]
> Probably one has to live with a single form, as mentioned in the book!

Not sure what you mean.

> Anatomy, Astrology (Astrological), Astronomy, Geometry, Grammar (Grammatical), Mathematics, Medicine, Mythology, Surgery- to be either in the noun-form or as adjective (depending on context).

Right.

**Comment by funderburkjim** [comment]
@gasyoun 

Your changes now installed on Cologne server!

FYI -  Here are the steps I took, in two parts: local server install, and Cologne server install

## Local server
This shows the scripts run.  The script outputs are not shown, or shown partially.
   Also lines beginning with '#' are either script output or comments.
```
cd /c/xampp/htdocs/cologne/csl-pywork
git pull
   #v02/distinctfiles/mw/pywork/mwab/mwab_input.txt | 1 +
  #1 file changed, 1 insertion(+)
cd ../csl-orig
git pull
   #v02/mw/mw.txt | 174 +++++++++++++++++++++++++++++----------------
   #1 file changed, 87 insertions(+), 87 deletions(-)

cd ../csl-pywork/v02
grep 'mw ' redo_xampp_all.sh   
   #sh generate_dict.sh mw  ../../mw  ## This is the command for local install of mw
sh generate_dict.sh mw  ../../mw
   # updating for websanlexicon for dictionary mw
   # ...
sh xmlchk_xampp.sh mw   
  #python3 ../../xmlvalidate.py ../../mw/pywork/mw.xml ../../mw/pywork/mw.dtd
  # ok   <<< This reassures that no errors introduced in mw.xml. So displays should work
```

## Cologne server
I login to Cologne server with Putty. Then essentially do the same thing as on local server.
```
cd /nfs/projekt/sanskrit-lexicon/http/docs/scans/csl-pywork
git pull
cd ../csl-orig
git pull
cd ../csl-pywork/v02
grep 'mw ' redo_cologne_all.sh
  #  sh generate_dict.sh mw  ../../MWScan/2020/
sh generate_dict.sh mw  ../../MWScan/2020/

# DONE
```

```

**Comment by funderburkjim** [comment]
@gasyoun   This went well.  👍 
Maybe it could serve as a model for at least some of the
improvements you want to make from time to time.  

As for documentation,  you could make a 'marcis' directory in the csl-doc repository (https://github.com/sanskrit-lexicon/csl-doc) and write various instruction files in a form that you find helpful.

**Comment by funderburkjim** [comment]
##  check that changes worked

![image](https://user-images.githubusercontent.com/6393033/151717051-4698c0f6-6bd7-4433-8f1f-11c45162c79a.png)

**Comment by gasyoun** [comment]
> I login to Cologne server with Putty

And @drdhaval2785 knows how to as well, right?

> Your changes now installed on Cologne server!

Thanks, now I can do the MW update pulls. But not sure about the https://github.com/sanskrit-lexicon/csl-orig/tree/master/v02/pwg abbreviation issues, listed in a PWG issue.

**Comment by drdhaval2785** [comment]
Dhaval knows how to login, but has not been logging for quite some time. I do not have a working account with Cologne right now.

**Comment by funderburkjim** [comment]
> PWG abbreviation issues.

@gasyoun   I intend to do some work with `<ls>` abbreviation markup in pwg.txt this week (related to MBH).  Can you wait until this is done?

**Comment by gasyoun** [comment]
> Can you wait until this is done?

Why even ask! Yes, of course ))

**Comment by funderburkjim** [comment]
Good, Thanks. 👍

**Comment by drdhaval2785** [comment]
Nope. Closeable.
