### ISSUE TITLE
n. (once m.) 

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#56]
> n. (once m.) milk MBh.  ; Suṡr.  ; Kāv.  &c. [L=254406]

`m.` not marked as an abbreviation.

> (H2) yaṣṭi 1 [p= 840] : f. ( for 2. See [p= 848,3] ) sacrificing Pāṇ.  3-3, 110 Sch. ( prob. w.r. for iṣṭi) . [L=169538]

`prob.` not marked as an abbreviation.

**Comment by funderburkjim** [comment]
Entering correction  'm.' -> `<lex>m.</lex>`.

**Comment by drdhaval2785** [comment]
Both markup done. Confirmed. Closing.
