### ISSUE TITLE
Last five missing _$_ etymologies

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#58]
```
ahi
fBu
PenI
vyodana
Sala
```

Contain $. I have a solution for all but `vyodana`. Even on page http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/servepdf.php?page=1041 I can not find the entry.

```
ahi <ab>Russ.</ab>_$;</c1> -> <ab>Russ.</ab>ûgorj;</c1>

fBu Angl.Sax.</ab>_$_;_<ab> -> Angl.Sax.</ab>earfoð<ab>

PenI <ab>Slav.</ab>_$_;_<ab> -> <ab>Slav.</ab>pěna;<ab>

Sala _measure_of_length</c> <p><cf/>~<c>$-</c> -> _measure_of_length</c> <p><cf/>~<c>tri-,-</c>
```

![tri](https://user-images.githubusercontent.com/80761/37558242-e8ecf5f4-2a21-11e8-982e-b130d5231e8b.PNG)

@SergeA agree?

In `raj` there is undeciphered Greek `[ cf. Gk. , "to dye", , "dyer."]` So there might be many more?

![gk](https://user-images.githubusercontent.com/80761/37558268-4f0becaa-2a22-11e8-8f7a-666f81e88882.PNG)

**Comment by SergeA** [comment]
> @SergeA agree?

If you are waiting for an answer, please put your question more understandably.

**Comment by SergeA** [comment]
**vyodana**

![vyodana](https://user-images.githubusercontent.com/6435011/37564127-531bd7c8-2a87-11e8-9ccc-5a10c0d7cb06.jpg)

`(H3) vy--odana [p= 1029,1] [L=208305] | ( $ ind. accord. to  Sāy.   = vividhe 'nne labdhe sati)  RV.  viii, 52, 9.`

It is "e" with a blob.
"( $ ind." >> "(_e_, ind."
"E" shows word ending of the ind. form "vyodane".

Compare PWK
`(vyodana) viodana , Loc. nach  Sāy.  = vividhe 'nne labdhe sati. `
Note here **Loc.** to point the actual word-form "vyodan**e**".

Compare also PWG:
```
vyodana (2. vi + o°) m. asya vṛṣṇo vyodana uru kramiṣṭa jīvase Ṛv.8, 52, 9. 
= vividhe 'nne labadhe sati Sāy.  
```
Here is given the full sentence.
Word "vyodan**e**" is changed to "vyodan**a**" by sanshi.
Also note here the wrong reference Ṛv.8, 52, 9, which was copied by MW.
The actual reference is Ṛv.8, 63, 9. Should we correct this?

**Comment by funderburkjim** [comment]
Have folded these five corrections  into the meta/iast conversion
https://github.com/sanskrit-lexicon/Cologne/issues/216,  currently in progress.

**Comment by gasyoun** [comment]
> Also note here the wrong reference Ṛv.8, 52, 9, which was copied by MW.
The actual reference is Ṛv.8, 63, 9. Should we correct this?

At least document in a .txt file.

**Comment by gasyoun** [comment]
@funderburkjim it's not fixed, is it?

**Comment by funderburkjim** [comment]
I agree we should correct such references and add them as print changes when required.

Looks like the items you point out have not yet been corrected.

Keep after me and/or @drdhaval2785  on this until done.

**Comment by gasyoun** [comment]
@funderburkjim I believe in you.

**Comment by drdhaval2785** [comment]
All incorporated. Closing.

**Comment by Andhrabharati** [comment]
> 
> 
> **vyodana**
> 
> ![vyodana](https://user-images.githubusercontent.com/6435011/37564127-531bd7c8-2a87-11e8-9ccc-5a10c0d7cb06.jpg)
> 
> `(H3) vy--odana [p= 1029,1] [L=208305] | ( $ ind. accord. to Sāy. = vividhe 'nne labdhe sati) RV. viii, 52, 9.`
> 
> It is "e" with a blob.
> "( $ ind." >> "(_e_, ind."
> "E" shows word ending of the ind. form "vyodane".
> 
> Compare PWK
> `(vyodana) viodana , Loc. nach Sāy. = vividhe 'nne labdhe sati. `
> Note here **Loc.** to point the actual word-form "vyodan**e**".
> 
> Compare also PWG:
> 
> ```
> vyodana (2. vi + o°) m. asya vṛṣṇo vyodana uru kramiṣṭa jīvase Ṛv.8, 52, 9. 
> = vividhe 'nne labadhe sati Sāy.  
> ```
> 
> Here is given the full sentence.
> Word "vyodan**e**" is changed to "vyodan**a**" by sanshi.
> Also note here the wrong reference Ṛv.8, 52, 9, which was copied by MW.
> The actual reference is Ṛv.8, 63, 9. Should we correct this?

This vyodana comes under the "word-endings" issue that I was talking about all along.
Glad that @SergeA could get this added into the MW text.
