### ISSUE TITLE
one partic. point

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#59]
> (H1) vy-agra b [p= 1029] : mf (ā) n. not attending to any one partic. point ( opp. to ekā*gra), distracted, inattentive [L=208320]

partic. wrong grammatical markup applied, guess there are more similar cases.

**Comment by funderburkjim** [comment]
I don't see what is wrong.  More details needed.

**Comment by gasyoun** [comment]
partic. is not a grammar tag.

**Comment by funderburkjim** [comment]
But it is an abbreviation, and shows a tooltip ('particular') which looks right to me. I still see nothing that needs change.

**Comment by gasyoun** [comment]
So be it.
