### ISSUE TITLE
Link to Source Text

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#6]
How about some testing on linking to source texts? One way is to link to Gretil, locally (https://www.dropbox.com/s/uu6tlj6fdp8b37y/GRETIL_ALL_2013-10-09_UTF8_FOR_PERSONAL_USE_ONLY.zip?dl=0), but we can't give a link to the line, only general file; or on Cologne's website, so a copy of it. For RV I've compiled https://www.dropbox.com/s/t720jc9s8ju0cc7/RV-sa-hn-ru-de-en.html?dl=0, but I have it only for Rigveda, not even Atharvaveda. 
In MW 62153: <s>I</s><ls>Pa1n2._3-2_,_8</ls> -> <s>I</s> <ls>Pa1n2._3-2_,_8</ls> ? Should not there be spacing in between any two elements, how about regexing this field? Should not we do RV. ix, 62, 25  -> RV. IX, 62, 25 at the same time or there was an idea behind it?

**Comment by funderburkjim** [comment]
> s this issue closable now?

Yes, I think closeable.  Closing.
