### ISSUE TITLE
VP.  @ [L=260923]

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#60]
> m. of various authors and scholars ( esp. of the poet bhartṛ-hari as the author of the vākya-padīya ; also with miśra, bhaṭṭa, dīkṣita &c. ) Cat.  [L=260922]
m. of a mountain VP.  @ [L=260923]
m. of a world (cf. hari-varṣa) L.  [L=260924]

@ sign seems fishy, Jim.

**Comment by funderburkjim** [comment]
Those @ signs have been removed in the current meta/iast conversion.
See: http://198.199.88.166/cologne/mw/web/webtc/indexcaller.php?key=hari&input=slp1&output=roman
