### ISSUE TITLE
myrobalans

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#62]
`the 3 myrobalans (= tri-phalā q.v.), L.  [L=141723]` in [L=141720]

Biological coding too wide.

![322](https://user-images.githubusercontent.com/80761/51171689-99871680-18c2-11e9-9daa-a72d4740ed78.PNG)

**Comment by funderburkjim** [comment]
I noticed a similar problem elsewhere a few days ago and it is now corrected.

![image](https://user-images.githubusercontent.com/6393033/51356792-ee28be00-1a89-11e9-853d-1c22930c2ad0.png)

The display was not closing the span associated with 'myrobalans'.

I consider this issue closable.

**Comment by gasyoun** [comment]
> The display was not closing the span associated with 'myrobalans'.

So it's a one time fix, not a general issue?

**Comment by funderburkjim** [comment]
It was a general issue - a bug in the display program.  The general issue is fixed.
