### ISSUE TITLE
Reference (re)Format (Pāṇ. 7-4, 89; viii, 2, 55)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#63]
In `(H2) [p= 717,3] : phulla a mf(ā)n. (Pāṇ. 7-4, 89; viii, 2, 55 ) split or cleft open, expanded, blown (as a flower), MBh. ; Kāv.  &c. [L=142042]` the part `Pāṇ. 7-4, 89` is ok and everywhere (roman letters changed to arabic numbers), but `viii, 2, 55` is not. Any easy fix?

![phulla](https://user-images.githubusercontent.com/80761/51175927-ac9ee400-18cc-11e9-8090-3036b7e6fda1.PNG)

**Comment by funderburkjim** [comment]
There are 8541 lines matching `<ls>Pāṇ.`.

Of these, approximately 300 only have some Roman numerals.   Not exactly sure why. 

For consistency in coding, I'll generate changes in the digitization to convert these Roman numerals to decimal digits.

**Comment by funderburkjim** [comment]
### suggested changes
The 300 + changes have been identified.

The 341 changes are in
[manualByLine_changes_edit.txt](https://github.com/sanskrit-lexicon/MWS/files/2771566/manualByLine_changes_edit.txt)

Before installing these changes in MW,  they need to be reviewed.

### Request others review
Post needed adjustments in comments.
When this review done, I'll post the changes to MW.

Note that most of the 8000 panini references have form, in digitization, like 'x-y,z'.
In addition to converting roman numerals to digits, the proposed changes of the above file also aim to convert from 'x,y,z' to 'x-y,z' form to foster greater uniformity in the digitization.

**Comment by gasyoun** [comment]
> When this review done, I'll post the changes to MW.

Looked through it and did not find nothing strange.

What I do see is Pāṇ. vii, 1, 64 encoded as Pāṇ. 7-i, 64, so the `i` is wrong, it's `1`. Converting once more will get us in trouble.
`lamBaka:896-3:<ls>Pāṇ. 7-i, 64 <ab>Sch.</ab></ls> -> <ls>Pāṇ. 7-1, 64 <ab>Sch.</ab></ls>`

Such cases are plenty.

**Comment by funderburkjim** [comment]
I have a little trouble understanding your comment.   Here is a paraphrase of what I think you have in mind:

Even after making the digitization internally consistent (by having all Arabic digits),  there will remain an inconsistency between the digitization and the printed edition (since the printed edition uses Roman numerals).  And further,
we should defer dealing with this remaining inconsistency for now.

Did I accurately paraphrase your comment?

**Comment by gasyoun** [comment]
> there will remain an inconsistency between the digitization and the printed edition (since the printed edition uses Roman numerals)

Let it be so.  I'm aware of it (is it documented everywhere else?)

> Did I accurately paraphrase your comment?

No.

See https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&page=896

![77](https://user-images.githubusercontent.com/80761/51496454-e1310500-1dd0-11e9-967c-81b20d734055.PNG)

`lamBaka:896-3:<ls>Pāṇ. 7-i, 64 <ab>Sch.</ab>`

There is no Pāṇ. Pāṇ. `vii, i, 64`  in original. There was `Pāṇ. vii, 1, 64`.

**Comment by funderburkjim** [comment]
OK -- I see.   The corrected '7-1, 64' in the manualByline_changes_edit.txt file is as it should be.

**Comment by funderburkjim** [comment]
These corrections have now been installed.
