### ISSUE TITLE
No space after dot (inf.with)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#66]
I hardly believe `to be (inf.with an acc. or nom.` should be left as it is. Guess it's not only MW-wide.

![inff](https://user-images.githubusercontent.com/80761/53438075-1e139b80-3a10-11e9-8698-44399b913593.PNG)

**Comment by Andhrabharati** [comment]
@gasyoun,

Isn't this issue closable now?

**Comment by funderburkjim** [comment]
This never got corrected in MW!    So we should not close until this is corrected.

`(<ab>inf.</ab>with an <ab>acc.</ab>`  The example in mw.txt

In fact there are likely many more that should be changed, e.g., 
`332 matches in 326 lines for "</ab>[a-zA-Z]" in buffer: mw.txt`.

We could make the MW change with a regex replacement:
`</ab>\([a-zA-Z]\) → </ab> \1`   (Emacs syntax) 

@Andhrabharati 
* Do see any problem with doing the above global regex replacement in mw.txt? 
 (332 lines would be changed in mw.txt) 
* Are there any other *similar* patterns which should also be changed in mw.txt?

**Comment by Andhrabharati** [comment]
No @funderburkjim, this cannot be done so, for it includes 296 plurals of `<s1 n="` type entries disguised as `<ab n="`!!
[I had this done in my version just yesterday.]

And in the rest 30, there are couple of corrections needed and not just inserting a space in between.

**Comment by Andhrabharati** [comment]
> * Are there any other _similar_ patterns which should also be changed in mw.txt?

There are numerous corrections of similar nature that I did in my file (last year when I started the revision work), but did not think it is worthy to list all those separately.

**Comment by funderburkjim** [comment]
## update to MW
See [change_1.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue66/change_1.txt),  or see the commit to csl-orig above.

37 lines changed.  A couple of additional changes in addition to adding a space.

-------------------------------------------------------------------

It is humbling to realize there are still such 'trivial' corrections that need to be made to mw.txt.

Maybe @drdhaval2785 can try to ferret out the (no doubt many) remaining trivial corrections needed in mw.txt.
@Andhrabharati has likely identified many of these, and perhaps he could make some suggestions to Dhaval regarding the remaining *trivial* typos.  

Suggest such work be done under a separate issue (or issues).

This issue can now be closed.
