### ISSUE TITLE
Missing markup: Ved. neut. & Gr.

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#67]
Looking at [ID=28801]

1) I have extracted all <ab>Ved.</ab>. After that I searched again for `Ved.` and found 16 cases without `<ab>`, including:
Ved.
[Ved.
Ved.inf. of
Ved.inf.of
Ved. <ab>inf.</ab> 

in

```
a/rTa
asTa/n
A/-pattos
Artos
A-voDavE/
ida/m
iya/DyE
Iraya/DyE
ud-aYc
upa-caraDyE
ezwavE/
ki/yat
go/
rakz
vi-kzuB
vi-vad
```

2) None of the 8 cases of `neut.` has `<ab>`.

in

```
a/ti
ati-ri
a/nta
anyat-kAraka
ida/m
Idf/kza
ka/
vedA/nta
```

3) `<ab>Gr.</ab>` has `<ab>` - fine. But if numbers follow, they should have markup as well, like Gr. 224.

![neut](https://user-images.githubusercontent.com/80761/53441180-43f06e80-3a17-11e9-959e-b695a202c41a.PNG)

**Comment by Andhrabharati** [comment]
![image](https://user-images.githubusercontent.com/75209130/151688952-ab9859b1-2e1f-472f-bd90-f65fad837ba8.png)


@gasyoun 

Now you know what to do for all such observations!

**Comment by Andhrabharati** [comment]
@funderburkjim / @gasyoun,

Is this issue closable now?

**Comment by funderburkjim** [comment]
After a quick review of mw.txt for the 3 markup problems mentioned by @gasyoun above,  I believe these have all been corrected.

Thus, this issue may be closed.
