### ISSUE TITLE
Markup &amp;c.

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#68]
There are 24k cases of `&c.`, but only a few have markup. Should all be equal? With or without?

In `99005` the `&amp;c.` is par of `ls`, see <ls>MBh. vi, 604 &amp;c.</ls>

```
<H3><h><key1>dvIpa</key1><key2>dvIpa/</key2><hom>a</hom></h><body><s>dvIpa/</s> <hom>a</hom>   &amp;c. See <ab>s.v.</ab></body><tail><L>98790</L><pc>506,1</pc></tail></H3>
```

![ampc](https://user-images.githubusercontent.com/80761/53441468-f88a9000-3a17-11e9-860a-da612c38ec58.PNG)

**Comment by Andhrabharati** [comment]
With my correction(s) incorporated now into mw.txt by @funderburkjim, the &c. is no more inside `ls`.

So guess this issue could be closed now.

Regarding the actual markup of it, it is there in another issue.

**Comment by funderburkjim** [comment]
Agree.
