### ISSUE TITLE
Marking Monier (2008 vs. 2019)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#69]
@funderburkjim I propose we make a paper together like you once did for Second International Sanskrit Computational Linguistics Symposium. 6th International Sanskrit Computational Linguistics Symposium will be held on October 23-25, 2019 at Kharagpur, West Bengal, India. Two weeks are left. I will document what I know and will ask questions here if you give a go. I will need your assistance and reassurance, otherwise it's a small one, 300 words only, very schematic.

**Comment by funderburkjim** [comment]
I'll try to answer your questions, but it will be your paper.   My head is currently filled with details of documenting apidev code in the dokuwiki.

**Comment by gasyoun** [comment]
@funderburkjim let me start.

> transliteration of Greek 

Fully finished?

> MW 'Additions and Corrections' 

Fully integrated?

**Comment by funderburkjim** [comment]
> transliteration of Greek

Finished for some dictionaries.   Jonathan got through roughly half of mw72.   Best place to start investigation of completeness is in https://github.com/sanskrit-lexicon/GreekInSanskrit/issues

**Comment by funderburkjim** [comment]
MW additions and corrections -- fully integrated AFAIK.

**Comment by gasyoun** [comment]
> roughly half of mw72

Thanks, missed it ended in 2017 unfinished.

> MW additions and corrections -- fully integrated AFAIK.

If you say, it's enough for me, thanks.

What would it take to hyperlink from MW to Panini as was done in GRA to RV?

**Comment by drdhaval2785** [comment]
As the symposium is over, closing this.
