### ISSUE TITLE
Questions Regarding "Current markup of Monier Williams Sanskrit-English Dictionary"

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#7]
It took me three days to write them down. Please do not hate me. Every few years I reread the paper, now I want to get rid of old questions:
1) "The dictionary appears as a sequence of 280081 records" - 286786 is the number of strings I see in mw.xml. Where should I look for 280081? Or is it the number before the 2012 additions incorporated?
2) "there are on average about 17 elements per record." - how many reference per record? There are some without, how many are those, that have at least one? What is the total number of time references used?
3) "There is no DTD against which to determine the validity" - even after 20 years impossible to make one? Nothing changed since 2008?
4) "Currently there is no pointer from an 'A' or 'B' child to its parent; the relation is implicit in the ordering of the records" - time not yet come?
5) semicolons are appear elsewhere -> semicolons appear elsewhere
6) "<H type='1'_> instead of <H1_>" - <H1_> is superior in all ways, way to even consider <H type='1'_>?
7) "The <tail> contains record sequencing information and a pointer to the scanned image of the pages of the dictionary." - metadata, not there in printed dictionary.
8) MONIER.ALL -> link, if a file mentioned, otherwise delete the mention
9) For my Reverse Dictionary of Sanskrit what I'm interested actually in is key2, not key1. "separates compound word components" - 2 to 4 dashes used, so such a RegEx will show me all of "compound word components"?
10) Why can't we apply <TWOWORDS/> to the 70 known "space" words?
11) he text shows -> the text shows
12) "Probably not both elements are required.", "no need for two elements, and the <shc/> could be changed to <shortlong/>." "probably now vestigial and should be removed" "Possibly should be converted" - can you make a list of deprecated and questionable tags, please?
13) I hardly understand the difference between <srs/> and <sr1/> - typographical?
14) "This element also appears for the same purpose for those prefixed verbs" - that the only place I miss a tag. How can I separate roots from prefixed verbs?
15) "elements can appear in any order" - yeah, that's great when I want to find lexical data, my regex fantasy fails.
16) "user of the XML version of the dictionary, they are probably best omitted (change _ and ~ to a single space, delete <c> , </c>, etc.)" - can we get the official version without them?
17) "various umlaut characters. These could be coded as XML entities." - done?
18) "other abbreviations that have been noted (e.g., Imper., sg.) which appear in the text but not in the preface" - what is the amount you suppose?
19) "Greek, the non-Sanskrit word is omitted and represented by the character '$'" - to fix it we need 3 things. Make a list of all instances. Cut the screenshots and add to a single document. Decipher. I'll take 1 step, Shilu - 2nd, 3rd - partly I, partly my colleagues.
20) "A separate mySQL table has been constructed containing all these Anglicized Sanskrit words, along with transliteration and citation references to other dictionary words. It is desirable for a Sanskrit scholar to examine this list, with especial attention to the words classified as 'non-Sanskrit' via the 'type="ns" attribute, and also for a fairly small number of words which appear to be Sanskrit but for which citations in the dictionary have not been found." - where is it?
21) "Currently about 900 (0.3%) of the abbreviated works remain unexplained" - Shilu had solved the last 12 missing, or do I miss something?
22) "Sometimes there is additional information, such as an indication of how the feminine stem is formed or whether the word appears only at the end of compounds." - second case I would want an additional tag-subtag. Can lex contain only gender? I mean if I would manage to do some RegEx magic, would you agree? Now it's so mixed, hardly usable even for statistical evaluations.
23) How is "lexical grammar table" ftp://ftp.uni-koeln.de/institute/indologie/download/lgtab.zip advanced other than it's outdated?
24) Can we get a unique ID for every meaning in MW as well?
25) "The coding of <hom> within the <body> is incomplete; currently only 114 instances are coded." - we can make all duplicate entries hom and clean them one day. Does not sounds better?
26) "intention of this markup is to flag those records which serve no purpose in certain hierarchical displays of the dictionary." - would love to see a sample, nothing understood.
27) Can we generate "-kalpanA, f. or -prakalpanA, f. or -pradAna, n. allotment of a portion." - text as in book from the XML file?
28) "Due in part to the intentional splitting of MONIER.ALL records in the process of XML markup, there are still some inaccuracies in the values of this element, which should be corrected for the most part in a month or two." - ever done?
29) As per http://www.sanskrit-lexicon.uni-koeln.de/mwupdate/mwxmldownload/greekinfo.html are the 11 ? "A few omissions are indicated by a '?'." about places that need approval http://www.sanskrit-lexicon.uni-koeln.de/mwupdate/greek/web/disp/ from some Greek lover? So "'$'; text in other alphabets, such as Arabic" is solely for Arabic now right? Please change "UnicodeCConverter.propertiies" -> "UnicodeCConverter.properties".
I give you my thanks. Even if you ever read all the 29 points. Now I can sleep well.

**Comment by drdhaval2785** [comment]
@gasyoun this needs relook from your side. It has been years since the questions rose. Some may have died down.
You may declutter this.

**Comment by gasyoun** [comment]
> Some may have died down.

Some have, some not.

**Comment by drdhaval2785** [comment]
Request to @gasyoun to identify closed and open questions separately. We can track them effectively then

**Comment by Andhrabharati** [comment]
@funderburkjim / @gasyoun,

Is this issue closable now?

**Comment by funderburkjim** [comment]
In many issues @Andhrabharati has asked `is this issue closable now?`  Upon my review of them, it is unclear what the criterion for 'closable' should be.  
Today I am leaning towards 'actionable'.

I just noticed that There are two kinds of 'closed' in this github listing.
* Close with comment  
* Close as not planned .  (... stale).

'stale' strikes me as applicable --  For me it means 'maybe some interesting ideas, but no clear idea of how to proceed.'  
 
If @gasyoun is so inclined,  he may wish to review his 'closed' issues, and reformulate ideas that he still views as needing attention at cdsl.
