### ISSUE TITLE
°ṭvāya vs. -dṛśya

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#70]
←  (H1) [p= 491,1] :
Whitney Roots links: dṛś

`°ṭvāya, RV. ; -dṛśya, RV.`

![tvaya](https://user-images.githubusercontent.com/80761/71318970-07f82f80-24a9-11ea-953c-7df5374a5bf1.PNG)

Is it not the same? Should not the devanagari ° become - always in IAST, @SergeA ?

**Comment by SergeA** [comment]
I think they are not the same. I think here hyphen marks a prefixed form, while circle is used for common abbreviations. But it is not for sure, needs more investigation. Better keep it as it is. 

Even in IAST better keep circles.

**Comment by funderburkjim** [comment]
Agree with @SergeA .  

Both ° and '-' are similar in that they indicate concatenation with some other text string.
° seems always to leave the 'other text string' implied, i.e., up to the reader to discern.
- is sometimes used between two explicit text strings (upa-√ dṛś) and 
  sometimes (as with -dfSya) where one of the text strings is implied.

In the example of forms of 'ind.p' (indeclineable participle),
* dfzwvA  is the form to use for the unprefixed verb
* °wvAya  means that the form to use for prefixed verbs is dfzwvAya  
   * so for prefixed verb, such as upadfz, the ind.p. is upadfzwvAya  
   * the ° in °wvAya refers to the unrepeated part 'dfz',  but the combination dfz and wvAya is not a 
      samAsa nor is it a combination of an upasarga with a root; though it is certainly a combination of 
     some sort.  
* -dfSya  means that the ind.p. for a prefixed verb can (also) be formed by combining the prefix with
    dfSya (e.g., upa-dfSya.    

In terms of frequency of occurrence, the '-' is (I conjecture) used in MW most often for samAsa, 
next most often for upasarga-verbform.   It would be interesting if we find any other kinds of 
usage of '-'.

**Comment by gasyoun** [comment]
@SergeA thanks for the comment.

> In terms of frequency of occurrence, the '-' is (I conjecture) used in MW most often for samAsa,
next most often for upasarga-verbform

Good to know, was not aware.

**Comment by drdhaval2785** [comment]
As it was decided to keep it as it is, closing this.
