### ISSUE TITLE
Space after √

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#71]
`(H1) [p= 380,3]cakrá n. (Ved. rarely m.; g. ardharcādi; fr. √ car?; √ 1. kṛ, Pāṇ. 6-1, 12 ; Kāś. ) the wheel (of a carriage, of the Sun's chariot [RV. ], of Time [ i, 164, 2-48 ]; °kráṃ-√ car, to drive in a carriage, ŚBr. vi ), RV.  &c. [ID=70328]`

![car](https://user-images.githubusercontent.com/80761/71319000-50175200-24a9-11ea-83ca-2c1f2a26e9be.PNG)

Should the space after the root remain? `fr. √ car?` Remove the space after `√`, add it before `?`, or just make `?` italics? Because of this practice we have `°kráṃ-√ car` that does look strange because of the space.

**Comment by funderburkjim** [comment]
As point of information, there are about 14000 lines of mw.txt with √.

All but two of those have a space after the √.

It would be technically easy to changes those 14,000 lines in mw.txt.

I am less clear whether the change should be done.

**Comment by funderburkjim** [comment]
@gasyoun  

The change can also be made only at the level of the displays.

I've made a test version of the basic display at DigitalOcean.

Here's the basic display for cakra WITH the space:
![image](https://user-images.githubusercontent.com/6393033/71453511-87138f00-2759-11ea-931b-c621472e2e30.png)


Here's the test version at DO for cakra, where the space is removed:
![image](https://user-images.githubusercontent.com/6393033/71454138-3d2ca800-275d-11ea-92ad-d977922e74d7.png)


I'll leave both versions up for a while, so you can compare the displays for other entries.

What do you and others think?
* the 'space' version is definitely better
* the 'no-space' version is definitely better
* Either is ok;  doesn't matter.


Technical note:
  For some reason, the test version does not work properly on Cologne server.  The space is
removed (at DO) by this line inserted after line 100 of basicadjust.php for mw:
```
   $line = preg_replace("|√ |u","√",$line); # experiment of 12/25/2019
```
I can't get this same change to work properly at Cologne

**Comment by gasyoun** [comment]
> the 'space' version is definitely better

I go for killing of the space.

**Comment by funderburkjim** [comment]
Space now killed.

Technical note:  The change made is like above, but with a preceding comment line.
Don't know why this works but did not work earlier.

**Comment by gasyoun** [comment]
> Space now killed.

Thanks.
