### ISSUE TITLE
Lithuanian words IAST

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#79]
This issue was raised in #21.

I filtered MW for Lithuanian words in MW.

Please see https://github.com/sanskrit-lexicon/MWS/blob/master/Lithuanian/filter.txt

There are 22 instances, one per line, showing 3 colon-separated fields:
* MW Cologne id
* MW headword in SLP1
* the Lithuanian words *as currently spelled* 
   * Some may have been put into IAST, many have not been.

Example:

92125.1:dina:dëna:

@gasyoun    You could work through these 22 cases.
Put the correct IAST spelling as a fourth field.

When you are done,  either 
* edit filter.txt directly and commit the corrected version to Github,
* or upload a separate copy of filter.txt with the corrections.

Then mention that the corrections are ready for me to install in
a comment in this issue.

OK?

**Comment by Andhrabharati** [comment]
I've corrected all Greek and other European words, as I am in possession of the original OUP print copy which has excellent quality, crisp and clear throughout. The scans floating everywhere are of no match to the print.

If someone is willing to takeover incorporating them in Koeln file(s), I can send across my file in unicode.

**Comment by drdhaval2785** [comment]
@Andhrabharati 
Please share the Lithuanian / any other Europena words which you may have already done.
We will try to close this issue by incorporating your data, just as was done in case of Greek words.

**Comment by Andhrabharati** [comment]
I did all those words ling back, as I mentioned in my post.

But as there was a doubt that Greek words could be done by a non-Greek person, expressed by Marcis, I just sent those words, separated from those lines.

**Comment by Andhrabharati** [comment]
And I've worked on couple of bigger issues on the total text, not as small tasks that I am seeing here now, like these -

1. Correct all cognate (ety.) lines
2. Split all the data till meanings (senses) portion appropriately (both Nominals and Verbals)
3. identify the and mark the word-endings.
... ... ... ...

**Comment by drdhaval2785** [comment]
We can just compare whatever exists in Cologne data and your work. If there are any differences, we can work on them. I would request you to provide the excel sheet for non greek words, just like you shared earlier.

**Comment by Andhrabharati** [comment]
> 
> 
> We can just compare whatever exists in Cologne data and your work. If there are any differences, we can work on them. I would request you to provide the excel sheet for non greek words, just like you shared earlier.

There sure are issues in Koeln data.
Let me see when I can do it for you. (should be soon enough)

**Comment by Andhrabharati** [comment]
Probably I could do it when I start working with Kolen  text (provided by Jim today), after 7th Jan- looking once again into my corrections (as I did today for Greek for any minor overlooks) lines.

**Comment by Andhrabharati** [comment]
(as a comparision with latest Koeln data also has to be done)

**Comment by gasyoun** [comment]
> If someone is willing to takeover incorporating them in Koeln file(s), I can send across my file in unicode.

In Dhaval we trust.

> I start working with Kolen text (provided by Jim today), after 7th Jan- looking once again into my corrections

Sounds like a plan.

**Comment by Andhrabharati** [comment]
As against the "filtered" data by @funderburkjim (22 occurrences), there are over 200 of Lithuanians words as I have seen.

Though I mentioned to give my full "lines" earlier, decided to give only the Lithuanian words now, as per the issue under discussion.

[MW_Lithuanian words.txt](https://github.com/sanskrit-lexicon/MWS/files/5806284/MW_Lithuanian.words.txt)

**And I am not going to spend any time in comparing the Koeln text with my data.**

**Comment by drdhaval2785** [comment]
> decided to give only the Lithuanian words now

Fine. Thank you for helping with Lithuanian words. 

> And I am not going to spend any time in comparing the Koeln text with my data.

Absolutely fine. That can be done by us.

**Comment by Andhrabharati** [comment]
And you may note that at **(611,3) paśu**, it is not "**Lit.**" but "**Lat.**" in the book.

**Comment by gasyoun** [comment]
> not "Lit." but "Lat."

Eagle-eyed.

**Comment by Andhrabharati** [comment]
> > not "Lit." but "Lat."
> 
> Eagle-eyed.

am just focused in what(ever) I do.

**Comment by funderburkjim** [comment]
Corrections to mw:
1. 120108.1 : pala :  \<ab>Lith.\</ab> \<s>pelE\</s>  : \<ab>Lith.\</ab> \<etym>pelai\</etym>
2. 120543.1 : paSu : `<ab>Lit.</ab> <etym>pecu</etym>` : `<ab>Lat.</ab> <etym>pecu</etym>` Thanks @Andhrabharati !

**Comment by funderburkjim** [comment]
@gasyoun  Please examine @Andhrabharati  's file [MW_Lithuanian words.txt](https://github.com/sanskrit-lexicon/MWS/files/5806284/MW_Lithuanian.words.txt)

and note here any corrections needed in the current MW spellings of the Lithuanian words.

Your help will allow us to close this issue.

**Comment by Andhrabharati** [comment]
Looks like @gasyoun is occupied for the year 2021 (with his Ramayaṇa and other book printing works), as he mentioned elsewhere.

Probably @drdhaval2785 might take-up this work, as he said thus earlier-
 >>   And I am not going to spend any time in comparing the Koeln text with my data.

> Absolutely fine. That can be done by us.

**[I don't think any knowledge in Lithuanian language is required for the job; its just a character recognition work visually.]**

**Comment by gasyoun** [comment]
> and note here any corrections needed in the current MW spellings of the Lithuanian words.

I have to see the scans. Can we add HTML links to them?

> [I don't think any knowledge in Lithuanian language is required for the job; its just a character recognition work visually.]

Almost.

**Comment by Andhrabharati** [comment]
Just made a quick Excel file, with my data and Jim's data (filter.txt) as mentioned at the top.
(Wonder why @funderburkjim was saying 22 number; his number is also almost the same as mine.)
[MW_Lithuanian words AB vs. Koeln.xlsx](https://github.com/sanskrit-lexicon/MWS/files/6005878/MW_Lithuanian.words.AB.vs.Koeln.xlsx)

@gasyoun might find this useful, if working on this.

And the corresponding CSV file is here, if @funderburkjim likes to browse through.
[MW_Lithuanian words Ab vs. Koeln.txt](https://github.com/sanskrit-lexicon/MWS/files/6005867/MW_Lithuanian.words.Ab.vs.Koeln.txt)

**Comment by funderburkjim** [comment]
> I have to see the scans

The page,col is in MW_Lithuanian.words.txt file.
Almost as convenient as a link: `3,1	akṣa	assis` 

If you insist on links,  you can generate links in your text file. e.g.,
change each line by prefixing `https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?page=`

And, voila, you'll have links, e.g.,

https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?page=3,1	akṣa	assis

**Comment by Andhrabharati** [comment]
Appears we both are "travelling at close wavelengths"!!

**Comment by Andhrabharati** [comment]
> Put the correct IAST spelling as a fourth field.

It would be Unicode (any language/script), not IAST (used only for Sanskrit/Devanagari).

**Comment by gasyoun** [comment]
@darius-sr please confirm you understand the task.

**Comment by gasyoun** [comment]
Some changes are easy.
`dristu` --> `drįstu`

Many more contain an archaic form which is not used anymore. We could add the Lithuanian word in use in metadata.

I have no final answer of what to do with @darius-sr comments as of now.
 
[MW_Lithuanian.words.AB.vs.Koeln-_Darius.xlsx](https://github.com/sanskrit-lexicon/MWS/files/6071472/MW_Lithuanian.words.AB.vs.Koeln-_Darius.xlsx)

**Comment by Andhrabharati** [comment]
Why not leave them as in the MW print book?

The book itself is OLD, and based on archaic forms of those times only!
(Recall the Greek entries issue, wherein the J. Migliori opined to have the archaic forms.)

Or probably use tool-tips wherever possible, showing the "current" forms for those archaic stuff..

I recall @funderburkjim saying elsewhere to have such changes to be in a "new edition" at a different platform, if someone wishes to do so.

**Comment by Andhrabharati** [comment]
Just tried to make a tsv file out of the xlsx, for @funderburkjim to see

https://github.com/sanskrit-lexicon/MWS/raw/master/mwtranscode/MW_Lithuanian.words.AB.vs.Koeln-_Darius.tsv

**Comment by gasyoun** [comment]
>Or probably use tool-tips wherever possible, showing the "current" forms for those archaic stuff.

That might even make sense.

**Comment by Andhrabharati** [comment]
> @gasyoun You could work through these 22 cases.
> Put the correct IAST spelling as a fourth field.

It seems there is a big confusion in Cologne team's mind about the term IAST.

I had just tried telling Dhaval about this few days back.
Now seems it needs more publicity!

**IAST** (International Alphabet of Sanskrit Transliteration) **is a minute subset of (Unicode) Roman accents** (hardly a score of them) **applied to transliterate Sanskrit alphabet ONLY**, whereas Roman accents go into some hundreds, if not thousands, encompassing majority of the Western world language scripts.

I would say it is more appropriate to use the term **Roman Unicode**, to cover all scripts native forms, instead of IAST for all languages including Sanskrit. In fact, it is what is appearing in the web-display input/output drop-down lists.

When the script is rendered in non-Roman lettering, like Greek, Russian and many Asian (Eastern world) languages, the proper term is simply **Unicode**.

**Comment by funderburkjim** [comment]
Yes, we are aware that the term IAST pertains to Sanskrit.  
I use [iast-wikipedia](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration) as a reference.

@gasyoun is also aware of this.  But your reminder of the distinction is well-written.

Your Lithuanian list is impressive -- we'll have to examine more closely to see what use to make of it, maybe in the form of
a tooltip as mentioned.  

The most immediate usage would be to more correctly represent the Lithuanian text in mw.txt in mimic of mw's spelling, if possible with
unicode.  Are corrections  to mw.txt for Lithuanian words along this line already mentioned in your file?  
If so, perhaps you could extract into a separate file the items that need such correction in mw.txt.

**Comment by Andhrabharati** [comment]
> Are corrections to mw.txt for Lithuanian words along this line already mentioned in your file?

Yes, very much.
They are all with (p,c) HW references, not with <L>-numbers.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Just look for lines containing  the term 'Diff'; these are the lines that need corrections.

Hope this issue could be closed sooner; has been there for more than a year now, for the **admin**'s  action!!
[Seems @drdhaval2785 is not active any more here!]

**Comment by Andhrabharati** [comment]
I have "handled" all the etym. entries including these Lithuanian items, and this issue is closable now.
