### ISSUE TITLE
Fresh relook at the "Additions and Corrections" warranted

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#80]
Dear folks,

[MW_prakriyA (corrected).txt](https://github.com/sanskrit-lexicon/MWS/files/5740367/MW_prakriyA.corrected.txt)
[MW_prakriyA.txt](https://github.com/sanskrit-lexicon/MWS/files/5740368/MW_prakriyA.txt)
Pl. have a look at the attached files, for an example entry प्रक्रिया (prakriyA), showing what I meant.

I am not at ease with other transliteration schemes, but if some one is willing to carry out necessary corrections, I can make all words that need to be updated, and give the file either in direct Unicode or in ITRANS.

Like to hear on this from someone.

**Comment by gasyoun** [comment]
> I am not at ease with other transliteration schemes

It is of no importance, anything can be converted to anything easily.

> Like to hear on this from someone.

@funderburkjim can we make use of it, any idea how to compare?

**Comment by funderburkjim** [comment]
Dear @Andhrabharati 

Hello!

As I understand your two versions of prakriyA,
you are wanting to make a 'better' version of Monier-Williams (1899) dictionary.

The printed text in question (what we call the scanned image) is:
![image](https://user-images.githubusercontent.com/6393033/103143841-c9650880-46ec-11eb-9aa5-e41f9de01325.png)

And, just to take the first change you mention,
Our current digitization is:
` producing, production,`     which is in agreement with the scanned image.

But you think a better entry would be:
`production, creation, origin` 

Have I paraphrased your suggestion accurately?

**Comment by drdhaval2785** [comment]
No. I think he is referring to addenda / corrigenda section implenentation. If addenda / corrigenda are taken into consideration, the output would look like this.

**Comment by funderburkjim** [comment]
Oh, that makes more sense.

One way that might be useful would be to rearrange the records so that, if possible,
the corrections are just after the record being corrected.   In this prakriyA example,
how to do such a rearrangement seems clear.  

Here's the base digitization in mw.txt under discussion:
```
<L>130013<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3
<s>pra-°kriyA</s> ¦ <lex>f.</lex> producing, production, <ls>Sarvad.</ls><info lex="f"/>
<LEND>
<L>130014<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  procedure, way, manner, <ls>MBh.</ls><info lex="inh"/>
<LEND>
<L>130015<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  a ceremony, observance, formality, <ls>Hariv.</ls>; <ls>Kathās.</ls>; <ls>Rājat.</ls><info lex="inh"/>
<LEND>
<L>130016<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  precedence, high position, elevation, privilege, <ls>MBh.</ls>; <ls>Rājat.</ls>; <ls>Kathās.</ls><info lex="inh"/>
<LEND>
<L>130017<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  the insignia of high rank, <ls>Rājat.</ls><info lex="inh"/>
<LEND>
<L>130018<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  characterisation, <ls>Nyāyas.</ls><info lex="inh"/>
<LEND>
<L>130019<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  a chapter (<ab>esp.</ab> the introductory <ab n="chapter">ch°</ab> of a work), <ls>Śaṃk.</ls>; <ls>Cat.</ls><info lex="inh"/>
<LEND>
<L>130020<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  (in med.) a prescription, <ls>Bhpr.</ls><info lex="inh"/>
<LEND>
<L>130021<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  (in gram.) etymological formation<info lex="inh"/>
<LEND>
<L>130022<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  rules for the <ab n="formation">f°</ab> and inflection of words, <ls>MW.</ls><info lex="inh"/>
<LEND>

----- and here are the records from Corrections and Additions ----

<L>130022.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦  production, creation, origin, <ls>Sarvad.</ls><info n="sup"/><info lex="inh"/>
<LEND>
<L>130022.2<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ form, procedure, method, mode, manner, <ls>MBh.</ls><info n="sup"/>
<LEND>
<L>130022.3<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ a ceremony, <ls>Hariv.</ls>; <ls>Kathās.</ls><info n="sup"/>
<LEND>
<L>130022.4<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ formality, <ls>Rājat.</ls><info n="sup"/>
<LEND>
<L>130022.5<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ prerogative, privilege, high rank or position, excellence, superiority, <ls>MBh.</ls>; <ls>Kathās.</ls> &c.<info n="sup"/>
<LEND>
<L>130022.6<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ the insignia of high rank or dignity, <ls>Rājat.</ls>; <ls>Gīt.</ls><info n="sup"/>
<LEND>
<L>130022.7<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ characterization, <ls>Nyāyas.</ls><info n="sup"/>
<LEND>
<L>130022.8<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ a chapter, section (often at the end of titles of books)<info n="sup"/>
<LEND>
<L>130022.9<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ medical prescription, <ls>Bhpr.</ls><info n="sup"/>
<LEND>
```

**Comment by funderburkjim** [comment]
## One possible solution

Rearrange the records so that supplement records are just after the corresponding
original records.   This involves change L-numbers.  For instance,

```
<L>130013<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3
<s>pra-°kriyA</s> ¦ <lex>f.</lex> producing, production, <ls>Sarvad.</ls><info lex="f"/>
<LEND>
<L>130013.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦  production, creation, origin, <ls>Sarvad.</ls><info n="sup"/><info lex="inh"/>
<LEND>


<L>130014<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  procedure, way, manner, <ls>MBh.</ls><info lex="inh"/>
<LEND>
<L>130014.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ form, procedure, method, mode, manner, <ls>MBh.</ls><info n="sup"/>
<LEND>

<L>130015<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  a ceremony, observance, formality, <ls>Hariv.</ls>; <ls>Kathās.</ls>; <ls>Rājat.</ls><info lex="inh"/>
<LEND>
<L>130015.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ a ceremony, <ls>Hariv.</ls>; <ls>Kathās.</ls><info n="sup"/>
<LEND>

<L>130016<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  precedence, high position, elevation, privilege, <ls>MBh.</ls>; <ls>Rājat.</ls>; <ls>Kathās.</ls><info lex="inh"/>
<LEND>
<L>130016.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ formality, <ls>Rājat.</ls><info n="sup"/>
<LEND>
<L>130016.2<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ prerogative, privilege, high rank or position, excellence, superiority, <ls>MBh.</ls>; <ls>Kathās.</ls> &c.<info n="sup"/>
<LEND>     NOTE 2 supplement records seem to 'belong' to 130016

<L>130017<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  the insignia of high rank, <ls>Rājat.</ls><info lex="inh"/>
<LEND>
<L>130017.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ the insignia of high rank or dignity, <ls>Rājat.</ls>; <ls>Gīt.</ls><info n="sup"/>
<LEND>

<L>130018<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  characterisation, <ls>Nyāyas.</ls><info lex="inh"/>
<LEND>
<L>130018.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ characterization, <ls>Nyāyas.</ls><info n="sup"/>
<LEND>     NOTE: This is just a spelling change

<L>130019<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  a chapter (<ab>esp.</ab> the introductory <ab n="chapter">ch°</ab> of a work), <ls>Śaṃk.</ls>; <ls>Cat.</ls><info lex="inh"/>
<LEND>
<L>130019.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ a chapter, section (often at the end of titles of books)<info n="sup"/>
<LEND>

<L>130020<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  (in med.) a prescription, <ls>Bhpr.</ls><info lex="inh"/>
<LEND>
<L>130020.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
¦ medical prescription, <ls>Bhpr.</ls><info n="sup"/>
<LEND>

<L>130021<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  (in gram.) etymological formation<info lex="inh"/>
<LEND>
<L>130022<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
¦  rules for the <ab n="formation">f°</ab> and inflection of words, <ls>MW.</ls><info lex="inh"/>
<LEND>
```

@Andhrabharati   Is this close to what you had in mind?

@drdhaval2785 What do you think regarding this possible rearrangement?

**Comment by Andhrabharati** [comment]
@funderburkjim,

What I said is with regarding to changing the text, considering the
"Additions and Corrections" given at the end of the book.

In this particular case, the corrections are to be "applied" part by part
in the main text, closely looking into the text.

Thats what I suggested giving the main & corrections texts put together
part by part in one file (for better understnding) and the resulting final
text in another file.

Currently, the Cologne data is having these two texts separately, one below
the other, without merging those appropriately.

Hope now you'd get what I am saying.

**Comment by drdhaval2785** [comment]
@Andhrabharati 
If you reply to the mail, kindly delete the text before you type anything. Otherwise the text of mail would unnecessarily get attached to the github issue. 

You can view your last comment on github site (not in mail) and click on three dots at the end, to understand what I mean by 'unnecessary attachment'

**Comment by Andhrabharati** [comment]
I do not understand why such a complex mechanism is being thought of, for
incorporating the corrections in the main text.

We just need to treat this as errata, for which we do corrections in the
main text as inserting, deleting or replacing the text, is intended.

And probably add a simple note saying that the text is "corrected" with
reference to the errata given elsewhere in the book itself. You may see the
note I used in my second (corrected) file. So the user would be informed
why the text is different than the printed text seen in that page.

**Comment by Andhrabharati** [comment]
I missed saying a point above -

Many additions and corrections were already incorporated in the present
text, without resirting to any such complex/long criteria as you are
mentioning now.

**Comment by Andhrabharati** [comment]
On Sat, 26 Dec 2020, 09:30 Nagabhushana Rao K, <knbrao@gmail.com> wrote:

> I do not understand why such a complex mechanism is being thought of, for
> incorporating the corrections in the main text.
>
> We just need to treat this as errata, for which we do corrections in the
> main text as inserting, deleting or replacing the text, is intended.
>
> And probably add a simple note saying that the text is "corrected" with
> reference to the errata given elsewhere in the book itself. You may see the
> note I used in my second (corrected) file. So the user would be informed
> why the text is different than the printed text seen in that page.
>
> On Sat, 26 Dec 2020, 07:30 funderburkjim, <notifications@github.com>
> wrote:
>
>> One possible solution
>>
>> Rearrange the records so that supplement records are just after the
>> corresponding
>> original records.
>>
> Yes, this is exactly what I did in my first file, not line by line, but
part by part as appropriate.

We at Andhrabharati treat data as "logical blocks", not by lines!!

This involves change L-numbers. For instance,

**Comment by Andhrabharati** [comment]
On Sat, 26 Dec 2020, 09:38 Nagabhushana Rao K, <knbrao@gmail.com> wrote:

>
>
> On Sat, 26 Dec 2020, 09:30 Nagabhushana Rao K, <knbrao@gmail.com> wrote:
>
>> I do not understand why such a complex mechanism is being thought of, for
>> incorporating the corrections in the main text.
>>
>> We just need to treat this as errata, for which we do corrections in the
>> main text as inserting, deleting or replacing the text, is intended.
>>
>> And probably add a simple note saying that the text is "corrected" with
>> reference to the errata given elsewhere in the book itself. You may see the
>> note I used in my second (corrected) file. So the user would be informed
>> why the text is different than the printed text seen in that page.
>>
>> On Sat, 26 Dec 2020, 07:30 funderburkjim, <notifications@github.com>
>> wrote:
>>
>>> One possible solution
>>>
>>> Rearrange the records so that supplement records are just after the
>>> corresponding
>>> original records.
>>>
>> Yes, this is exactly what I did in my first file, not line by line, but
> part by part as appropriate.
>
> We at Andhrabharati treat data as "logical blocks", not by lines!!
>
> This involves change L-numbers. For instance,
>>>
>>> <L>130013<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3
>>>
>>> <s>pra-°kriyA</s> ¦ <lex>f.</lex> producing, production, <ls>Sarvad.</ls><info lex="f"/>
>>>
>>> <LEND>
>>>
>>> <L>130013.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  production, creation, origin, <ls>Sarvad.</ls><info n="sup"/><info lex="inh"/>
>>>
>>> <LEND>
>>>
>>>
>>>
>>>
>>>
>>> <L>130014<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  procedure, way, manner, <ls>MBh.</ls><info lex="inh"/>
>>>
>>> <LEND>
>>>
>>> <L>130014.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦ form, procedure, method, mode, manner, <ls>MBh.</ls><info n="sup"/>
>>>
>>> <LEND>
>>>
>>>
>>>
>>> <L>130015<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  a ceremony, observance, formality, <ls>Hariv.</ls>; <ls>Kathās.</ls>; <ls>Rājat.</ls><info lex="inh"/>
>>>
>>> <LEND>
>>>
>>> <L>130015.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦ a ceremony, <ls>Hariv.</ls>; <ls>Kathās.</ls><info n="sup"/>
>>>
>>> <LEND>
>>>
>>>
>>>
>>> <L>130016<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  precedence, high position, elevation, privilege, <ls>MBh.</ls>; <ls>Rājat.</ls>; <ls>Kathās.</ls><info lex="inh"/>
>>>
>>> <LEND>
>>>
>>> <L>130016.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦ formality, <ls>Rājat.</ls><info n="sup"/>
>>>
>>> <LEND>
>>>
>>> <L>130016.2<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦ prerogative, privilege, high rank or position, excellence, superiority, <ls>MBh.</ls>; <ls>Kathās.</ls> &c.<info n="sup"/>
>>>
>>> <LEND>     NOTE 2 supplement records seem to 'belong' to 130016
>>>
>>>
>>>
>>> <L>130017<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  the insignia of high rank, <ls>Rājat.</ls><info lex="inh"/>
>>>
>>> <LEND>
>>>
>>> <L>130017.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦ the insignia of high rank or dignity, <ls>Rājat.</ls>; <ls>Gīt.</ls><info n="sup"/>
>>>
>>> <LEND>
>>>
>>>
>>>
>>> <L>130018<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  characterisation, <ls>Nyāyas.</ls><info lex="inh"/>
>>>
>>> <LEND>
>>>
>>> <L>130018.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦ characterization, <ls>Nyāyas.</ls><info n="sup"/>
>>>
>>> <LEND>     NOTE: This is just a spelling change
>>>
>>>
>>>
>>> <L>130019<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  a chapter (<ab>esp.</ab> the introductory <ab n="chapter">ch°</ab> of a work), <ls>Śaṃk.</ls>; <ls>Cat.</ls><info lex="inh"/>
>>>
>>> <LEND>
>>>
>>> <L>130019.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦ a chapter, section (often at the end of titles of books)<info n="sup"/>
>>>
>>> <LEND>
>>>
>>>
>>>
>>> <L>130020<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  (in med.) a prescription, <ls>Bhpr.</ls><info lex="inh"/>
>>>
>>> <LEND>
>>>
>>> <L>130020.1<pc>1330,2<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦ medical prescription, <ls>Bhpr.</ls><info n="sup"/>
>>>
>>> <LEND>
>>>
>>>
>>>
>>> <L>130021<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  (in gram.) etymological formation<info lex="inh"/>
>>>
>>> <LEND>
>>>
>>> <L>130022<pc>653,3<k1>prakriyA<k2>pra-kriyA<e>3A
>>>
>>> ¦  rules for the <ab n="formation">f°</ab> and inflection of words, <ls>MW.</ls><info lex="inh"/>
>>>
>>> <LEND>
>>>
>>>
>>> @Andhrabharati <https://github.com/Andhrabharati> Is this close to what
>>> you had in mind?
>>>
>> Yes, this would be useful for easier crosschecking etc. to have
internally; for the "common" end user, giving all this would be too much to
comprehend.

@drdhaval2785 <https://github.com/drdhaval2785> What do you think regarding

**Comment by Andhrabharati** [comment]
> @Andhrabharati <https://github.com/Andhrabharati>
> If you reply to the mail, kindly delete the text before you type anything.
> Otherwise the text of mail would unnecessarily get attached to the github
> issue.
>
Got it, will do that way henceforth.

I found replying through mail (which directly is pointed to the post/thread
to reply) is easier and hence tried that.
Otherwise I have to log into Github. go to resp. page and then reply, which
I thought is a longer way

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Andhrabharati** [comment]
> 
> 
> @Andhrabharati
> If you reply to the mail, kindly delete the text before you type anything. Otherwise the text of mail would unnecessarily get attached to the github issue.
> 
> You can view your last comment on github site (not in mail) and click on three dots at the end, to understand what I mean by 'unnecessary attachment'

Yes, I see that the mail reply is giving too much of unnecessary clutter.
This forum just needs to have clean and to-the-point messages.

So I have decided to take the longer way, to log-in and post/reply at Github itself. (The mail would just be treated that a new message/reply has been posted)

BTW, is there any other (better) way that one can automatically be notified of the new posts at the forum, without having to manually open and look at each post to see if anything new has come up?

**Comment by drdhaval2785** [comment]
You can open the repository you are interested in and click on 'watching' icon with eye icon. You can select 'All actiity'. This will send all new issues in your email account.

**Comment by Andhrabharati** [comment]
This is good; and I can directly come to the resp. thread from mail, by selecting "view to on Github" to respond (if any).

**Comment by gasyoun** [comment]
> One way that might be useful would be to rearrange the records so that, if possible,
the corrections are just after the record being corrected. 

Agree, `corrections are just after`

**Comment by Andhrabharati** [comment]
> No, we need to be able to track what has been inserted. So when looking at the scan I can understand were the difference comes from.
I do understand this need, but like to have it stored internally, not to display to the outside word as the search result.

> > Many additions and corrections were already incorporated in the present text, without resirting to any such complex/long criteria as you are mentioning now.
> And I disagree with such an approach. People will start asking questions. Unneeded questions that take time.
Exactly; for this only, I suggested to put a simple note at the end of the data; as the main text ref. and errata text ref. will be there, interested people can compare them (but I rarely see any user putting that much effort - everyone seems to be just living/satisfied with what is shown to them)! Did any one ever questioned you guys so far, for the already integrated entries already in the data?

So, at the end of it, can I take that the forum, now in principle, is agreeing to make the integration of main & errata text appropriately?

If some is going to come forward to make corrections, I can start making the list and send across.

**Comment by gasyoun** [comment]
> but like to have it stored internally, not to display to the outside word as the search result.

We are on the same page.

> everyone seems to be just living/satisfied with what is shown to them

Not so, actually.

> Did any one ever questioned you guys so far, for the already integrated entries already in the data?

Jim receives many letters of many issues.

> So, at the end of it, can I take that the forum, now in principle, is agreeing to make the integration of main & errata text appropriately?

We still have to decide on technical parts.

> If some is going to come forward to make corrections, I can start making the list and send across.

That sounds like a good plan, let us hear @funderburkjim opinion.

**Comment by Andhrabharati** [comment]
> > Did any one ever questioned you guys so far, for the already integrated entries already in the data?
> 
> Jim receives many letters of many issues.

I am not talking about regular feedback, but specifically about the already "merged" entries at MW99.
Did anyone raise a point on them, that they are not as per the printed book or scan?

**Comment by drdhaval2785** [comment]
No such issues were raised in recent past. 
At the same time, Jim has been methodical enough to document almost all of the changes made to each file from the date of receipt of first digitization to the present day.

Till date, addenda and corrigenda are not merged inside the main text for majority of dictionaries.

Therefore, it would be necessary to device some way about how to make these changes, and still retain some information about the changes made.

**Comment by drdhaval2785** [comment]
For sake of simplicity, I would propose to do almost the same thing which @Andhrabharati has suggested.

We can implement addenda corrigenda for a given dictionary in a single commit directly in xxx.txt file itself, and note that commit number in history.txt file of that dictionary. This would take care of our concerns. 

In case we want to highlight the changes, we can give a link to this commit.

**Comment by Andhrabharati** [comment]
> Till date, addenda and corrigenda are not merged inside the main text for majority of dictionaries.
> 

Does it mean that in some dictionaries it is done?

**Comment by Andhrabharati** [comment]
> At the same time, Jim has been methodical enough to document almost all of the changes made to each file from the date of receipt of first digitization to the present day.
> 

@funderburkjim,

I've been wondering since long (almost for over 10 years) about one issue noticed with MW99 data, and did not know whom to ask about it.

Recently when I came in contact with Dr Dhaval in a different context, and seeing his name in the Koeln maintenance team, enquired with him about the same. He said he has no clue of it.

The image provided at https://www.sanskrit-lexicon.uni-koeln.de/talkMay2008/markingMonier.html of the very initial attempt of MW digitisation (print page vs. typed matter) shows that from day-1 this issue has been there in the data.

Now that Dhaval gave a clue that you maintained all the changes that went in the gradual development of this work (rather every work under this project, I guess), I thought of asking you the same now.

The point in my mind is about **the missing (head)word endings before the gender indication** in the data, which is present in the MW book. Everyone knows that he took every care to see that all essential information is included in his dictionary.

These word endings have an important role in Skt. Grammar, and are very essential in forming composite words, in sandhi process or for joining vibhakti-pratyayas to the word itself. Every authentic Skt. dictionary invariably contains this piece of information.

Wonder why this has been not added all these days (it's almost 20 years now that the work started), though various attempts are undergoing about including other information, like adding Greek words etc.

**Has this not drawn any one's attention so far?**

Incidentally, seen that this information is there in other dictionaries taken up later, including MW72.

Can you pl. throw some light on this issue?
-------------------------
I strongly suggest adding this piece of "left" information in this work, to make it a "complete" counterpart to the original book.

**Comment by gasyoun** [comment]
> Therefore, it would be necessary to device some way about how to make these changes, and still retain some information about the changes made.

Right.

> In case we want to highlight the changes, we can give a link to this commit.

I remember seeing `Deutsche Mythologie` of Grimm brothers, where all the later digital insertions where marked by color (yellow gackground color).

**Comment by funderburkjim** [comment]
@Andhrabharati 

> the missing (head)word endings before the gender indication

Please open this as a separate issue -- it is unrelated to the 'Additions'  subject
of this issue.
And provide a specific example so we  understand.

**Comment by Andhrabharati** [comment]
> 
> The point in my mind is about **the missing (head)word endings before the gender indication** in the data, which is present in the MW book. Everyone knows that he took every care to see that all essential information is included in his dictionary.
> 
> These word endings have an important role in Skt. Grammar, and are very essential in forming composite words, in sandhi process or for joining vibhakti-pratyayas to the word itself. Every authentic Skt. dictionary invariably contains this piece of information.
> 
> Wonder why this has been not added all these days (it's almost 20 years now that the work started), though various attempts are undergoing about including other information, like adding Greek words etc.
> 
> **Has this not drawn any one's attention so far?**
> 

With this extract from the MW99 itself, which mentioned about the word-endings being provided, I stop talking on the matter.

![image](https://user-images.githubusercontent.com/75209130/103654056-69dbe800-4f8b-11eb-889c-d1cfd6be904f.png)
