### ISSUE TITLE
Two pages skipped from the attention of all for so long

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#81]
I have 1960 print of Oxford University Press and it has two pages at the front, "Addenda et Corrigenda", which are hitherto missed at Koeln data.

I suggest these entries to be included to the data, alongwith the already digitised "Additions and Corrections", the regular annexure of MW99.
[MW-Additional pages.pdf](https://github.com/sanskrit-lexicon/MWS/files/5740380/MW-Additional.pages.pdf)

**Comment by gasyoun** [comment]
> I suggest these entries to be included to the data

Does it look like a similar topic, @Andhrabharati ?
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/27

**Comment by Andhrabharati** [comment]
> Does it look like a similar topic, @Andhrabharati ?
> [sanskrit-lexicon/CORRECTIONS#27](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/27)
Yes, and my other post #80 could also be there.

Looks like I can be "the volunteer to come" there!!

**Comment by Andhrabharati** [comment]
> I have 1960 print of Oxford University Press and it has two pages at the front, "Addenda et Corrigenda", which are hitherto missed at Koeln data.
> 
> I suggest these entries to be included to the data, alongwith the already digitised "Additions and Corrections", the regular annexure of MW99.
> [MW-Additional pages.pdf](https://github.com/sanskrit-lexicon/MWS/files/5740380/MW-Additional.pages.pdf)

@funderburkjim, @drdhaval2785
request your attention to this post as well.

**Comment by gasyoun** [comment]
> Looks like I can be "the volunteer to come" there

20 years we were waiting for this day.

**Comment by Andhrabharati** [comment]
> 
> 
> > Looks like I can be "the volunteer to come" there
> 
> 20 years we were waiting for this day.

Surprising indeed; we (at Andhrabharati) were thinking all these years, that there would be many "takers" for the Skt. works, across the globe.

For Telugu, which is our primary area of work, we found that there are absolutely no "takers", but just "talkers" (uncountable of them)!!

**Comment by gasyoun** [comment]
> Surprising indeed; we (at Andhrabharati) were thinking all these years, that there would be many "takers" for the Skt. works, across the globe.

There are less than fingers on my hand.

**Comment by funderburkjim** [comment]
Yes, those two extra pages are definitely of interest.

Do you have some form of digitization already done?

**Comment by Andhrabharati** [comment]
> 
> 
> Yes, those two extra pages are definitely of interest.
> 
> Do you have some form of digitization already done?
> 
> Please provide full Bibliographic information.

One can get the scan of this print at https://archive.org/details/sanskritenglishd00moniuoft/mode/2up, if searched for "sanskrit english dictionary 1960 Monier williams".

The Bibliography matter as needed, could be gleaned from this.

Upon closer looking at the content now, I got two points of concern/debate-

1. the page numbers seem to be marked as xi and xii.

The new edition preface has the pages i-x and then the Introduction to the prev. edition started, first two pages of which are also marked for the same numbers xi and xii.

Could this be taken as a mistake (which we need to seriously think upon, as the people those days were meticulous enough for such things)?

2. The transliteration for च् and छ् are c and ch, in both MW72 and MW99, but these two pages have them as k and kh.

These two points are **against** for considering these to be part of MW99, but the strong points **for** considering them are (1) this print style is only to be seen in MW (to the best of my knowledge) and (2) these contents are absent in MW99 main  and annexure pages.

**Comment by Andhrabharati** [comment]
> 
>     1. The transliteration for च् and छ् are c and ch, in both MW72 and MW99, but these two pages have them as k and kh.
> 

Understood from https://github.com/sanskrit-lexicon/CORRECTIONS/issues/14, that these pages are from MD, not MW.

So based on this & also the difference in the transliteration scheme I mentioned above, I would like to get this thread closed.

**Comment by gasyoun** [comment]
> Could this be taken as a mistake (which we need to seriously think upon, as the people those days were meticulous enough for such things)?

Not mistake, intended.

**Comment by funderburkjim** [comment]
I think these two pages are indeed some additional supplement to MW99.  For example,
pragama  has several compounds in this additional supplement, but these are absent in mw99.  

We will take into account vagaries of IAST in the supplement -- we are used to modernizing
IAST.

Will check your archive.org reference for bibliography.

Since you did not mention, I presume you don't have digitization of these two supplement
pages.   We will undertake the digitization and integration into body of Cologne digitization.

That's the plan from as it looks now.

**Comment by drdhaval2785** [comment]
Jim, from discussion at https://github.com/sanskrit-lexicon/CORRECTIONS/issues/14 it seems that these pages are from MD, and not MW.

**Comment by Andhrabharati** [comment]
Jim,

Had downloaded the recording of skype meeting of 27.12.2020, as the link was shared by Marcis with me.

You are such a wonderful guy, devoting your life for the purpose.
I could only say, had we come in contact earlier, things would've been different by now at Koeln.

Interestingly there is a common point between you and us. You and both of us (at Andhrabharati) are unmarried and working with a purpose.

Now coming to the point under discussion-

1. I have verified that these two pages indeed are of MD, tallying for page numbers and the transliteration. And MD has credited the contribution of this Addenda to Cappeller in his preface.

![image](https://user-images.githubusercontent.com/75209130/103260384-6bbe0e00-49c3-11eb-9894-2ddc0269e1ed.png)

2. Looked at the Koeln file for this and these entries are present in it towards the end, ~27700 in the xml file, though some entries, glaringly the very beginning one of this Annexure, are missed in it.

No need for you to take up digitisation of the two pages now, but you have to see that full content is covered in your files.

3. Coming to entries not in MW, I can list not just 10s but 1000s, not covered by him, but you said that should be another issue/topic.

This addition of new entries is what, in my opinion, a new edition would be.

4. But incorporating the addenda into main text is just an activity that is covered in a reprint, as is the practice followed by many publishers, though some others prefer to just print the prev. text as is without putting time this additional work.

This is what Dhaval and me had in mind, in suggesting to incorporate the changes in the main text itself.

**Comment by Andhrabharati** [comment]
BTW, I thought closing an issue means no more discussions/updates regarding the point.

But things seems to be different here, still debating on "a closed issue".

**Comment by Andhrabharati** [comment]
Or is it that anyone is not supposed to close the issue, except the admin/owner (is there any such concept here?!)?

**Comment by gasyoun** [comment]
> Or is it that anyone is not supposed to close the issue, except the admin/owner (is there any such concept here?!)?

You have equal rights. Anyone can close. It's closed already.

**Comment by Andhrabharati** [comment]
I mean, if still discussions/posts occur on it, what is the purpose of having open or closed tags?

**Comment by drdhaval2785** [comment]
Purpose of closure is - The substantial question has been resolved. 

Usually if one diaagrees with the closure, he reopens the issue. But that does not preclude the managers from closing the issues.

**Comment by gasyoun** [comment]
> Usually if one diaagrees with the closure, he reopens the issue. But that does not preclude the managers from closing the issues.

Right.
