### ISSUE TITLE
MW supplement brief history

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#82]
Thomas Malten provided the initial digitization of Monier-Williams 1899 dictionary. 
This original work is still maintained on the home page https://www.sanskrit-lexicon.uni-koeln.de/  under [Sanskrit and Tamil Dictionaries, 2005](https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/tamil/index.html).

For example, look up 'prakriyA' in this display:
![image](https://user-images.githubusercontent.com/6393033/103160287-0b4f8680-47a1-11eb-953a-0d3eb22f1208.png)

Note that the supplement entries for prakriyA are absent.

On the Cologne server, the directory mwupdate/additions  contains historical 
material on the integration of the supplement.  
A readme.txt file (dated 10/30/2012) would be a reasonable starting point for anyone wanting to do software archeology on this topic.
[readme.txt](https://github.com/sanskrit-lexicon/MWS/files/5743986/readme.txt)

**Comment by funderburkjim** [comment]
Here are some approximate steps, as gleaned from review of mwupdate/additions.

## MONIER.ADD

As part of his original work in the 1990s, Thomas made a digitization of the
supplement to MW1899.  This is in file mwupdate/additions/orig/MONIER.ADD.
We actually had two similar forms of this file.

Here is a copy, dated 1996, of one of them.

It is in an unusual encoding, mostly cp1255; so it may be 

[MONIERADDcp1255.txt](https://github.com/sanskrit-lexicon/MWS/files/5743993/MONIERADDcp1255.txt)

This is what we started with.

**Comment by funderburkjim** [comment]
## ADD3.xml

When Peter Scharf, Malcolm Hyman and I became involved with Thomas, approximately
in 2004, an early goal was to convert his digitization of mw into an xml form.
This took several years and numerous false steps.
By 2008 or so,  we had a functioning
monier.xml and some first versions of displays
like today's Basic display.

Sometime before January 2010,  probably at Peter's suggestion, I undertook to
convert the MONIERADD digitization into an xml form compatible with that of monier.xml.  

The result was ADD3.xml.

[ADD3.xml.txt](https://github.com/sanskrit-lexicon/MWS/files/5744030/ADD3.xml.txt)

 prakriyA from the supplement was now 9 records:
<details><summary> prakriyA in ADD3.xml</summary>

```
<H2><h><hc3>000</hc3><key1>prakriyA</key1><hc1>1</hc1><key2>pra-kriyA</key2></h><body> <lex>f.</lex> production, creation, origin, <ls>Sarvad.</ls></body><tail><pc>1330,2</pc><L>336390</L></tail></H2>
<H2A><h><hc3>000</hc3><key1>prakriyA</key1><hc1>1</hc1><key2>pra-kriyA</key2></h><body> form, procedure, method, mode, manner, <ls>MBh.</ls></body><tail><pc>1330,2</pc><L>336390.1</L></tail></H2A>
<H2A><h><hc3>000</hc3><key1>prakriyA</key1><hc1>1</hc1><key2>pra-kriyA</key2></h><body> a ceremony, <ls>Hariv. ; </ls><ls>Katha1s.</ls></body><tail><pc>1330,2</pc><L>336390.2</L></tail></H2A>
<H2A><h><hc3>000</hc3><key1>prakriyA</key1><hc1>1</hc1><key2>pra-kriyA</key2></h><body> formality, <ls>Ra1jat.</ls></body><tail><pc>1330,2</pc><L>336390.4</L></tail></H2A>
<H2A><h><hc3>000</hc3><key1>prakriyA</key1><hc1>1</hc1><key2>pra-kriyA</key2></h><body> prerogative, privilege, high rank or position, excellence, superiority, <ls>MBh. ; </ls><ls>Katha1s.</ls> <etc/></body><tail><pc>1330,2</pc><L>336390.5</L></tail></H2A>
<H2A><h><hc3>000</hc3><key1>prakriyA</key1><hc1>1</hc1><key2>pra-kriyA</key2></h><body> the insignia of high rank or dignity, <ls>Ra1jat. ; </ls><ls>Gi1t.</ls></body><tail><pc>1330,2</pc><L>336390.7</L></tail></H2A>
<H2A><h><hc3>000</hc3><key1>prakriyA</key1><hc1>1</hc1><key2>pra-kriyA</key2></h><body> characterization, <ls>Nya1yas.</ls></body><tail><pc>1330,2</pc><L>336390.9</L></tail></H2A>
<H2A><h><hc3>000</hc3><key1>prakriyA</key1><hc1>1</hc1><key2>pra-kriyA</key2></h><body> a chapter, section (often at the end of titles of books)</body><tail><pc>1330,2</pc><L>336391</L></tail></H2A>
<H2A><h><hc3>000</hc3><key1>prakriyA</key1><hc1>1</hc1><key2>pra-kriyA</key2></h><body> medical prescription, <ls>Bhpr.</ls></body><tail><pc>1330,2</pc><L>336391.1</L></tail></H2A>

```
</details>

The record numbers started at L=300000.  

By this artifice with L-numbers, displays could readily include the supplement entries.

**Comment by funderburkjim** [comment]
## Further integration

At this point, the supplement entries were tacked onto the entries appearing in the
body -- completely analogous to the printed text.

At Peter's suggestion, in mid 2012 it was undertaken to further integrate the supplement entries.  
We took this to mean moving the supplement entries where they would belong 
within the body.   Sharon Ben-Dor  did much of the heavy lifting of deciding where
supplement entries belonged; and Pawan Goyal also contributed.

The result of these efforts was to create numerous delete/insert/update transactions
to monier.xml.

Probably these were the log_yyyymmdd_nn.txt files in 
mwupdate/additions/step3/updlogs directory.

The end result was an xml version of monier.xml very much like that of today, in that
the supplement records were repositioned to be near the corresponding body elements.

**Comment by funderburkjim** [comment]
This issue was written to provide some historical context to issue #80, where @Andhrabharati proposes a further improvement to the integration of the
supplement records.

**Comment by Andhrabharati** [comment]
Can this issue be closed now? 
(Unless @funderburkjim likes to add some more remarks here, after the present work on the subject matter happening with AB contribution)

**Comment by funderburkjim** [comment]
Fine with me to close.
