### ISSUE TITLE
MW missing feminine data

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/MWS#84]
https://github.com/sanskrit-lexicon/MWS/issues/80#issuecomment-751368563

Where @Andhrabharati asked a question regarding gender information in MW digitization. 
@funderburkjim has asked him to provide an example. 
This is a placeholder for that issue.

**Comment by Andhrabharati** [comment]
> [#80 (comment)](https://github.com/sanskrit-lexicon/MWS/issues/80#issuecomment-751368563)
> 
> Where @Andhrabharati asked a question regarding gender information in MW digitization.
> @funderburkjim has asked him to provide an example.
> This is a placeholder for that issue.

@drdhaval2785, I am not talking about feminine data, but about all word endings.

On feminine data also, I have some observation(s), which I might post sometime later.

**Comment by Andhrabharati** [comment]
With this extract from the MW99 itself, which mentioned about the word-endings being provided, I stop talking on the matter.

![image](https://user-images.githubusercontent.com/75209130/103654056-69dbe800-4f8b-11eb-889c-d1cfd6be904f.png)

**Comment by Andhrabharati** [comment]
This issue does not need any more discussion (as my current full review takes care of this), and can be closed now.
