### ISSUE TITLE
How is <bot> tag applied?

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/MWS#87]
Kindly look at the following two entries in mw.xml file
```
<H1><h><key1>amlowa</key1><key2>amlowa</key2></h><body><s>amlowa</s>   <lex>m.</lex> ebony, Diospyros Ebenaster, <ls>L.</ls><info n="sup"/><info lex="m"/></body><tail><L>14655.1</L><pc>1316,1</pc></tail></H1>
<H3><h><key1>SiKIndra</key1><key2>SiKIndra</key2></h><body><s>SiKI<srs/>ndra</s>   <lex>m.</lex> ebony, <bot>Diospyros Ebenaster</bot>, <ls>L.</ls><info lex="m"/></body><tail><L>216773</L><pc>1071,1</pc></tail></H3>
```

The same words `Diospyros Ebenaster` appear in both entries.
But the first is not marked with `bot` tag, whereas the second is.

Can @funderburkjim tell why the same string is tagged somewhere and not tagged somewhere?
Can we programmatically find out such cases and apply the `bot` or `bio` tag appropriately to all occurences?

**Comment by gasyoun** [comment]
> The same words Diospyros Ebenaster appear in both entries.
But the first is not marked with bot tag, whereas the second is.

Seen several such before.

**Comment by Andhrabharati** [comment]
@drdhaval2785 

As the "subject issue" would be dealt at #74, this issue could be closed.

What do you think?
