### ISSUE TITLE
A query on MW search & display

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#88]
I just did a search with "exact" option, for 'a' in "Headwords", and this is what I got-

![a query on MW search-display result](https://user-images.githubusercontent.com/75209130/103442245-7bb34780-4c7a-11eb-9853-47072d4446dd.png)

1. I see 14 entries with "|a" (SLP) at the end of the HW, in addition to the expected single result for 'a'.

2. And all these 14 are displayed without 'a' at the end, say "ajamI|a" as "ajamI|".

3. In the results of 'a' having 6 homonyms, 5 are shown as 1. अ, 2. अ, 3. अ, 5. अ, 6. अ, but the 4th one as  अ 4 (no dot and number after the entry word) - why is this 4th one like this?
(One, with a keen eye, expects consistency to be maintained throughout)

**Comment by Andhrabharati** [comment]
I guess, all words having this '|' would be having such issues.

**Comment by Andhrabharati** [comment]
Now I searched with "substring" option, for this '|' in "Headwords", and this is what I got-

![image](https://user-images.githubusercontent.com/75209130/103442578-6d1a5f80-4c7d-11eb-8c06-681937c3ac0e.png)

The left-side of result window says "No matches found" and right-side windows shows plenty of words which do not contain this character at all; both these are wrong, as per the internal data (XML file)

**Comment by Andhrabharati** [comment]
**I just assumed the role of a validator, in the user perspective!!**

**Comment by Andhrabharati** [comment]
Based on the data inside, one should get a result screen like this-

![image](https://user-images.githubusercontent.com/75209130/103442712-c5059600-4c7e-11eb-8501-21f232c4cc0d.png)

(of course this does not treat '|' as ’Lh’ as per the book, but just as a character '|').

**Comment by drdhaval2785** [comment]
Nice catch!

This is indeed a bug.

**Comment by Andhrabharati** [comment]
'|' point?

what about the "अ 4" point? of course this is not a display error, but data error - the typing is done like that.

**Comment by Andhrabharati** [comment]
We did follow the internal data truly, and both these errors do not occur with us (at Andhrabharati)- no extra results nor inconsistency in representation.

![image](https://user-images.githubusercontent.com/75209130/103442927-4f022e80-4c80-11eb-84f5-71f22b9114cd.png)

![image](https://user-images.githubusercontent.com/75209130/103442951-73f6a180-4c80-11eb-9121-841bda340195.png)

**Comment by Andhrabharati** [comment]
BTW, one may see the extra work we did at Andhrabharati, padding "N. " at each of the latter senses, thus making the entry more meaningful, while displaying. 

**Pl. compare the results for **ajamILha** of Koeln and AB at attached in the above images.**

In a printed book, many such techniques are adopted to save space, but still as it is a continuous running matter, the user mentally pads this part while reading the book.

In the digital text, there is no need to bother to save space, and if the split line is read independently, it does not immediately give the full sense (which one would get while reading in a book). In the present case, the display of 'of X' just means (something) belonging to X, (which could be any attribute/property- computer terminology!!) unless one goes to above line(s) and finds this "N. ". If the meanings are too many, as is the case many times, this particular "N. " would be far away from the particular line being looked at.

**So we presumed this would benefit the reader at once without reference to anywhere else; though on the face of it is deviating from the printed matter, is very much near to the mind of the composer.** We tried to do some such improvements (value-additions) in the digital data- our intention being more user-friendly, but maintaining the original text without too much of changes.

**Comment by gasyoun** [comment]
> BTW, one may see the extra work we did at Andhrabharati, padding "N. " at each of the latter senses, thus making the entry more meaningful, while displaying.

Hmm, have to explore it more, to understand what has been done and why.

> In a printed book, many such techniques are adopted to save space, but still as it is a continuous running matter, the user mentally pads this part while reading the book.

Agree.

> If the meanings are too many, as is the case many times, this particular "N. " would be far away from the particular line being looked at.

Indeed.

> So we presumed this would benefit the reader at once without reference to anywhere else; though on the face of it is deviating from the printed matter, is very much near to the mind of the composer. We tried to do some such improvements (value-additions) in the digital data- our intention being more user-friendly, but maintaining the original text without too much of changes.

Not all additions are bad just because not in the book.

**Comment by Andhrabharati** [comment]
Another major reduction technique adopted is with bigger words, which got split with sandhi & samAsa criteria, and are clubbed together under some "parent" HW.

We named them as "composite words" and have them all "formed" into their full form, which makes them directly searcheable upon.

**Comment by Andhrabharati** [comment]
We have this as a std. theme in all the works we did; noted that Koeln too has them thus, but just in one of their works, namely this MW99.

**Comment by Andhrabharati** [comment]
We just had envisaged how the original work would have been done, had there been no constraint in terms of space/pages, in a digital format that we are putting them now.

And we'ce identified points like these and some more, in the process.

**Comment by Andhrabharati** [comment]
> 
> > BTW, one may see the extra work we did at Andhrabharati, padding "N. " at each of the latter senses, thus making the entry more meaningful, while displaying.
> 
> Hmm, have to explore it more, to understand what has been done and why.
> 

Adding these (from the images above) just for quick comparison, on what has been mentioned.

![image](https://user-images.githubusercontent.com/75209130/103450562-68d25e80-4cde-11eb-8f93-8c14b6669418.png)

![image](https://user-images.githubusercontent.com/75209130/103450574-869fc380-4cde-11eb-9d43-e14ce2f72f42.png)

**Comment by Andhrabharati** [comment]
As the intended '|' point is attended by @funderburkjim sometime back, this issue is closable now.
