### ISSUE TITLE
Extract Pages With Issues (For Reference Purposes)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#9]
Let's propose I want to kill the $ places in MW and replace them with the Arabic text they want. I've made a list of those instances (sample http://pastebin.com/a9Au3SyP) and would want to know a way to have a .pdf or collections of .jpgs with only the wanted pages, not the whole book, any idea?

**Comment by drdhaval2785** [comment]
With development of servepdf, this has become redundant.
Please see https://github.com/sanskrit-lexicon/csl-apidev/blob/master/doc/servepdf.md for ways to call the pages based on headword or lnum.
