### ISSUE TITLE
IdfSIdfktA to be converted to IdfktA

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/MWS#91]
Wrong parsing of IdfktA as IdfSIdfktA in 29742 Lnum

```
<L>29741<pc>170,2<k1>IdfS<k2>I-df/S<e>2
<s>I-df/S</s> ¦ <lex>mfn.</lex> <s>k</s> (<ab>Ved.</ab> <s>N</s>, <ls>Pāṇ. 7-1, 83</ls>) endowed with such qualities, such, <ls>VS.</ls>; <ls>TS.</ls>; <ls>ŚBr.</ls>; <ls>Śak.</ls>; <ls>Pañcat.</ls> &c.<info lex="m:f:n"/>
<LEND>
<L>29741.1<pc>170,2<k1>IdfS<k2>I-df/S<e>2B
<s>I-df/S</s> ¦ <lex>f.</lex> (<s>k</s>) such a condition, such occasion, <ls>RV.</ls>; <ls>AV.</ls><info lex="f"/>
<LEND>
<L>29742<pc>170,2<k1>IdfSIdfktA<k2>I-df/S—Idfk-tA<e>3
<s>I-df/S—Idfk-tA</s> ¦ <lex>f.</lex> quality, <ls>Ragh.</ls>; <ls>Daś.</ls><info lex="f"/>
<LEND>
```

**Comment by drdhaval2785** [comment]
![capture](https://user-images.githubusercontent.com/5755132/103474593-816c7280-4dcb-11eb-8a38-4ea10f59d472.PNG)

**Comment by drdhaval2785** [comment]
Are there such others, @funderburkjim ?

**Comment by Andhrabharati** [comment]
This is the case I've been talking about all these days, eversince I started "**interacting**"! (word-endings not being considered or ignored.

![image](https://user-images.githubusercontent.com/75209130/103476141-2ccff400-4dd9-11eb-82e5-71141f3b793a.png)

**Comment by funderburkjim** [comment]
@drdhaval2785   Definitely a bug.   Assume you will correct.

The following seems to me a similar example, where no similar error is present.
```
<L>45<pc>1,1<k1>aMSin<k2>aMSin<e>2
<s>aMSin</s> ¦ <lex>mfn.</lex> having a share, <ls>Yājñ.</ls><info lex="m:f:n"/>
<LEND>
<L>46<pc>1,1<k1>aMSitA<k2>aMSi-tA<e>3
<s>aMSi-tA</s> ¦ <lex>f.</lex> the state of a sharer or co-heir, heirship.<info lex="f"/>
<LEND>
```
![image](https://user-images.githubusercontent.com/6393033/103497100-7129b700-4e0e-11eb-9a09-a5997d89e57b.png)

> Are there such others?

I don't see how to define 'such others' in such a way to search for others.  I have seen examples 
where compounds in mw were similarly incorrectly constructed so that the 'parent' of the compound
was erroneously duplicated.  But these have been rare.

**Comment by funderburkjim** [comment]
@Andhrabharati 

> word-endings not being considered or ignored

I think this is related to your issue #85,  which I have not had a chance to read yet, but hope to read soon.

**Comment by gasyoun** [comment]
> This is the case I've been talking about all these day

What does `k` stand for? Word ending?

**Comment by Andhrabharati** [comment]
> 
> 
> > This is the case I've been talking about all these day
> 
> What does `k` stand for? Word ending?

YES.

**īdr̥s** becomes **īdr̥k** to form composite forms, or for other grammatical purposes.
In this case, it has formed the feminine form **īdiktā**.

**Comment by Andhrabharati** [comment]
Let’s take a very popular word, r̥k, as an example.

![image](https://user-images.githubusercontent.com/75209130/103519010-c01d2e00-4e9a-11eb-8134-a52e535bef7e.png)

r̥c can become r̥k, 

![image](https://user-images.githubusercontent.com/75209130/103519125-fbb7f800-4e9a-11eb-9e35-55872e88922e.png)

which in turn can become r̥g 

![image](https://user-images.githubusercontent.com/75209130/103519180-15593f80-4e9b-11eb-8e1b-d29d979c5661.png)
(Note the r̥gveda in here)

or r̥ṅ

![image](https://user-images.githubusercontent.com/75209130/103519236-33bf3b00-4e9b-11eb-8e7b-7ec8c1e50094.png)

**Comment by Andhrabharati** [comment]
Few entries like this are lucky enough to be put as HWs here, thus retaining the word-endings.

Others just indicated at the main (parent) entry got ignored/lost in this Koeln MW99 digitization. (**Of course, they are properly in place in the later additions at Koeln.**)

My main concern is that- as this MW99 being treated as a **Base work** here to relate all other works to it, it should be as much complete as possible.

**Comment by Andhrabharati** [comment]
And here is one entry from <pc>1,3, which has the variant form of the HW (additionally)-

![image](https://user-images.githubusercontent.com/75209130/103529565-e39ca480-4eab-11eb-8538-34d8b337cca7.png)

having **akartr̥** the main HW, and **akartā** the additional form (which can be found listed in SKD, with a citation from the bhagavadgītā)

**Comment by gasyoun** [comment]
> My main concern is that- as this MW99 being treated as a Base work here to relate all other works to it, it should be as much complete as possible.

Fully agree and thanks for the examples.

> having akartr̥ the main HW, and akartā the additional form (which can be found listed in SKD, with a citation from the bhagavadgītā

Great, so it will add more alternate headwords, perfect.

**Comment by Andhrabharati** [comment]
The only way to fill these is manual way, nothing else!!

**Comment by gasyoun** [comment]
> The only way to fill these is manual way

So your list of headwords is bigger? Or it has correct samāsas versus wrong ones at Cologne?

**Comment by Andhrabharati** [comment]
Obviously!

**Comment by Andhrabharati** [comment]
Finally, I am handling this myself in the current full review, and the issue is closable now.
