### ISSUE TITLE
Ka or KA

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/MWS#93]
What should the headword be?
![capture](https://user-images.githubusercontent.com/5755132/103474723-aad9ce00-4dcc-11eb-8b8e-d10a85aeafea.PNG)

**Comment by drdhaval2785** [comment]
Same in SaNKa / SaNKA
![capture](https://user-images.githubusercontent.com/5755132/103474767-0c9a3800-4dcd-11eb-8112-393549981392.PNG)

**Comment by drdhaval2785** [comment]
Same in SaSa / SaSI
![capture](https://user-images.githubusercontent.com/5755132/103474782-39e6e600-4dcd-11eb-9f80-2ca1e85bb51a.PNG)

**Comment by Andhrabharati** [comment]
I think I've taken the entry just preceding the cf. line, in all these cases.
Guess, they should all be tagged to the Main entry word at the top, as is the case everywhere else.

**Comment by drdhaval2785** [comment]
I am ignoring this feature in comparision. 
As @Andhrabharati thinks that this requires to be tagged to 'SiKa' and not to 'SiKA', I am closing this issue.
Cologne has them under SiKa.

**Comment by gasyoun** [comment]
> Guess, they should all be tagged to the Main entry word at the top, as is the case everywhere else.

So mistagged from @Andhrabharati ?

**Comment by Andhrabharati** [comment]
> 
> 
> > Guess, they should all be tagged to the Main entry word at the top, as is the case everywhere else.
> 
> So mistagged from @Andhrabharati ?

Not exactly!
The purpose here is more about the Greek words at resp. lines, where they are - the HWs given being just pointers to reach there.
