### ISSUE TITLE
List of works and Authors in MW99

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#94]
I have seen that quite a few entries are yet to be "deciphered" under this topic.

There are couple of variants in this part of work-
1. Listed in the MW book as abbr.; some are yet to get the full form by proper identification.
2. Not listed at abbr. section, but present inside the book; some are yet to get the full form by proper identification.
3. Wrongly mentioned in the book - a major task to get corrected without some background knowledge/understanding in Indian Skt. works themselves

Though the first and second varieties could be "handled" by Koeln team, if not today but by some time in future, I am quite sure that Koeln team (by itself) could NEVER ever be able to get the third variety correct.

As an example of this 3rd variety, I would like to mention one particular entry, as under-

> Six (6) entries have "Rev." as an \<ab\>, preceded by \<ls\>ŚivaP.\</ls\>. This is an error by MW (and/or the revising team).
> 
> This should have been \<ls\>SkandaP. Rev(ākhaṇḍa).\</ls\> which part of that work exclusively talks about various <tīrtha>s throughout India (or Āryāvarta).
>

**Comment by gasyoun** [comment]
> Koeln team (by itself) could NEVER ever be able to get the third variety correct.

How many more you are aware of? I love the fire in your words. Let us see if it gets to works.

**Comment by Andhrabharati** [comment]
Aren't what I am posting count as "works"? (atleast they should speak of the way I think, if not of my work)

**Comment by gasyoun** [comment]
> (atleast they should speak of the way I think, if not of my work)

They do in a very well manner. Will see how they scale.

**Comment by Andhrabharati** [comment]
As the `<ls>` entries are being handled in other issues, this can be closed now.
